force-app/main/default/objects/Participation_Activity_Profile_Data__c/Participation_Activity_Profile_Data__c.object-meta.xml
<CustomObject>
    <label>Participation Activity Profile Data</label>
    <nameField>
        <label>NSO Participation Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participation Activity Profile Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation_Activity_Profile_Data__c/fields/Delivery_Context__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Context__c</fullName>
    <label>Delivery Context</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Club</fullName>
            </value>
            <value>
                <fullName>Tertiary</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Primary School</fullName>
            </value>
            <value>
                <fullName>Secondary School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participation_Activity_Profile_Data__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participation Activity Profile Data</relationshipLabel>
    <relationshipName>Participation_Activity_Profile_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation_Activity_Profile_Data__c/fields/Percentage_of_Adults__c.field-meta.xml
<CustomField>
    <fullName>Percentage_of_Adults__c</fullName>
    <label>Percentage of Adults</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Participation_Activity_Profile_Data__c/fields/Percentage_of_Young_People__c.field-meta.xml
<CustomField>
    <fullName>Percentage_of_Young_People__c</fullName>
    <label>Percentage of Young People</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Participation_Data__c/Participation_Data__c.object-meta.xml
<CustomObject>
    <label>Participation Data</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Participation Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation_Data__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Programme_Name__r.End_Date__c</formula>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Participation_Data__c/fields/Programme_Name__c.field-meta.xml
<CustomField>
    <fullName>Programme_Name__c</fullName>
    <label>Programme Name</label>
    <referenceTo>Participation_Activity_Profile_Data__c</referenceTo>
    <relationshipLabel>Participation Data</relationshipLabel>
    <relationshipName>Participation_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation_Data__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Programme_Name__r.Start_Date__c</formula>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Participation_DataControllerTest.cls
@isTest
private class Participation_DataControllerTest {
    /*
     @ Description : Method to insert Participation Data
    */
    private static testmethod void testSavePartData() {
        //creating test data
        list<Account> accList = RUL_Util.createAccounts();
        insert accList ;
        
        Participation_Activity_Profile_Data__c newObj = new Participation_Activity_Profile_Data__c();
        newObj.Organisation__c = accList[0].Id;
        newObj.Start_Date__c = system.today();
        newObj.End_Date__c = system.today();
        newObj.Delivery_Context__c = 'Club';
        newObj.Percentage_of_Adults__c = 10;
        newObj.Percentage_of_Young_People__c = 10;
        insert newObj;
        
        PageReference newPageRef = Page.Participation_Data;
        newPageRef.getParameters().put('Id',newObj.Id);
        Test.setCurrentPage(newPageRef);
        
        Participation_DataController temp = new Participation_DataController();
        temp.save();
        temp.cancel();
        
       // System.assertEquals(1, [select count() from Participation_Data__c WHERE Programme_Name__c =: newObj.id]);       
    }
}