force-app/main/default/objects/Initiative_Development_Template__c/Initiative_Development_Template__c.object-meta.xml
<CustomObject>
    <description>Partnerships Investment 
Used when partners want to develop new initiatives for investment areas within their Partnerships Investment</description>
    <label>Initiative Development Template</label>
    <nameField>
        <displayFormat>IDT-{000000}</displayFormat>
        <label>Initiative Development Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Initiative Development Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Amount_of_Investment_Year_1__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Investment_Year_1__c</fullName>
    <description>How much of your total investment will be allocated to this initiative in Year 1</description>
    <inlineHelpText>How much of your total investment will be allocated to this initiative in Year 1</inlineHelpText>
    <label>Amount of Investment Year 1</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Amount_of_Investment_Year_2__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Investment_Year_2__c</fullName>
    <description>How much of your total investment will be allocated to this initiative in Year 2</description>
    <inlineHelpText>How much of your total investment will be allocated to this initiative in Year 2</inlineHelpText>
    <label>Amount of Investment Year 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Amount_of_Investment_Year_3__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Investment_Year_3__c</fullName>
    <description>How much of your total investment will be allocated to this initiative in Year 3</description>
    <inlineHelpText>How much of your total investment will be allocated to this initiative in Year 3</inlineHelpText>
    <label>Amount of Investment Year 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <defaultValue>(&quot;2022 - 2024&quot;)</defaultValue>
    <description>Select the financial year that your investment relates to.</description>
    <inlineHelpText>Select the financial year that Sport NZ is investing for.</inlineHelpText>
    <label>Financial Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021 - 2022</fullName>
            </value>
            <value>
                <fullName>2021 - 2024</fullName>
            </value>
            <value>
                <fullName>2022-2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/How_will_you_measure_success_in_Year_1__c.field-meta.xml
<CustomField>
    <fullName>How_will_you_measure_success_in_Year_1__c</fullName>
    <description>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</description>
    <inlineHelpText>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</inlineHelpText>
    <label>How will you measure success in Year 1</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/How_will_you_measure_success_in_Year_2__c.field-meta.xml
<CustomField>
    <fullName>How_will_you_measure_success_in_Year_2__c</fullName>
    <description>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</description>
    <inlineHelpText>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</inlineHelpText>
    <label>How will you measure success in Year 2</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/How_will_you_measure_success_in_Year_3__c.field-meta.xml
<CustomField>
    <fullName>How_will_you_measure_success_in_Year_3__c</fullName>
    <description>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</description>
    <inlineHelpText>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</inlineHelpText>
    <label>How will you measure success in Year 3</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/How_will_you_measure_success_in_Year_4__c.field-meta.xml
<CustomField>
    <fullName>How_will_you_measure_success_in_Year_4__c</fullName>
    <description>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</description>
    <inlineHelpText>What measures will you use to demonstrate you are achieving your outcomes?
This will form your monitoring and evaluation</inlineHelpText>
    <label>How will you measure success in Year 4</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Initiative_Name__c.field-meta.xml
<CustomField>
    <fullName>Initiative_Name__c</fullName>
    <description>Enter the name of your Initiative</description>
    <inlineHelpText>Enter the name of your Initiative</inlineHelpText>
    <label>Initiative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <label>Investment Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Leadership and Connectivity</fullName>
            </value>
            <value>
                <fullName>Insights and Evaluation</fullName>
            </value>
            <value>
                <fullName>Spaces and Places</fullName>
            </value>
            <value>
                <fullName>Play</fullName>
            </value>
            <value>
                <fullName>Active Recreation</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Physical Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Number_of_FTE_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Number_of_FTE_Allocated__c</fullName>
    <description>Please enter the number of FTE that will be dedicated to this initiative.  This is for all employees named in the &quot;Who will lead this area?&quot; question.</description>
    <inlineHelpText>Please enter the number of FTE that will be dedicated to this initiative.  This is for all employees named in the &quot;Who will lead this area?&quot; question.</inlineHelpText>
    <label>Number of FTE Allocated</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiative Development Templates</relationshipLabel>
    <relationshipName>Initiative_Development_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Initiative_Development_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Sign_Off_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Sign_Off_Approval_Date__c</fullName>
    <description>Enter the date that the Initiative was approved by Investment, Partnerships and Expertise and Capability</description>
    <inlineHelpText>Enter the date that the Initiative was approved by Investment, Partnerships and Expertise and Capability</inlineHelpText>
    <label>Sign-Off Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/SME_Approvers__c.field-meta.xml
<CustomField>
    <fullName>SME_Approvers__c</fullName>
    <description>SME&apos;s who have approved this initiative</description>
    <inlineHelpText>Enter your name if you have approved the initiative or a component of the initiative</inlineHelpText>
    <label>SME Approvers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/SME_Comments__c.field-meta.xml
<CustomField>
    <fullName>SME_Comments__c</fullName>
    <description>Enter your comments on the initiative for the Approval team</description>
    <inlineHelpText>Enter any commentary that the Approval team need to take in to consideration when approving this initiative</inlineHelpText>
    <label>SME Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Sport_NZ_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Sport_NZ_Feedback__c</fullName>
    <description>Sport NZ Feedback on the draft initiative.</description>
    <inlineHelpText>The information in this box is Sport NZ&apos;s feedback on your initiative.  Please consider Sport NZ&apos;s feedback as you finalise your initiative.</inlineHelpText>
    <label>Sport NZ Feedback</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Needs Reviewing</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/What_activity_will_you_do_in_Year_1__c.field-meta.xml
<CustomField>
    <fullName>What_activity_will_you_do_in_Year_1__c</fullName>
    <description>What work will your organisation do to achieve the outcomes you have said you will achieve?</description>
    <inlineHelpText>What work will your organisation do to achieve the outcomes you have said you will achieve?</inlineHelpText>
    <label>What activity will you do in Year 1</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/What_activity_will_you_do_in_Year_2__c.field-meta.xml
<CustomField>
    <fullName>What_activity_will_you_do_in_Year_2__c</fullName>
    <description>What work will your organisation do to achieve the outcomes you have said you will achieve?</description>
    <inlineHelpText>What work will your organisation do to achieve the outcomes you have said you will achieve?</inlineHelpText>
    <label>What activity will you do in Year 2</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/What_activity_will_you_do_in_Year_3__c.field-meta.xml
<CustomField>
    <fullName>What_activity_will_you_do_in_Year_3__c</fullName>
    <description>What work will your organisation do to achieve the outcomes you have said you will achieve?</description>
    <inlineHelpText>What work will your organisation do to achieve the outcomes you have said you will achieve?</inlineHelpText>
    <label>What activity will you do in Year 3</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/What_outcomes_will_you_achieve__c.field-meta.xml
<CustomField>
    <fullName>What_outcomes_will_you_achieve__c</fullName>
    <description>Enter the outcomes from the Sport NZ Intervention Logic for this Investment Area</description>
    <inlineHelpText>Enter the outcomes from the Sport NZ Intervention Logic for this Investment Area</inlineHelpText>
    <label>What outcomes will you achieve?</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/What_Risks_have_been_identified__c.field-meta.xml
<CustomField>
    <fullName>What_Risks_have_been_identified__c</fullName>
    <description>What risks have been identified that may impact you achieving the outcomes you have said you will achieve.</description>
    <inlineHelpText>List all the risks that have been identified that may impact you achieving the outcomes you have said you will achieve.</inlineHelpText>
    <label>What Risks have been identified?</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Initiative_Development_Template__c/fields/Who_will_lead_this_area__c.field-meta.xml
<CustomField>
    <fullName>Who_will_lead_this_area__c</fullName>
    <description>Enter the role and name of the person or people who will be responsible for this initiative</description>
    <inlineHelpText>Enter the role and name of the person who will be responsible for this initiative.  If this is split between more than one person, please provide all names and roles.</inlineHelpText>
    <label>Who will lead this area?</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloneIDTController.cls
public class CloneIDTController {
    
    public Initiative_Development_Template__c idt;
	public String IDTid;
     public CloneIDTController(ApexPages.StandardController controller) {
     
         system.debug('In Contructor!');
        IDTid = ApexPages.currentPage().getParameters().get('Id');
        
        // query all necessary fields.
        idt = [select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, 
               	SystemModstamp, LastViewedDate, LastReferencedDate, Amount_of_Investment_Year_1__c, Financial_Year__c, 
               	How_will_you_measure_success_in_Year_1__c, How_will_you_measure_success_in_Year_2__c, 
               	How_will_you_measure_success_in_Year_3__c, Initiative_Name__c, Investment_Area__c, Number_of_FTE_Allocated__c, 
               	Organisation_Name__c, Relationship_Manager__c, Status__c, What_Risks_have_been_identified__c, 
               	What_activity_will_you_do_in_Year_1__c, What_activity_will_you_do_in_Year_2__c, What_activity_will_you_do_in_Year_3__c, 
               	What_outcomes_will_you_achieve__c, Who_will_lead_this_area__c, Amount_of_Investment_Year_2__c, 
               	Amount_of_Investment_Year_3__c, Sport_NZ_Feedback__c, SME_Comments__c, SME_Approvers__c, Sign_Off_Approval_Date__c, 
               	How_will_you_measure_success_in_Year_4__c, What_activity_will_you_do_in_Year_4__c,Outcome_area__c,Outcomes__c
               from Initiative_Development_Template__c 
               where Id = :IDTid limit 1];
         
				
     }
    
    public PageReference cloneIDT()
    {
        System.debug('In method:-'+ idt);
        Initiative_Development_Template__c clonedIDT = new Initiative_Development_Template__c();
        clonedIDT.Amount_of_Investment_Year_1__c = idt.Amount_of_Investment_Year_1__c;
        clonedIDT.Amount_of_Investment_Year_2__c = idt.Amount_of_Investment_Year_2__c;
        clonedIDT.Amount_of_Investment_Year_3__c = idt.Amount_of_Investment_Year_3__c;
        clonedIDT.Financial_Year__c = idt.Financial_Year__c;
        clonedIDT.How_will_you_measure_success_in_Year_1__c = idt.How_will_you_measure_success_in_Year_1__c;
        clonedIDT.How_will_you_measure_success_in_Year_2__c = idt.How_will_you_measure_success_in_Year_2__c;
        clonedIDT.How_will_you_measure_success_in_Year_3__c = idt.How_will_you_measure_success_in_Year_3__c;
        clonedIDT.How_will_you_measure_success_in_Year_4__c = idt.How_will_you_measure_success_in_Year_4__c;
        
        clonedIDT.Investment_Area__c = idt.Investment_Area__c;
        clonedIDT.Number_of_FTE_Allocated__c = idt.Number_of_FTE_Allocated__c;
        clonedIDT.Organisation_Name__c = idt.Organisation_Name__c;
        clonedIDT.Relationship_Manager__c = idt.Relationship_Manager__c;
        clonedIDT.Initiative_Name__c = 'Copy-'+idt.Initiative_Name__c;
        clonedIDT.Sign_Off_Approval_Date__c = null;
        clonedIDT.SME_Approvers__c = null;
        clonedIDT.SME_Comments__c = null;
        clonedIDT.Sport_NZ_Feedback__c = null;
        clonedIDT.Status__c = 'Draft';
        clonedIDT.What_activity_will_you_do_in_Year_1__c = idt.What_activity_will_you_do_in_Year_1__c;
        clonedIDT.What_activity_will_you_do_in_Year_2__c = idt.What_activity_will_you_do_in_Year_2__c;
        clonedIDT.What_activity_will_you_do_in_Year_3__c = idt.What_activity_will_you_do_in_Year_3__c;
        clonedIDT.What_activity_will_you_do_in_Year_4__c = idt.What_activity_will_you_do_in_Year_4__c;
        clonedIDT.What_outcomes_will_you_achieve__c = idt.What_outcomes_will_you_achieve__c;
        clonedIDT.What_Risks_have_been_identified__c = idt.What_Risks_have_been_identified__c;
        clonedIDT.Who_will_lead_this_area__c = idt.Who_will_lead_this_area__c;
        clonedIDT.Outcome_area__c = idt.Outcome_area__c;
        clonedIDT.Outcomes__c = idt.Outcomes__c;
        
        
        insert clonedIDT;
        
       
       /* QuickAction.QuickActionRequest req = new QuickAction.QuickActionRequest();
    req.quickactionname = QuickAction.Edit;
    req.record = clonedIDT;
    QuickAction.QuickActionResult res = QuickAction.performQuickAction(req);*/
    //return clonedIDT.id;
        
        return (new PageReference('/' + clonedIDT.Id));
    }
}