force-app/main/default/objects/Programme__c/Programme__c.object-meta.xml
<CustomObject>
    <label>Programme and Event Participation</label>
    <nameField>
        <displayFormat>PEP-{00000}</displayFormat>
        <label>Programme  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programme and Event Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme__c/fields/Avg_No_of_Participants_at_Each_Session__c.field-meta.xml
<CustomField>
    <fullName>Avg_No_of_Participants_at_Each_Session__c</fullName>
    <label>Avg. No. of Participants at Each Session</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programme__c/fields/Number_of_Programmes_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Programmes_Delivered__c</fullName>
    <label>Number of Programmes Delivered</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programme__c/fields/Number_of_Sessions_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sessions_Delivered__c</fullName>
    <label>Number of Sessions Delivered</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programme__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <formula>Programme_or_Event_Name__r.Organisation__c</formula>
    <label>Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RUL_ProgramTriggerHandler.cls
public without sharing class RUL_ProgramTriggerHandler {
	public void afterInsert(list<Programme__c> lstNew){
		set <Id> setOrganizationId = new set <Id>();
		for(Programme__c objP : lstNew){
			if(!String.isBlank(objP.Organization_Id__c)){
				setOrganizationId.add(objP.Organization_Id__c);
			}
		}
		if(!setOrganizationId.isEmpty()){
			rollupDetails(setOrganizationId);
		}
	}
	
	public void afterUpdate(map<Id,Programme__c> mapNewMap, map <Id,Programme__c> mapOldMap){
		set <Id> setOrganizationId = new set <Id>();
		for(Programme__c objP : mapNewMap.values()){
			if(!String.isBlank(objP.Organization_Id__c)
			&& (objP.Organization_Id__c != 
			mapOldMap.get(objP.Id).Organization_Id__c
			|| objP.Number_of_Programmes_Delivered__c != 
			mapOldMap.get(objP.Id).Number_of_Programmes_Delivered__c
			|| objP.Number_of_Sessions_Delivered__c != 
			mapOldMap.get(objP.Id).Number_of_Sessions_Delivered__c
			|| objP.Avg_No_of_Participants_at_Each_Session__c != 
			mapOldMap.get(objP.Id).Avg_No_of_Participants_at_Each_Session__c)){
				setOrganizationId.add(objP.Organization_Id__c);
			}
		}
		if(!setOrganizationId.isEmpty()){
			rollupDetails(setOrganizationId);
		}
	}
	
	public void rollupDetails(set<Id> setOrgId){
		list <Account> lstA = [Select 
								a.No_of_Sessions_Delivered__c, 
								a.No_of_Programs_Delivered__c, 
								a.Id, 
								a.Avg_No_of_Participants_at_Each_Session__c, 
								(Select 
								Id, 
								Number_of_Programmes_Delivered__c, 
								Number_of_Sessions_Delivered__c, 
								Avg_No_of_Participants_at_Each_Session__c, 
								Organization_Id__c 
								From Programme_and_Event_Participation1__r) 
								From Account a
								where a.Id IN : setOrgId];
		
		for(Account objA : lstA){
			decimal intAvg = 0;
			decimal intSessions = 0;
			decimal intPrograms = 0;
			for(Programme__c objP : objA.Programme_and_Event_Participation1__r){
				if(objP.Avg_No_of_Participants_at_Each_Session__c != null){
					intAvg = intAvg + objP.Avg_No_of_Participants_at_Each_Session__c;
				}
				if(objP.Number_of_Programmes_Delivered__c != null){
					intPrograms = intPrograms + objP.Number_of_Programmes_Delivered__c;
				}
				if(objP.Number_of_Sessions_Delivered__c != null){
					intSessions = intSessions + objP.Number_of_Sessions_Delivered__c;
				}
			}
			objA.Avg_No_of_Participants_at_Each_Session__c = intAvg;
			objA.No_of_Sessions_Delivered__c = intSessions;
			objA.No_of_Programs_Delivered__c = intPrograms;
		}
		update lstA;
	}
}