force-app/main/default/objects/Programme__c/Programme__c.object-meta.xml
<CustomObject>
    <label>Programme and Event Participation</label>
    <nameField>
        <displayFormat>PEP-{00000}</displayFormat>
        <label>Programme  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programme and Event Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme__c/fields/Avg_No_of_Participants_at_Each_Session__c.field-meta.xml
<CustomField>
    <fullName>Avg_No_of_Participants_at_Each_Session__c</fullName>
    <label>Avg. No. of Participants at Each Session</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programme__c/fields/Number_of_Programmes_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Programmes_Delivered__c</fullName>
    <label>Number of Programmes Delivered</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programme__c/fields/Number_of_Sessions_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sessions_Delivered__c</fullName>
    <label>Number of Sessions Delivered</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programme__c/fields/Organization_Delivered_To__c.field-meta.xml
<CustomField>
    <fullName>Organization_Delivered_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization Delivered To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programme and Event Participation (Organization Delivered To)</relationshipLabel>
    <relationshipName>Programme_and_Event_Participation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RUL_ProgramTriggerHandlerTest.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of RUL_ProgramTrigger

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 18-11-2016       | Vivian Charlie   | 1. Created test class to test functionality of RUL_ProgramTrigger
   ==========================================================================================================================
*/
@isTest
private class RUL_ProgramTriggerHandlerTest {
    /*
     @ Description : Method to insert and update Programmes
    */
    public static testMethod void testInsertAndUpdateProgrammes() {     
        List<Programme__c> progList = new List<Programme__c>();
        //Creating test data
        progList = RUL_Util.createProgrammes();
        Test.StartTest();
        insert progList;
        Test.StopTest();
        Decimal sumPD=0;
        Decimal sumSD=0;
        Decimal sumAvgSess=0;
        Decimal TotalPd=0;
        Decimal TotalSd=0;
        Decimal TotalAvgSess=0;
        Set<Id> ids = new Set<Id>();
        for(Integer i=0; i<progList.size(); i++) { 
            progList[i].Number_of_Programmes_Delivered__c  = i+2;
            progList[i].Number_of_Sessions_Delivered__c = i+10;
            progList[i].Avg_No_of_Participants_at_Each_Session__c = i+10;
            sumPD = sumPD + progList[i].Number_of_Programmes_Delivered__c;
            sumSD = sumSD + progList[i].Number_of_Sessions_Delivered__c;
            sumAvgSess = sumAvgSess + progList[i].Avg_No_of_Participants_at_Each_Session__c;
            ids.add(progList[i].Organization_Delivered_To__c);
        }
        update progList;
        list<Account> parentAcc = new list<Account>();
        parentAcc = [SELECT id,
                            Avg_No_of_Participants_at_Each_Session__c,
                            No_of_Programs_Delivered__c,
                            No_of_Sessions_Delivered__c
                            FROM Account
                            WHERE id in: ids];
        for(Account accObj: parentAcc) {
            if(accObj.No_of_Programs_Delivered__c != NULL) {
                TotalPd = TotalPd + accObj.No_of_Programs_Delivered__c;
            }
            if(accObj.No_of_Sessions_Delivered__c != NULL) {
                TotalSd = TotalSd + accObj.No_of_Sessions_Delivered__c;
            }
            if(accObj.Avg_No_of_Participants_at_Each_Session__c != NULL) {
                TotalAvgSess = TotalAvgSess + accObj.Avg_No_of_Participants_at_Each_Session__c;
            }
        }                          
        //System.assertEquals(sumPD,TotalPd);
        //System.assertEquals(sumSD,TotalSd);
        //System.assertEquals(sumAvgSess,TotalAvgSess);
    }
    
    /*
     @ Description : Method to delete Programmes
    */
    public static testMethod void testDeleteProgrammes() {     
        List<Programme__c> progList = new List<Programme__c>();
        //Creating test data
        progList = RUL_Util.createProgrammes();
        Test.StartTest();
        insert progList;
        delete progList;
        Test.StopTest();        
        List<Programme__c> updatedProgList = new List<Programme__c>([SELECT id
                                                                     FROM Programme__c
                                                                     WHERE id In: progList]);
        System.assertEquals(0,updatedProgList.size());
    }
}