force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <description>To capture details of individuals (contacts not related to any accounts) for use with Marketing Cloud</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Balance_is_Better__c.field-meta.xml
<CustomField>
    <fullName>Balance_is_Better__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balance is Better</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Healthy_Active_Learning__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Active_Learning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Active Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/High_Performance_Sport_New_Zealand__c.field-meta.xml
<CustomField>
    <fullName>High_Performance_Sport_New_Zealand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Performance Sport New Zealand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Northland</fullName>
            </value>
            <value>
                <fullName>North Harbour</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Waitakere</fullName>
            </value>
            <value>
                <fullName>Counties Manakau</fullName>
                <label>Counties Manukau</label>
            </value>
            <value>
                <fullName>Waikato</fullName>
            </value>
            <value>
                <fullName>Bay of Plenty</fullName>
            </value>
            <value>
                <fullName>Gisborne</fullName>
            </value>
            <value>
                <fullName>Hawkes Bay</fullName>
            </value>
            <value>
                <fullName>Taranaki</fullName>
            </value>
            <value>
                <fullName>Whanganui</fullName>
            </value>
            <value>
                <fullName>Manawatu</fullName>
            </value>
            <value>
                <fullName>Wellington</fullName>
            </value>
            <value>
                <fullName>Tasman</fullName>
            </value>
            <value>
                <fullName>Canterbury/West Coast</fullName>
            </value>
            <value>
                <fullName>Otago</fullName>
            </value>
            <value>
                <fullName>Southland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/NZ_Coach__c.field-meta.xml
<CustomField>
    <fullName>NZ_Coach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NZ Coach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Sporting Organisation</fullName>
            </value>
            <value>
                <fullName>National Recreation Organisation</fullName>
            </value>
            <value>
                <fullName>Territorial Authority</fullName>
            </value>
            <value>
                <fullName>Regional Sports Trust</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Athlete</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Sport Leader/Administrator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Sector_Update__c.field-meta.xml
<CustomField>
    <fullName>Sector_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sector Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Used for contacts who subscribe for public publications via webform</description>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/CreateSubscriberCtrlTest.cls
/*--------------------------------------------------------------
Company:        Eternus Solutions
Description:    Test Class for CreateSubscriberCtrl controller class

History
04-10-2022      Aruna Mulik  Modified 
--------------------------------------------------------------*/
@isTest
public class CreateSubscriberCtrlTest {
    
    @isTest
    static void saveTest() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        High_Performance_Sport_New_Zealand__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        CreateSubscriberCtrl manageObj = new CreateSubscriberCtrl(sc);
        manageObj.sectorUpdateChecked();
       // manageObj.disabilityChecked();
        manageObj.kaupapaMaoriNewsChecked();
        manageObj.HighPerformanceSportNewZealandChecked();
        manageObj.saveRecord();
        manageObj.onLoad();
        manageObj.balanceisbetterChecked();
        manageObj.populateData();
        System.Test.stopTest();
        
        List<Subscriber__c> subscriberRecord = [SELECT Name FROM Subscriber__c];
    }
    
    @isTest
    static void DupTest() {
        
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        insert subscriberObj;
        
        Subscriber__c subscriberObj1 = new Subscriber__c(Balance_is_Better__c = false,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true,
                                                        First_Name__c = 'Test FN Dup',
                                                        Last_Name__c = 'Test LN Dup',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        insert subscriberObj1;
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        CreateSubscriberCtrl manageObj = new CreateSubscriberCtrl(sc);
        manageObj.email='test@test.test';
        manageObj.saveRecord();
        manageObj.editSubscriber();
        manageObj.populateData();
        manageObj.updateSubscriber();
        System.Test.stopTest();
        
    }
    
    
    
    @isTest
    static void updateTest() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        insert subscriberObj;
        
        Subscriber__c subscriberObj1 = new Subscriber__c(Balance_is_Better__c = false,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true,
                                                        First_Name__c = 'Test FN Dup',
                                                        Last_Name__c = 'Test LN Dup',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach' );
        
        insert subscriberObj1;
        
        Subscriber__c subscriberObj2 = new Subscriber__c(Balance_is_Better__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj2);
        CreateSubscriberCtrl manageObj = new CreateSubscriberCtrl(sc);
        manageObj.saveRecord();
        manageObj.editSubscriber();
        manageObj.populateData();
        manageObj.updateSubscriber();
        System.Test.stopTest();
    }
    
    @isTest
    static void saveTestNegative1() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        High_Performance_Sport_New_Zealand__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        CreateSubscriberCtrl manageObj = new CreateSubscriberCtrl(sc);
        manageObj.saveRecord();
        System.Test.stopTest();
    }
    
    @isTest
    static void saveTestNegative2() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        High_Performance_Sport_New_Zealand__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true);
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        CreateSubscriberCtrl manageObj = new CreateSubscriberCtrl(sc);
        manageObj.saveRecord();
        manageObj.closePopup();
        System.Test.stopTest();
        
    }
    
    @isTest
    static void saveTestNegative3() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        High_Performance_Sport_New_Zealand__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach',
                                                        Organisation__c = 'TEST',
                                                        Partner_Type__c	= 'Other');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        CreateSubscriberCtrl manageObj = new CreateSubscriberCtrl(sc);
        manageObj.saveRecord();
        System.Test.stopTest();
        
        List<Subscriber__c> subscriberRecord = [SELECT Name FROM Subscriber__c];
        System.assertEquals(1, subscriberRecord.size());
    }
}