force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <description>To capture details of individuals (contacts not related to any accounts) for use with Marketing Cloud</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Northland</fullName>
            </value>
            <value>
                <fullName>North Harbour</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Waitakere</fullName>
            </value>
            <value>
                <fullName>Counties Manakau</fullName>
                <label>Counties Manukau</label>
            </value>
            <value>
                <fullName>Waikato</fullName>
            </value>
            <value>
                <fullName>Bay of Plenty</fullName>
            </value>
            <value>
                <fullName>Gisborne</fullName>
            </value>
            <value>
                <fullName>Hawkes Bay</fullName>
            </value>
            <value>
                <fullName>Taranaki</fullName>
            </value>
            <value>
                <fullName>Whanganui</fullName>
            </value>
            <value>
                <fullName>Manawatu</fullName>
            </value>
            <value>
                <fullName>Wellington</fullName>
            </value>
            <value>
                <fullName>Tasman</fullName>
            </value>
            <value>
                <fullName>Canterbury/West Coast</fullName>
            </value>
            <value>
                <fullName>Otago</fullName>
            </value>
            <value>
                <fullName>Southland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Athlete</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Sport Leader/Administrator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Used for contacts who subscribe for public publications via webform</description>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/IntegritySubscriberFormCtrlTest.cls
/* Class Name        : IntegritySubscriberFormCtrlTest

* Description       : Test class for IntegritySubscriberFormCtrl class

* Author            : Infobeans - Aruna Mulik

* Created On        : 10/11/2022

* Modification Log  :

* -----------------------------------------------------------------------------------------------------

* Developer             Date               Description

* -----------------------------------------------------------------------------------------------------

* Aruna Mulik          10/11/2022         Initial version
******************************************************************************************************/
@isTest
public class IntegritySubscriberFormCtrlTest {
    @isTest
    static void saveTest() {
        Subscriber__c subscriberObj = new Subscriber__c(First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        IntegritySubscriberFormCtrl manageObj = new IntegritySubscriberFormCtrl(sc);
        manageObj.createSubscriber();
        
        
        manageObj.saveRecord();
        manageObj.closePopup();
        
        System.Test.stopTest();
        List<Subscriber__c> subscriberRecord = [SELECT Name FROM Subscriber__c];
    }
    
    @isTest
    static void updateTest() {
        Subscriber__c subscriberObj = new Subscriber__c(First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        insert subscriberObj;
        
        Subscriber__c subscriberObj2 = new Subscriber__c(First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj2);
        IntegritySubscriberFormCtrl manageObj = new IntegritySubscriberFormCtrl(sc);
        manageObj.createSubscriber();
        manageObj.editSubscriber();
        manageObj.updateSubscriber();
        System.Test.stopTest();
    }

}