force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <description>To capture details of individuals (contacts not related to any accounts) for use with Marketing Cloud</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Athlete_Life_Db__c.field-meta.xml
<CustomField>
    <fullName>Athlete_Life_Db__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Athlete Life Db</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Balance_is_Better__c.field-meta.xml
<CustomField>
    <fullName>Balance_is_Better__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balance is Better</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Click_Location__c.field-meta.xml
<CustomField>
    <fullName>Click_Location__c</fullName>
    <label>Click Location</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Disability_Sector_News__c.field-meta.xml
<CustomField>
    <fullName>Disability_Sector_News__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disability Sector News</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Do_you_identify_as_Maori__c.field-meta.xml
<CustomField>
    <fullName>Do_you_identify_as_Maori__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do you identify as Maori?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Healthy_Active_Learning__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Active_Learning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Active Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Healthy_Active_Quarterly__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Active_Quarterly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Active Quarterly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/HiddenTag__c.field-meta.xml
<CustomField>
    <fullName>HiddenTag__c</fullName>
    <label>HiddenTag</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/iseGuide__c.field-meta.xml
<CustomField>
    <fullName>iseGuide__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if subscriber has requested for eguide.</description>
    <label>iseGuide</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Kaupapa_Maori_News__c.field-meta.xml
<CustomField>
    <fullName>Kaupapa_Maori_News__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kaupapa Maori News</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Ko_wai_koe__c.field-meta.xml
<CustomField>
    <fullName>Ko_wai_koe__c</fullName>
    <label>Ko wai koe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marae</fullName>
            </value>
            <value>
                <fullName>School/Kura</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Researcher</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/NZ_Coach__c.field-meta.xml
<CustomField>
    <fullName>NZ_Coach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NZ Coach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Athlete</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Sport Leader/Administrator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Sector_Update__c.field-meta.xml
<CustomField>
    <fullName>Sector_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sector Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Signup_Type__c.field-meta.xml
<CustomField>
    <fullName>Signup_Type__c</fullName>
    <label>Signup Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Youth_sport_options__c.field-meta.xml
<CustomField>
    <fullName>Youth_sport_options__c</fullName>
    <label>Youth sport options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I am a coach</fullName>
            </value>
            <value>
                <fullName>I am a teacher</fullName>
            </value>
            <value>
                <fullName>I am the parent/guardian of a participant</fullName>
            </value>
            <value>
                <fullName>I am a youth sport administrator</fullName>
            </value>
            <value>
                <fullName>I am a volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Used for contacts who subscribe for public publications via webform</description>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/TestSubscriberTrigger.cls
@isTest
public class TestSubscriberTrigger {
   

    @isTest
    public static void testbeforeInsertFunction(){
         subscriber__c subObj=new subscriber__c();
        subObj.First_Name__c='testSubbeforeInsert';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Balance_is_Better__c=true;
        subObj.isDuplicate__c=false;
         subObj.Athlete_Life_Db__c=true;
        subObj.RecordTypeId ='0126F000001Msc2QAC';
        subObj.Sector_Update__c=true;
        subObj.NZ_Coach__c=true;
        subObj.Kaupapa_Maori_News__c=true;
        subObj.Disability_Sector_News__c=true;
        subObj.Healthy_Active_Learning__c=true;
        subObj.Healthy_Active_Quarterly__c=true;
        subObj.Do_you_identify_as_Maori__c= true;
        subObj.Ko_wai_koe__c='Other';
        subObj.Youth_sport_options__c='I am a Coach, Other';
        subObj.Role__c='Other';
         subObj.Monthly__c=true;
        SubObj.iseGuide__c=true;
        SubObj.HiddenTag__c='how much is too much';
        insert subObj;
        subscriber__c subObj1=new subscriber__c();
        
        subObj1.First_Name__c='testSub1beforeInsert';
        subObj1.Last_Name__c='testLastName1';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Balance_is_Better__c=true;
        subObj1.Monthly__c=true;
        subObj1.RecordTypeId ='0126F000001Msc2QAC';
       /* subObj1.Sector_Update__c=true;
        subobj1.NZ_Coach__c=true;
        subObj1.Kaupapa_Maori_News__c=true;
        subObj1.Disability_Sector_News__c=true;
        subObj1.Healthy_Active_Learning__c=true;
        subObj1.Healthy_Active_Quarterly__c=true; */ 
        
        test.startTest();
        insert subObj1;
       
        //update subList;
        
        //delete subObj;
        test.stopTest();
        
    }
     @isTest
    public static void testupdatedfunction(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestupdated';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Balance_is_Better__c=true;
      subObj.Monthly__c=true;
        subObj.isDuplicate__c=false;
        subObj.Youth_sport_options__c='I am a coach';
        insert subObj;
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSub2testupdated';
        subObj1.Last_Name__c='testLastName';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Email_Address__c='test@gmail1.com';
        subObj1.Balance_is_Better__c=true;
           //subObj1.RecordTypeId='Public';
        subObj1.HiddenTag__c='How Much is too much';
        subObj1.isDuplicate__c=true;
         subObj1.Monthly__c=true;
         
        insert subObj1;
        
        List<Subscriber__c> updatedlist = new List<Subscriber__c>();
        List<Subscriber__c> listtoupdate = [select id,isDuplicate__c,Email_Address__c,HiddenTag__c from Subscriber__c where First_Name__c='testSub2testupdated' ];
        for(Subscriber__c c: listtoupdate )
        {
            c.Email_Address__c = 'test@gmail.com';
            c.HiddenTag__c ='how much is too much';
            updatedlist.add(c);
            
        }
        
        test.startTest();
        update updatedlist;
        test.stopTest();
        
    }
    
      @isTest
    public static void testupdatedfunctionNoDuplicate(){
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubUNoDuplicate';
        subObj1.Last_Name__c='testLastName';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Balance_is_Better__c=false;
        subObj1.isDuplicate__c=true;
        subObj1.Youth_sport_options__c='I am a coach,I am a teacher';
         subObj1.Monthly__c=true;
        insert subObj1;
        
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubUNoDuplicate';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Email_Address__c='test1@gmail.com';
        subObj.Balance_is_Better__c=true;
        subObj.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj.isDuplicate__c=false;
         subObj.Monthly__c=true;
        insert subObj;
        
        List<Subscriber__c> lupdate=new List<Subscriber__c>();
        /*subObj1.isDuplicate__c=false;
        lupdate.add(subObj1);*/
        //subscriber__c subObj2=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSub1UNoDuplicate';
        subObj1.Email_Address__c='test1@gmail.com';
        lupdate.add(subObj1);
        
        
        test.startTest();
        update lupdate;
        test.stopTest();
        
    }

}