force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <description>To capture details of individuals (contacts not related to any accounts) for use with Marketing Cloud</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Athlete_Life_Db__c.field-meta.xml
<CustomField>
    <fullName>Athlete_Life_Db__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Athlete Life Db</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Balance_is_Better__c.field-meta.xml
<CustomField>
    <fullName>Balance_is_Better__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balance is Better</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Carded_Athlete_Db__c.field-meta.xml
<CustomField>
    <fullName>Carded_Athlete_Db__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carded Athlete Db</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Click_Location__c.field-meta.xml
<CustomField>
    <fullName>Click_Location__c</fullName>
    <label>Click Location</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Coach_Db__c.field-meta.xml
<CustomField>
    <fullName>Coach_Db__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Coach Db</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Disability_Sector_News__c.field-meta.xml
<CustomField>
    <fullName>Disability_Sector_News__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disability Sector News</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Do_you_identify_as_Maori__c.field-meta.xml
<CustomField>
    <fullName>Do_you_identify_as_Maori__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do you identify as Maori?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/General_Db__c.field-meta.xml
<CustomField>
    <fullName>General_Db__c</fullName>
    <defaultValue>false</defaultValue>
    <label>General Db</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/General_Media__c.field-meta.xml
<CustomField>
    <fullName>General_Media__c</fullName>
    <defaultValue>false</defaultValue>
    <label>General Media</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Healthy_Active_Learning__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Active_Learning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Active Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Healthy_Active_Quarterly__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Active_Quarterly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Active Quarterly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/HiddenTag__c.field-meta.xml
<CustomField>
    <fullName>HiddenTag__c</fullName>
    <label>HiddenTag</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/High_Performance_Sport_New_Zealand__c.field-meta.xml
<CustomField>
    <fullName>High_Performance_Sport_New_Zealand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Performance Sport New Zealand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/HP_Woman_Feedback__c.field-meta.xml
<CustomField>
    <fullName>HP_Woman_Feedback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP Woman Feedback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Integrity__c.field-meta.xml
<CustomField>
    <fullName>Integrity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This check box will be checked if user is filling form for Integrity subscription</description>
    <label>Integrity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/iseGuide__c.field-meta.xml
<CustomField>
    <fullName>iseGuide__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if subscriber has requested for eguide.</description>
    <label>iseGuide</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Kaupapa_Maori_News__c.field-meta.xml
<CustomField>
    <fullName>Kaupapa_Maori_News__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kaupapa Maori News</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Ko_wai_koe__c.field-meta.xml
<CustomField>
    <fullName>Ko_wai_koe__c</fullName>
    <label>Ko wai koe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marae</fullName>
            </value>
            <value>
                <fullName>School/Kura</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Researcher</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Northland</fullName>
            </value>
            <value>
                <fullName>North Harbour</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Waitakere</fullName>
            </value>
            <value>
                <fullName>Counties Manakau</fullName>
                <label>Counties Manukau</label>
            </value>
            <value>
                <fullName>Waikato</fullName>
            </value>
            <value>
                <fullName>Bay of Plenty</fullName>
            </value>
            <value>
                <fullName>Gisborne</fullName>
            </value>
            <value>
                <fullName>Hawkes Bay</fullName>
            </value>
            <value>
                <fullName>Taranaki</fullName>
            </value>
            <value>
                <fullName>Whanganui</fullName>
            </value>
            <value>
                <fullName>Manawatu</fullName>
            </value>
            <value>
                <fullName>Wellington</fullName>
            </value>
            <value>
                <fullName>Tasman</fullName>
            </value>
            <value>
                <fullName>Canterbury/West Coast</fullName>
            </value>
            <value>
                <fullName>Otago</fullName>
            </value>
            <value>
                <fullName>Southland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/NSO_Marcomms_Db__c.field-meta.xml
<CustomField>
    <fullName>NSO_Marcomms_Db__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NSO Marcomms Db</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/NZ_Coach__c.field-meta.xml
<CustomField>
    <fullName>NZ_Coach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NZ Coach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Sporting Organisation</fullName>
            </value>
            <value>
                <fullName>National Recreation Organisation</fullName>
            </value>
            <value>
                <fullName>Territorial Authority</fullName>
            </value>
            <value>
                <fullName>Regional Sports Trust</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Athlete</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Sport Leader/Administrator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Sector_Update__c.field-meta.xml
<CustomField>
    <fullName>Sector_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sector Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Signup_Type__c.field-meta.xml
<CustomField>
    <fullName>Signup_Type__c</fullName>
    <label>Signup Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Subscribed__c.field-meta.xml
<CustomField>
    <fullName>Subscribed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Woman_in_Sport_Db__c.field-meta.xml
<CustomField>
    <fullName>Woman_in_Sport_Db__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Woman in Sport Db</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Youth_sport_options__c.field-meta.xml
<CustomField>
    <fullName>Youth_sport_options__c</fullName>
    <label>Youth sport options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I am a coach</fullName>
            </value>
            <value>
                <fullName>I am a teacher</fullName>
            </value>
            <value>
                <fullName>I am the parent/guardian of a participant</fullName>
            </value>
            <value>
                <fullName>I am a youth sport administrator</fullName>
            </value>
            <value>
                <fullName>I am a volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Used for contacts who subscribe for public publications via webform</description>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/HelperClassSubscriberTagsUpdateTest.cls
@isTest
public class HelperClassSubscriberTagsUpdateTest {
    @isTest
    public static void testbeforeInsertFunction(){
         subscriber__c subObj=new subscriber__c();
        subObj.First_Name__c='testSubbeforeInsert';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Balance_is_Better__c=true;
        subObj.isDuplicate__c=false;
         subObj.Athlete_Life_Db__c=true;
        subObj.RecordTypeId ='0126F000001Msc2QAC';
        subObj.Sector_Update__c=true;
        subObj.NZ_Coach__c=true;
        subObj.Kaupapa_Maori_News__c=true;
        subObj.Disability_Sector_News__c=true;
        subObj.Healthy_Active_Learning__c=true;
        subObj.Healthy_Active_Quarterly__c=true;
        subObj.Do_you_identify_as_Maori__c= true;
        subObj.Ko_wai_koe__c='Other';
        subObj.Youth_sport_options__c='I am a Coach, Other';
        subObj.Role__c='Other';
         subObj.Monthly__c=true;
        SubObj.iseGuide__c=true;
        SubObj.HiddenTag__c='how much is too much';
        insert subObj;
        subscriber__c subObj1=new subscriber__c();
        
        subObj1.First_Name__c='testSub1beforeInsert';
        subObj1.Last_Name__c='testLastName1';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Balance_is_Better__c=true;
        subObj1.Monthly__c=true;
        subObj1.RecordTypeId ='0126F000001Msc2QAC';
       /* subObj1.Sector_Update__c=true;
        subobj1.NZ_Coach__c=true;
        subObj1.Kaupapa_Maori_News__c=true;
        subObj1.Disability_Sector_News__c=true;
        subObj1.Healthy_Active_Learning__c=true;
        subObj1.Healthy_Active_Quarterly__c=true; */ 
        
        test.startTest();
        insert subObj1;
       
        //update subList;
        
        //delete subObj;
        test.stopTest();
        
    }
    @isTest
    public static void testbeforeInsertFunctionNoDuplicate(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubINoDuplicate';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Youth_sport_options__c= 'I am a coach';
       // subObj.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj.Email_Address__c='test1@gmail.com';
        subObj.Balance_is_Better__c=true;
        subObj.isDuplicate__c=false;
         subObj.RecordTypeId ='0126F000001Msc2QAC';
        subObj.Organisation__c='test';
        //subObj.RecordTypeId.Name='Public';
        insert subObj;
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSub1INoDuplicate';
        subObj1.Last_Name__c='testLastName1';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj1.Email_Address__c='test2@gmail.com';
        subObj1.isDuplicate__c=true;
         subObj.RecordTypeId ='0126F000001Msc2QAC';
          subObj.Organisation__c='test';
         subObj.Monthly__c=true;
        
        test.startTest();
        insert subObj1;
        test.stopTest();
        
    }
    
    @isTest
    public static void testupdatedfunction(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestupdated';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Balance_is_Better__c=true;
      subObj.Monthly__c=true;
        subObj.isDuplicate__c=false;
        subObj.Youth_sport_options__c='I am a coach';
        insert subObj;
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSub2testupdated';
        subObj1.Last_Name__c='testLastName';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Email_Address__c='test@gmail1.com';
        subObj1.Balance_is_Better__c=true;
           //subObj1.RecordTypeId='Public';
        subObj1.HiddenTag__c='How Much is too much';
        subObj1.isDuplicate__c=true;
         subObj1.Monthly__c=true;
         
        insert subObj1;
        
        List<Subscriber__c> updatedlist = new List<Subscriber__c>();
        List<Subscriber__c> listtoupdate = [select id,isDuplicate__c,Email_Address__c,HiddenTag__c from Subscriber__c where First_Name__c='testSub2testupdated' ];
        for(Subscriber__c c: listtoupdate )
        {
            c.Email_Address__c = 'test@gmail.com';
            c.HiddenTag__c ='how much is too much';
            updatedlist.add(c);
            
        }
        
        test.startTest();
        update updatedlist;
        test.stopTest();
        
    }
    
      @isTest
    public static void testupdatedfunctionNoDuplicate(){
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubUNoDuplicate';
        subObj1.Last_Name__c='testLastName';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Balance_is_Better__c=false;
        subObj1.isDuplicate__c=true;
        subObj1.Youth_sport_options__c='I am a coach,I am a teacher';
         subObj1.Monthly__c=true;
        insert subObj1;
        
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubUNoDuplicate';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Email_Address__c='test1@gmail.com';
        subObj.Balance_is_Better__c=true;
        subObj.Youth_sport_options__c='I am a coach,I am a teacher';
        subObj.isDuplicate__c=false;
         subObj.Monthly__c=true;
        insert subObj;
        
        List<Subscriber__c> lupdate=new List<Subscriber__c>();
        /*subObj1.isDuplicate__c=false;
        lupdate.add(subObj1);*/
        //subscriber__c subObj2=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSub1UNoDuplicate';
        subObj1.Email_Address__c='test1@gmail.com';
        lupdate.add(subObj1);
        
        
        test.startTest();
        update lupdate;
        test.stopTest();
        
    }
      @isTest
    public static void testBibFalsefunction(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestBibFalse';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Balance_is_Better__c=true;
        subObj.Sector_Update__c=false;
        subObj.NZ_Coach__c=false;
        subObj.Location__c='Wellington';
        subobj.Role__c='Coach';
        subObj.Organisation__c='testorg';
        subObj.High_Performance_Sport_New_Zealand__c=true;
        subObj.Partner_Type__c='Other';
        subObj.RecordTypeId ='0126F000001Msc2QAC';
        subObj.Youth_sport_options__c='I am a coach,I am a teacher';
        insert subObj;
        
      subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubtestBibFalse';
        subObj1.Last_Name__c='testLastName';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Balance_is_Better__c=true;
        subObj1.Location__c='Wellington';
        subobj1.Role__c='Coach';
        subObj1.Organisation__c='testorg';
        subObj1.Partner_Type__c='Other';
        subObj1.RecordTypeId ='0126F000001Msc2QAC';
        subObj1.Youth_sport_options__c='I am a coach,I am a teacher';
        
        insert subObj1;
        test.startTest();
        subObj1.Sector_Update__c=true;
        subObj1.NZ_Coach__c=true;
        update subObj1;
        test.stopTest();
        
    }
    @isTest
    public static void testhpsnzRecordtype(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestBibFalse';
        subObj.Last_Name__c='testLastName';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Location__c='Wellington';
        subobj.Role__c='Coach';
        subObj.Organisation__c='testorg';
        subObj.RecordTypeId ='0126F0000022f3oQAA';
        subObj.General_Db__c=true;
        subObj.NSO_Marcomms_Db__c=true;
        subObj.Athlete_Life_Db__c=true;
        subObj.Coach_Db__c=true;
        subobj.High_Performance_Sport_New_Zealand__c=true;
        subobj.Carded_Athlete_Db__c=true;
       // subObj.NSO_Marcomms_Db__c=false;
        subObj.Woman_in_Sport_Db__c=true;
        subObj.HP_Woman_Feedback__c=true;
        subObj.Subscribed__c=true;
        subObj.Tags__c='testtag';
         insert subObj;
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubtestBibFalse';
        subObj1.Last_Name__c='testLastName';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Location__c='Wellington';
        subobj1.Role__c='Coach';
        subObj1.Organisation__c='testorg';
        subObj1.RecordTypeId ='0126F0000022f3oQAA';
        subObj1.General_Db__c=true;
        subObj1.Athlete_Life_Db__c=true;
        subObj1.Subscribed__c=true;
        subObj1.Carded_Athlete_Db__c=true;
        subObj1.Woman_in_Sport_Db__c=true;
        subObj1.Coach_Db__c=true;
        subobj1.High_Performance_Sport_New_Zealand__c=false;
        subobj1.Carded_Athlete_Db__c=true;
        subObj1.NSO_Marcomms_Db__c=true;
        subObj1.Woman_in_Sport_Db__c=true;
        subobj1.HP_Woman_Feedback__c=true;
        
         
        test.startTest();
        insert subObj1;
        test.stopTest();
        
    }
    
    @isTest
    public static void testmediaRecordtype(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestBibFalse';
        subObj.Last_Name__c='testLastName';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Location__c='Wellington';
        subObj.RecordTypeId ='0126F000001Msc1QAC';
        subObj.General_Media__c=true;
        subObj.Subscribed__c=true;
        subObj.Organisation__c='test';
        insert subObj;
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubtestBibFalse';
        subObj1.Last_Name__c='testLastName';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Organisation__c='test';
        subObj1.RecordTypeId ='0126F000001Msc1QAC';
                
        test.startTest();
        insert subObj1;
        test.stopTest();
                       
    }
    
     @isTest
    public static void testintegrityRecordType(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestBibFalse';
        subObj.Last_Name__c='testLastName';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Location__c='Wellington';
        subobj.Role__c='Coach';
        subObj.Organisation__c='testorg';
        subObj.RecordTypeId ='0126F000001ZwPnQAK';
         subObj.Integrity__c=true; 
         subobj.Tags__c='testtag';
         insert subObj;
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubtestBibFalse';
        subObj1.Last_Name__c='testLastName';
        subObj1.Email_Address__c='test@gmail.com';
      
        subObj1.RecordTypeId ='0126F000001ZwPnQAK';
       
        test.startTest();
        insert subObj1;
        test.stopTest();
        
    }
    
     @isTest
    public static void testPublicRecordType(){
        subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestBibFalse';
        subObj.Last_Name__c='testLastName';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Location__c='Wellington';
        subobj.Role__c='Coach';
        subObj.Organisation__c='testorg';
        subObj.RecordTypeId ='0126F000001Msc2QAC';
         subObj.Integrity__c=true; 
         subObj.Tags__c='testtag';
        
         insert subObj;
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubtestBibFalse';
        subObj1.Last_Name__c='testLastName';
        subObj1.Email_Address__c='test@gmail.com';
        
      
        subObj1.RecordTypeId ='0126F000001Msc2QAC';
       
        test.startTest();
        insert subObj1;
        test.stopTest();
        
    }
    
      @isTest
    public static void testnotPublicEmailSet(){
        subscriber__c subObj=new subscriber__c();
        subObj.Balance_is_Better__c=true;
        subObj.First_Name__c='testSubtestBibFalse';
        subObj.Last_Name__c='testLastName';
        subObj.Email_Address__c='test@gmail.com';
        SubObj.iseGuide__c=true;
        SubObj.HiddenTag__c='how much is too much';
        // subobj.Tags__c='testtag';
        subObj.RecordTypeId ='0126F0000022f3oQAA';
        insert subObj;
        
         subObj.Last_Name__c='testLastName1';
        update subObj;
        
         subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSubtestBibFalse';
        subObj1.Last_Name__c='testLastName';
        subObj1.Email_Address__c='test@gmail.com';
        subObj1.Balance_is_Better__c=false;
      
        subObj1.RecordTypeId ='0126F000001Msc2QAC';
       
          test.startTest();
        insert subObj1;
        test.stopTest();
        
        
        
    }
    
     @isTest
    public static void UpdatedFunctionTest(){
         subscriber__c subObj=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj.First_Name__c='testSubtestupdated';
        subObj.Last_Name__c='testLastName';
        subObj.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj.Signup_Type__c='Email';
        subObj.Tags__c='Test Tag';
        SubObj.HiddenTag__c='how much is too much';
        subObj.Email_Address__c='test@gmail.com';
        subObj.Balance_is_Better__c=true;
      subObj.Monthly__c=true;
        subObj.isDuplicate__c=false;
        subObj.Youth_sport_options__c='I am a coach';
        insert subObj;
        
        subscriber__c subObj1=new subscriber__c();
        //Email_Address__c,First_Name__c,Last_Name__c,Click_Location__c,Signup_Type__c,Tags__c
        subObj1.First_Name__c='testSub2testupdated';
        subObj1.Last_Name__c='testLastName';
        subObj1.Click_Location__c='Sign Up Free - Desktop Nav';
        subObj1.Signup_Type__c='Email';
        subObj1.Tags__c='Test Tag';
        SubObj.HiddenTag__c='how much is too much';
        subObj1.Email_Address__c='test@gmail1.com';
        subObj1.Balance_is_Better__c=true;
           //subObj1.RecordTypeId='Public';
        subObj1.HiddenTag__c='How Much is too much';
        subObj1.isDuplicate__c=true;
         subObj1.Monthly__c=true;
        insert subObj1;
        
        List<Subscriber__c> updatedlist = new List<Subscriber__c>();
        List<Subscriber__c> listtoupdate = [select id,isDuplicate__c,Email_Address__c,HiddenTag__c from Subscriber__c where First_Name__c='testSub2testupdated' ];
        for(Subscriber__c c: listtoupdate )
        {
            c.Email_Address__c = 'test@gmail.com';
            c.HiddenTag__c ='how much is too much';
            updatedlist.add(c);
            
        }
        
        test.startTest();
        update updatedlist;
        test.stopTest();
    }
}