force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <description>To capture details of individuals (contacts not related to any accounts) for use with Marketing Cloud</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Balance_is_Better__c.field-meta.xml
<CustomField>
    <fullName>Balance_is_Better__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balance is Better</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Healthy_Active_Learning__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Active_Learning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Active Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Northland</fullName>
            </value>
            <value>
                <fullName>North Harbour</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Waitakere</fullName>
            </value>
            <value>
                <fullName>Counties Manakau</fullName>
                <label>Counties Manukau</label>
            </value>
            <value>
                <fullName>Waikato</fullName>
            </value>
            <value>
                <fullName>Bay of Plenty</fullName>
            </value>
            <value>
                <fullName>Gisborne</fullName>
            </value>
            <value>
                <fullName>Hawkes Bay</fullName>
            </value>
            <value>
                <fullName>Taranaki</fullName>
            </value>
            <value>
                <fullName>Whanganui</fullName>
            </value>
            <value>
                <fullName>Manawatu</fullName>
            </value>
            <value>
                <fullName>Wellington</fullName>
            </value>
            <value>
                <fullName>Tasman</fullName>
            </value>
            <value>
                <fullName>Canterbury/West Coast</fullName>
            </value>
            <value>
                <fullName>Otago</fullName>
            </value>
            <value>
                <fullName>Southland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Monthly__c.field-meta.xml
<CustomField>
    <fullName>Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/NZ_Coach__c.field-meta.xml
<CustomField>
    <fullName>NZ_Coach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NZ Coach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Athlete</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Sport Leader/Administrator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Sector_Update__c.field-meta.xml
<CustomField>
    <fullName>Sector_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sector Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Weekly__c.field-meta.xml
<CustomField>
    <fullName>Weekly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Weekly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Used for contacts who subscribe for public publications via webform</description>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/BIBedmPreferenceCtrlTest.cls
@isTest
public class BIBedmPreferenceCtrlTest {
    @isTest
    static void makeUnsubscribeTest() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        Weekly__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Monthly__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        BIBedmPreferenceCtrl manageObj = new BIBedmPreferenceCtrl(sc);    
        manageObj.unsubscribe= true;
        manageObj.makeUnsubscribe();
        System.Test.stopTest();
        
        List<Subscriber__c> subscriberRecord = [SELECT Name,Weekly__c, Monthly__c FROM Subscriber__c];
    }
    
    
    @isTest
    static void balanceisbetterCheckedTest() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = false,
                                                        Weekly__c = false,
                                                        Healthy_Active_Learning__c = true,
                                                        Monthly__c = false,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        BIBedmPreferenceCtrl manageObj = new BIBedmPreferenceCtrl(sc);
        
        manageObj.unsubscribe= false;
        manageObj.makeUnsubscribe();
        manageObj.balanceisbetterChecked();
        
        System.Test.stopTest();
        
        List<Subscriber__c> subscriberRecord = [SELECT Name,Weekly__c, Monthly__c FROM Subscriber__c];
    }
    
    @isTest
    static void populateDataTest() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        Weekly__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Monthly__c = true,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        BIBedmPreferenceCtrl manageObj = new BIBedmPreferenceCtrl(sc);
        
        
        manageObj.makeUnsubscribe();
        manageObj.balanceisbetterChecked();
        manageObj.populateData();
        manageObj.closePopup();
        
        System.Test.stopTest();
        
        List<Subscriber__c> subscriberRecord = [SELECT Name,Weekly__c, Monthly__c FROM Subscriber__c];
    }
    @isTest
    static void updateSubscriberTest() {
        Id RecordTypeIdSu = Schema.SObjectType.Subscriber__c.getRecordTypeInfosByName().get('Public').getRecordTypeId();
        
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        NZ_Coach__c = true,
                                                        Weekly__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Monthly__c = true,
                                                        RecordTypeId= RecordTypeIdSu,
                                                        First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach');
        
        insert subscriberObj;
        
        Subscriber__c subscriberObj1 = new Subscriber__c(Balance_is_Better__c = false,
                                                         Weekly__c = false,
                                                         Healthy_Active_Learning__c = true,
                                                         Monthly__c = false,
                                                         Sector_Update__c = true,
                                                         First_Name__c = 'Test FN Dup',
                                                         Last_Name__c = 'Test LN Dup',
                                                         Email_Address__c = 'test@test.test',
                                                         Location__c = 'Tasman',
                                                         RecordTypeId= RecordTypeIdSu,
                                                         Role__c = 'Coach');
        
        insert subscriberObj1;
        
        Subscriber__c sublst=[Select Id from Subscriber__c where Email_Address__c='test@test.test' limit 1];
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        BIBedmPreferenceCtrl manageObj = new BIBedmPreferenceCtrl(sc);
        
        manageObj.unsubscribe= true;
        manageObj.subid=sublst.Id;       
        manageObj.querySubscriberRecord();
        manageObj.saveRecord();
        manageObj.onLoad();
        manageObj.updateSubscriber();
        manageObj.onLoad();
        manageObj.populateData();
        System.Test.stopTest();
        
    }
}