force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <description>To capture details of individuals (contacts not related to any accounts) for use with Marketing Cloud</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Balance_is_Better__c.field-meta.xml
<CustomField>
    <fullName>Balance_is_Better__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balance is Better</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Healthy_Active_Learning__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Active_Learning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Active Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/High_Performance_Sport_New_Zealand__c.field-meta.xml
<CustomField>
    <fullName>High_Performance_Sport_New_Zealand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Performance Sport New Zealand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Integrity__c.field-meta.xml
<CustomField>
    <fullName>Integrity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This check box will be checked if user is filling form for Integrity subscription</description>
    <label>Integrity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Northland</fullName>
            </value>
            <value>
                <fullName>North Harbour</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Waitakere</fullName>
            </value>
            <value>
                <fullName>Counties Manakau</fullName>
                <label>Counties Manukau</label>
            </value>
            <value>
                <fullName>Waikato</fullName>
            </value>
            <value>
                <fullName>Bay of Plenty</fullName>
            </value>
            <value>
                <fullName>Gisborne</fullName>
            </value>
            <value>
                <fullName>Hawkes Bay</fullName>
            </value>
            <value>
                <fullName>Taranaki</fullName>
            </value>
            <value>
                <fullName>Whanganui</fullName>
            </value>
            <value>
                <fullName>Manawatu</fullName>
            </value>
            <value>
                <fullName>Wellington</fullName>
            </value>
            <value>
                <fullName>Tasman</fullName>
            </value>
            <value>
                <fullName>Canterbury/West Coast</fullName>
            </value>
            <value>
                <fullName>Otago</fullName>
            </value>
            <value>
                <fullName>Southland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/NZ_Coach__c.field-meta.xml
<CustomField>
    <fullName>NZ_Coach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NZ Coach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Athlete</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Sport Leader/Administrator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rangatahi</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Sector_Update__c.field-meta.xml
<CustomField>
    <fullName>Sector_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sector Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/recordTypes/Integrity.recordType-meta.xml
<RecordType>
    <fullName>Integrity</fullName>
    <active>true</active>
    <description>This record type will have records registered for Integrity list</description>
    <label>Integrity</label>
</RecordType>

force-app/main/default/objects/Subscriber__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Used for contacts who subscribe for public publications via webform</description>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/IntegrityUnubscriberFormCtrlTest.cls
/* Class Name        : IntegrityUnubscriberFormCtrlTest
* Description       : Test class for IntegrityUnubscriberFormCtrl
* Author            : Infobeans - Aruna Mulik
* Created On        : 11/11/2022
* Modification Log  :
* -----------------------------------------------------------------------------------------------------

* Developer             Date              Description

* -----------------------------------------------------------------------------------------------------

* Aruna Mulik          11/11/2022        Initial version
******************************************************************************************************/
@isTest
public class IntegrityUnubscriberFormCtrlTest {

 @isTest
    static void saveTest() {
        Id recordTypeId = Schema.SObjectType.Subscriber__c.getRecordTypeInfosByDeveloperName()
                      .get('Integrity').getRecordTypeId();
        Subscriber__c subscriberObj = new Subscriber__c(First_Name__c = 'Test FN',
                                                        Last_Name__c = 'Test LN',
                                                        Email_Address__c = 'test@test.test',
                                                        Location__c = 'Tasman',
                                                        Role__c = 'Coach',
                                                       Organisation__c='test',
                                                       Integrity__c=true,
                                                       RecordtypeId= recordTypeId);
        insert subscriberObj;
        Subscriber__c sublst=[Select Id from Subscriber__c where Email_Address__c='test@test.test' limit 1];
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        IntegrityUnsubscriberFormCtrl manageObj = new IntegrityUnsubscriberFormCtrl(sc);
       
         manageObj.subid=sublst.Id;
        manageObj.editSubscriber();
        manageObj.updateSubscriber();
        System.Test.stopTest();
  }
    
     @isTest
    static void saveTestNegative2() {
        Subscriber__c subscriberObj = new Subscriber__c(Balance_is_Better__c = true,
                                                        High_Performance_Sport_New_Zealand__c = true,
                                                        NZ_Coach__c = true,
                                                        Healthy_Active_Learning__c = true,
                                                        Sector_Update__c = true);
        
        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(subscriberObj);
        IntegrityUnsubscriberFormCtrl manageObj = new IntegrityUnsubscriberFormCtrl(sc);
        manageObj.saveRecord();
        manageObj.closePopup();
        System.Test.stopTest();
        
    
}
}