force-app/main/default/objects/Membership_Numbers__c/Membership_Numbers__c.object-meta.xml
<CustomObject>
    <label>Membership Numbers</label>
    <nameField>
        <displayFormat>MNN-{00000}</displayFormat>
        <label>Membership Numbers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership_Numbers__c/fields/Membership_Numbers_Category__c.field-meta.xml
<CustomField>
    <fullName>Membership_Numbers_Category__c</fullName>
    <label>Membership Numbers Category</label>
    <referenceTo>Membership_Numbers_Category__c</referenceTo>
    <relationshipLabel>Membership Numbers</relationshipLabel>
    <relationshipName>Membership_Numbers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership_Numbers__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Membership Numbers</relationshipLabel>
    <relationshipName>Membership_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership_Numbers_Category__c/Membership_Numbers_Category__c.object-meta.xml
<CustomObject>
    <label>Membership Numbers Category</label>
    <nameField>
        <label>Membership Numbers Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Numbers Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Membership_NumbersControllerTest.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of Membership_Numbers Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 18-11-2016       | Vivian Charlie   | 1. Created test class to test functionality of Membership_Numbers Page
   ==========================================================================================================================
*/
@isTest
private class Membership_NumbersControllerTest {
    /*
     @ Description : Method to insert Membership Numbers
    */
    public static testMethod void testSaveMemNoCat() {
        List<Membership_Numbers_Category__c> memNiCatList = new List<Membership_Numbers_Category__c>();
        //Creating test data
        memNiCatList = RUL_Util.createMemNosCat();
        insert memNiCatList;
        List<Account> accList = new List<Account>();
        accList = RUL_Util.createAccounts();
        insert accList;
        Test.setCurrentPageReference(new PageReference('Page.Membership_Numbers')); 
        apexpages.currentpage().getparameters().put('id', memNiCatList[0].id);
                            
        Membership_NumbersController controller = new Membership_NumbersController();
        controller.newMemberNo.Organisation__c = accList[0].id;
        PageReference pageRef = controller.save();
        System.assertEquals(pageRef.getUrl(),'/' + controller.newMemberNo.Id);
        //System.assertEquals(1, [select count() from Membership_Numbers__c WHERE Membership_Numbers_Category__c =: memNiCatList[0].id]);       
    }
    
    /*
     @ Description : Method to cancel Membership Numbers
    */
    public static testMethod void testCancelMemNoCat() {
        List<Membership_Numbers_Category__c> memNiCatList = new List<Membership_Numbers_Category__c>();
        //Creating test data
        memNiCatList = RUL_Util.createMemNosCat();
        insert memNiCatList;
        List<Account> accList = new List<Account>();
        accList = RUL_Util.createAccounts();
        insert accList;
        Test.setCurrentPageReference(new PageReference('Page.Membership_Numbers')); 
        apexpages.currentpage().getparameters().put('id', memNiCatList[0].id);
                            
        Membership_NumbersController controller = new Membership_NumbersController();
        controller.newMemberNo.Organisation__c = accList[0].id;
        PageReference pageRef = controller.Cancel();
        System.assertEquals(pageRef.getUrl(),'/' + controller.newMemberNo.Membership_Numbers_Category__c);       
    }
}