force-app/main/default/objects/Membership_Numbers__c/Membership_Numbers__c.object-meta.xml
<CustomObject>
    <label>Membership Numbers</label>
    <nameField>
        <displayFormat>MNN-{00000}</displayFormat>
        <label>Membership Numbers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership_Numbers__c/fields/Membership_Numbers_Category__c.field-meta.xml
<CustomField>
    <fullName>Membership_Numbers_Category__c</fullName>
    <label>Membership Numbers Category</label>
    <referenceTo>Membership_Numbers_Category__c</referenceTo>
    <relationshipLabel>Membership Numbers</relationshipLabel>
    <relationshipName>Membership_Numbers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership_Numbers_Category__c/Membership_Numbers_Category__c.object-meta.xml
<CustomObject>
    <label>Membership Numbers Category</label>
    <nameField>
        <label>Membership Numbers Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Numbers Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Membership_NumbersController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to implement functionality of Membership_Numbers Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 30-11-2016       | Vivian Charlie   | 1. Created class to implement functionality of Membership_Numbers Page
   ==========================================================================================================================
*/
public class Membership_NumbersController{
    public Membership_Numbers__c newMemberNo {get;set;}
    
    public Membership_NumbersController(){
        Id parentId = ApexPages.currentPage().getParameters().get('id');
        system.debug('parentId'+parentId);
        newMemberNo  = new Membership_Numbers__c();
        newMemberNo.Membership_Numbers_Category__c = parentId;
    }
    
    public PageReference save()
    {      
        try {
            upsert newMemberNo ;
        } catch(exception e) {
            ApexPages.addMessages(e);          
        }
        return new PageReference('/' + newMemberNo.id);
    }
    
    public Pagereference cancel(){
        PageReference newpage = new Pagereference('/' + newMemberNo.Membership_Numbers_Category__c);
        newpage.setRedirect(true);
        return newpage;
    }
}