force-app/main/default/objects/Funding_Allocation__c/Funding_Allocation__c.object-meta.xml
<CustomObject>
    <label>Funding to Strategic Area</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Allocations to Strategic Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Allocation__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipName>Funding_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <formula>Investment_Area__r.Strategic_Area__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Strategic Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Investment_Area_Owner__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investment_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Investment_Area_Allocation__c/Investment_Area_Allocation__c.object-meta.xml
<CustomObject>
    <label>Investment Area Allocation</label>
    <nameField>
        <displayFormat>IAA-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Area Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area_Allocation__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Investment Area Allocations</relationshipLabel>
    <relationshipName>Investment_Area_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Investment_Area_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Update the Status when you receive results against this Measure.  This will generally be when you record the Result and Result Date.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
                <default>true</default>
                <label>Removed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Partially Met</fullName>
            </value>
            <value>
                <fullName>Not Met</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Partner_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Non-compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sport NZ</fullName>
            </value>
            <value>
                <fullName>High Performance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestMeasureTriggerhandler.cls
@isTest
private class TestMeasureTriggerhandler {
    @testSetup
    private static void setup() {
        updateInvestmentAreaTriggerHandler.isExecuted = false;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User usr = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='rajput', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='Testuser@davanti.com');
        
        Account testAccount = new Account( Name = 'Test Account' );
        insert testAccount;
        
        Plan__c plan = new Plan__c(Partner__c=testAccount.Id,Status__c='Draft',Start_Date__c=system.today(),End_Date__c = system.today().addDays(20));
        insert plan;
        
        Strategic_Area__c sArea = new Strategic_Area__c();
        
        sArea.Name = 'Wellington';
        sArea.Entity__c = 'Sportz Anz';
        sArea.Status__c = 'Draft';
        sArea.Start_Date__c = system.Today();
        sArea.End_Date__c = system.Today().addDays(2);
        
        insert sArea;
        
        Investment_Area__c iArea = new Investment_Area__c();
        iArea.Name = 'Davanti';
        iArea.Strategic_Area__c = sArea.Id;
        iArea.Status__c = 'Active';
        iArea.Start_Date__c = system.Today();
        iArea.End_Date__c = system.Today().addDays(2);
        iArea.Investment_Area_Owner__c = usr.Id;
        
        insert iArea;
        
        Funding_Allocation__c fAllocation = new Funding_Allocation__c();
        fAllocation.Financial_Year__c = '2014/15';
        fAllocation.Funding_Allocation_End_Date__c = system.Today().addDays(90);
        fAllocation.Funding_Allocation_Start_Date__c = system.Today();
        fAllocation.Funding_Amount__c = 500;
        fAllocation.Strategic_Area__c = sArea.Id;
        
        insert fAllocation;
        
        Investment_Area_Allocation__c invAreaAllocation = new Investment_Area_Allocation__c();
        invAreaAllocation.Amount__c = 400;
        invAreaAllocation.Investment_Area__c = iArea.Id;
        invAreaAllocation.Funding_Allocation__c = fAllocation.Id;
        invAreaAllocation.Status__c = 'Draft';
        
        insert invAreaAllocation;
        
        Skip_Trigger__c isSkipTrigger = new Skip_Trigger__c();
        isSkipTrigger.Name = 'skipped';
        isSkipTrigger.is_Skipped__c = false;
        
        insert isSkipTrigger;
        
        List<Initiative__c> lstOfInitiative = new List<Initiative__c>();
        
        Initiative__c init1 = new Initiative__c(
            Name = 'Test Init1',
            Investment_Area__c = iArea.Id,
            Plan__c = plan.Id,
            Pending_Measures__c = 0,
            Initiative_Owner__c = usr.Id);
        
        Initiative__c init2 = new Initiative__c(
            Name = 'Test Init2',
            Investment_Area__c = iArea.Id,
            Plan__c = plan.Id,
            Pending_Measures__c = 0,
            Initiative_Owner__c = usr.Id);
        
        lstOfInitiative.add(init1);
        lstOfInitiative.add(init2);
        
        insert lstOfInitiative;
        
        List<Measure__c> lstOfMeasure = new List<Measure__c>();
        
        for(Integer i = 0; i < 10; i++) {
            lstOfMeasure.add(
                new Measure__c(
                    Name = 'Test Measure' + i,
                    Initiative__c = init1.Id,
                    Partner__c = testAccount.Id,
                    Status__c = 'Pending')
            );
        }
        
        insert lstOfMeasure;
    }
    
    //Test insert
    @isTest
    private static void testInsert() {
        Test.startTest();
        
        List<Initiative__c> lstOfInitiative = [SELECT Id, Pending_Measures__c FROM Initiative__c];
        
        //System.assertEquals(10, lstOfInitiative[0].Pending_Measures__c);
        //System.assertEquals(0, lstOfInitiative[1].Pending_Measures__c);
        
        Test.stopTest();
    }
    
    //Test delete & undelete
    @isTest
    private static void testDelete() {
        Test.startTest();
        
        //Test delete
        List<Measure__c> lstOfMeasure = [SELECT Id FROM Measure__c WHERE Status__c = 'Pending'];
        
        delete lstOfMeasure;
        
        List<Initiative__c> lstOfInitiative = [SELECT Id, Pending_Measures__c FROM Initiative__c];
        system.debug('Testing Init ------------------'+lstOfInitiative);
        //System.assertEquals(10, lstOfInitiative[0].Pending_Measures__c);
        //System.assertEquals(0, lstOfInitiative[1].Pending_Measures__c);
        
        //Test undelete
        undelete lstOfMeasure;
        
        lstOfInitiative = [SELECT Id, Pending_Measures__c FROM Initiative__c];
        
        //System.assertEquals(10, lstOfInitiative[0].Pending_Measures__c);
        //System.assertEquals(0, lstOfInitiative[1].Pending_Measures__c);
        
        Test.stopTest();
    }
    
    //Test update - only Initiative__c changes
    @isTest
    private static void testUpdate1() {
        Test.startTest();
        
        List<Measure__c> lstOfMeasure = [SELECT Id, Initiative__c FROM Measure__c];
        List<Initiative__c> lstOfInitiative = [SELECT Id FROM Initiative__c];
        
        for(Integer i = 0; i < 10; i++) {
            lstOfMeasure[i].Initiative__c = (i < 5) ? null : lstOfInitiative[1].Id;
        }
        
        update lstOfMeasure;
        
        lstOfInitiative = [SELECT Id, Pending_Measures__c FROM Initiative__c];
        
        //System.assertEquals(10, lstOfInitiative[0].Pending_Measures__c);
        //System.assertEquals(5, lstOfInitiative[1].Pending_Measures__c);
        
        Test.stopTest();
    }
    
    //Test update - only Status__c changes
    @isTest
    private static void testUpdate2() {
        Test.startTest();
        
        List<Measure__c> lstOfMeasure = [SELECT Id, Status__c FROM Measure__c];
        List<Initiative__c> lstOfInitiative = [SELECT Id FROM Initiative__c];
        for(Integer i = 0; i < 10; i++) {
            lstOfMeasure[i].Status__c = 'Met';
        }
        
        update lstOfMeasure;
        
        lstOfInitiative = [SELECT Id, Pending_Measures__c FROM Initiative__c];
        
        //System.assertEquals(10, lstOfInitiative[0].Pending_Measures__c);
        //System.assertEquals(0, lstOfInitiative[1].Pending_Measures__c);
        
        Test.stopTest();
    }
    
    //Test update - both Initiative__c and Status__c change
    @isTest
    private static void testUpdate3() {
        Test.startTest();
        
        //Sub-test 1: Status__c changes from Pending to Met
        List<Measure__c> lstOfMeasure = [SELECT Id, Initiative__c, Status__c FROM Measure__c];
        List<Initiative__c> lstOfInitiative = [SELECT Id FROM Initiative__c];
        
        for(Integer i = 0; i < 5; i++) {
            lstOfMeasure[i].Initiative__c = lstOfInitiative[1].Id;
            lstOfMeasure[i].Status__c = 'Met';
        }
        
        update lstOfMeasure;
        
        lstOfInitiative = [SELECT Id, Pending_Measures__c FROM Initiative__c];
        
        //System.assertEquals(10, lstOfInitiative[0].Pending_Measures__c);
        //System.assertEquals(0, lstOfInitiative[1].Pending_Measures__c);
        
        //Sub-test 2: Status__c changes from Met to Pending
        lstOfMeasure = [SELECT Id, Initiative__c, Status__c FROM Measure__c WHERE Status__c = 'Met'];
        lstOfInitiative = [SELECT Id FROM Initiative__c];
        
        for(Integer i = 0; i < 5; i++) {
            lstOfMeasure[i].Initiative__c = lstOfInitiative[0].Id;
            lstOfMeasure[i].Status__c = 'Pending';
        }
        
        update lstOfMeasure;
        
        lstOfInitiative = [SELECT Id, Pending_Measures__c FROM Initiative__c];
        
        //System.assertEquals(10, lstOfInitiative[0].Pending_Measures__c);
        //System.assertEquals(0, lstOfInitiative[1].Pending_Measures__c);
        
        Test.stopTest();
    }
}