force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Proceed to Full Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Final_Comments__c.field-meta.xml
<CustomField>
    <fullName>Final_Comments__c</fullName>
    <label>Final Comments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Sharepoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Sharepoint_URL__c</fullName>
    <inlineHelpText>Paste a link to the completed Application form received with this application.  The form must first be saved in KC or KS.</inlineHelpText>
    <label>Link to Application</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/Application_Round__c.object-meta.xml
<CustomObject>
    <label>Application Round</label>
    <nameField>
        <label>Application Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <formula>hyperlink(Application__r.Applicant__r.Id,Application__r.Applicant__r.Name)</formula>
    <label>Applicant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Total_Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_Weighted_Score__c</fullName>
    <label>Total Weighted Score</label>
    <summarizedField>Assessment_Score__c.Weighted_Score__c</summarizedField>
    <summaryForeignKey>Assessment_Score__c.Assessment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <label>Weighting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/Assessment_Score__c.object-meta.xml
<CustomObject>
    <label>Assessment Score</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Score__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Assessment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Criteria__c</fullName>
    <label>Assessment Criteria</label>
    <referenceTo>Assessment_Criteria__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Weighted_Score__c</fullName>
    <label>Weighted Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <formula>Assessment_Criteria__r.Weighting__c</formula>
    <label>Weighting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessor__c/Assessor__c.object-meta.xml
<CustomObject>
    <label>Assessor</label>
    <nameField>
        <displayFormat>Assessor-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessor__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessors</relationshipLabel>
    <relationshipName>Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessor__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssessorScoringController.cls
public with sharing class AssessorScoringController {
	public List<ScoringWrapper> scoringWrapperList {get;set;}
    private String retURL;
	public AssessorScoringController() {
		scoringWrapperList = new List<ScoringWrapper>();
        List<Assessment__c> assessmentList = new List<Assessment__c>();
        Map<Id, Application__c> applicationMap = new Map<Id, Application__c>(); 
        Set<Id> appIds = new Set<Id>();
        Id userId = UserInfo.getUserId();

        if(ApexPages.currentPage().getParameters().get('retURL') != null) {
            retURL = ApexPages.currentPage().getParameters().get('retURL');
        }
        if(ApexPages.currentPage().getParameters().get('appId') != null) {
            Id appId = string.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('appId'));
            appIds.add(appId);

        } 
		if(ApexPages.currentPage().getParameters().get('appRoundId') != null) {
            //Get all the application from the application
            String appRoundId = string.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('appRoundId'));
			applicationMap = new Map<Id, Application__c>([Select Id, Application_Round__r.OwnerId, Final_Comments__c,                                                                                 
                                                                    Decision__c From Application__c where Application_Round__c=:approundId]);

            if(applicationMap.size() > 0)
                appIds = applicationMap.keySet();
        }  
         String queryString = 'Select Id, Application__c, Application__r.Applicant__c,' +
                      ' Application__r.Sharepoint_URL__c, Comments__c, Total_Weighted_Score__c, Assessor__c,' +
                      ' (Select Id, Assessment_Criteria__r.Name, Score__c, Assessment_Criteria__r.Weighting__c, Weighted_Score__c From Assessment_Scores__r order by Assessment_Criteria__r.Name ASC ) ' +
                      ' From Assessment__c where Application__c=:appIds'; 
        queryString  += ' and Assessor__c=:userId order by Name ASC';    

        assessmentList = Database.query(queryString);

        system.debug('### assessmentList =>' + assessmentList.size());
        for(Assessment__c ass: assessmentList) {
            ScoringWrapper scoring = new ScoringWrapper();
            scoring.assessment = ass;
            scoring.assessmentScoreList = ass.Assessment_Scores__r;
            scoringWrapperList.add(scoring);
        }
	} 

    public PageReference saveBtn() {
        SavePoint sp = Database.setSavePoint();
        List<Assessment__c> assessmentUpdateList = new List<Assessment__c>();
        List<Assessment_Score__c> assessmentScoreUpdateList = new List<Assessment_Score__c>(); 
        for(ScoringWrapper swrap : scoringWrapperList) {
            assessmentUpdateList.add(swrap.assessment);
            assessmentScoreUpdateList.addAll(swrap.assessmentScoreList);
        }
        try {
            update assessmentUpdateList;
            try {
                update assessmentScoreUpdateList;
                PageReference pageRef = null;
                if(retURL != null)
                    pageRef= new PageReference(retURL);
                return pageRef;
            } catch (Exception err) {
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Error on Saving Assessor Scores. ' + err.getMessage() + ' ' + err.getLineNumber());
                ApexPages.addMessage(msg);
                return null;
            }
        } catch(Exception err) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Error on Saving Assessor Scores. ' + err.getMessage() + ' ' + err.getLineNumber());
            ApexPages.addMessage(msg);
            return null;
        }
        return null;
    }

    public PageReference cancelBtn() {
         PageReference pageRef = null;
        if(retURL != null)
            pageRef= new PageReference(retURL);
        return pageRef;
    }

	public class ScoringWrapper {
		public List<Assessment_Score__c> assessmentScoreList {get;set;}
		public Assessment__c assessment {get;set;}
		public ScoringWrapper() {
			assessmentScoreList = new List<Assessment_Score__c>();
			assessment = new Assessment__c();
		}
	}

}