force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Proceed to Full Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Final_Comments__c.field-meta.xml
<CustomField>
    <fullName>Final_Comments__c</fullName>
    <label>Final Comments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Moderated_Scores__c.field-meta.xml
<CustomField>
    <fullName>Moderated_Scores__c</fullName>
    <description>To store moderated scores that are separated by blank space.</description>
    <label>Moderated Scores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Sharepoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Sharepoint_URL__c</fullName>
    <inlineHelpText>Paste a link to the completed Application form received with this application.  The form must first be saved in KC or KS.</inlineHelpText>
    <label>Link to Application</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/Application_Round__c.object-meta.xml
<CustomObject>
    <label>Application Round</label>
    <nameField>
        <label>Application Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <formula>hyperlink(Application__r.Applicant__r.Id,Application__r.Applicant__r.Name)</formula>
    <label>Applicant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Real_Total_Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Real_Total_Weighted_Score__c</fullName>
    <formula>Total_Weighted_Score__c / 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Real Total Weighted Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Total_Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_Weighted_Score__c</fullName>
    <label>Total Weighted Score</label>
    <summarizedField>Assessment_Score__c.Weighted_Score__c</summarizedField>
    <summaryForeignKey>Assessment_Score__c.Assessment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <label>Weighting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/Assessment_Score__c.object-meta.xml
<CustomObject>
    <label>Assessment Score</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Score__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Assessment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Criteria__c</fullName>
    <label>Assessment Criteria</label>
    <referenceTo>Assessment_Criteria__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/AssessmentCriteriaAssessment__c.field-meta.xml
<CustomField>
    <fullName>AssessmentCriteriaAssessment__c</fullName>
    <externalId>true</externalId>
    <label>AssessmentCriteriaAssessment</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Weighted_Score__c</fullName>
    <label>Weighted Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <formula>Assessment_Criteria__r.Weighting__c</formula>
    <label>Weighting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/FinalAssessorScoringController.cls
public with sharing class FinalAssessorScoringController {
    public List<FinalScoringWrapper> finalScoringWrapperList {get;set;}
    public List<Assessment_Score__c> assessmentScoringHeaderList {get;set;} //For VF table header
    public Map<Id,List<Assessment_Score__c>> assessmentScoreMap {get;set;}
    
    //For weighting list
    public String assessmentCriteriaFlag {get;set;}
    public List<Decimal> weightingList {get;set;}

    private String appRoundId;
	public FinalAssessorScoringController() {
        finalScoringWrapperList = new List<FinalScoringWrapper>();
        assessmentScoreMap = new Map<Id,List<Assessment_Score__c>>();
        Map<Id, Application__c> applicationMap = new Map<Id, Application__c>(); 
        assessmentScoringHeaderList =  new List<Assessment_Score__c>();
        
        assessmentCriteriaFlag = null;
        weightingList = new List<Decimal>();
        
        Id userId = UserInfo.getUserId();


		if(ApexPages.currentPage().getParameters().get('appRoundId') != null) {
            //Get all the application from the application
            appRoundId = string.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('appRoundId'));
			//get the owner of the account
			String finalDecisionStr = ApexPages.currentPage().getParameters().get('FinalDecision');
            if(finalDecisionStr == 'true') {
                applicationMap = new Map<Id, Application__c>([Select Id, Applicant__c, Application_Round__r.OwnerId, Final_Comments__c, Moderated_Scores__c,
                                                        Decision__c, Sharepoint_URL__c, Name, Investment__c,
                                                        (Select Id, Name, Assessor__r.Name, Total_Weighted_Score__c, Real_Total_Weighted_Score__c, Comments__c,
                                                         Application__r.Applicant__c From Assessments__r) From Application__c where Application_Round__c=:approundId and Application_Round__r.OwnerId=:userId]);
            }
        }  

        if(applicationMap.size() > 0) {
            //get the assessments ids to get the assessment criteria score
            Map<Id,Assessment__c> assessmentMap = new Map<Id,Assessment__c> ();
            for(Application__c app: applicationMap.values()) {
                if(app.Assessments__r.size() > 0) {
                    for(Assessment__c ass : app.Assessments__r) {
                        assessmentMap.put(ass.Id, ass);
                    }
                }
            }
            //todo: get the asssessment criteria scores 
            if(assessmentMap.size() > 0) {
                List<Assessment_Score__c> assessmentScoreList = [Select Id, AssessmentCriteriaAssessment__c, Assessment__c, Assessment_Criteria__r.Name, Assessment_Criteria__r.Weighting__c, Score__c, Weighted_Score__c 
                                                                From Assessment_Score__c where Assessment__c=:assessmentMap.keyset() order by Assessment_Criteria__r.Name ASC];
                if(assessmentScoreList.size() > 0) {

                    //put assessment in a map assessmentId and list of scores
                    //Map<Id,List<Assessment_Score__c>> assessmentScoreMap = new Map<Id,List<Assessment_Score__c>> ();
                    for(Assessment_Score__c assScore : assessmentScoreList) {
                        if(!assessmentScoreMap.containsKey(assScore.Assessment__c)) {
                            List<Assessment_Score__c> assScList = new List<Assessment_Score__c>();
                            assScList.add(assScore);
                            assessmentScoreMap.put(assScore.Assessment__c, assScList);
                        } else {
                            assessmentScoreMap.get(assScore.Assessment__c).add(assScore);
                        }
                        //put weighting in a list
                        if(assessmentCriteriaFlag != assScore.Assessment_Criteria__r.Name) {
                        	assessmentCriteriaFlag = assScore.Assessment_Criteria__r.Name;
                        	weightingList.add(assScore.Assessment_Criteria__r.Weighting__c);
                        }
                    }

                    //build the final scoring wrapper
                    if(assessmentScoreMap.size() > 0) {
                         for(Application__c app: applicationMap.values()) {
                            FinalScoringWrapper finalScoring = new FinalScoringWrapper();
                            finalScoring.application = app;
                            List<Assessment__c> assList = new List<Assessment__c>();
                            for(Assessment__c ass : assessmentMap.values()) {
                                if(ass.Application__c == app.id) {
                                    assList.add(ass);
                                    finalScoring.averageWeightedScore += ass.Real_Total_Weighted_Score__c;
	                                assessmentScoringHeaderList = assessmentScoreMap.get(ass.id);
	                                //initialise the list of average weighted scores
	                                if(finalScoring.averageAssessmentScoreList.size() == 0)
	                                	for(Integer i = 0; i < assessmentScoringHeaderList.size(); i++)
	                                		finalScoring.averageAssessmentScoreList.add(0);
	                                //get average weighted scores
	                                for(Integer i = 0; i < assessmentScoringHeaderList.size(); i++) {
	                                	if(assessmentScoringHeaderList.get(i).Score__c != null && assessmentScoringHeaderList.get(i).Score__c != 0) {
	                                		Decimal temp = finalScoring.averageAssessmentScoreList.get(i) + assessmentScoringHeaderList.get(i).Score__c;
	                                		finalScoring.averageAssessmentScoreList.set(i, temp);
	                                	}
	                                }
                                }
                            }
                            finalScoring.assessmentList = assList;
                            for(Integer i = 0; i < finalScoring.averageAssessmentScoreList.size(); i++) {
                            	Decimal temp = finalScoring.averageAssessmentScoreList.get(i);
                            	if(temp != 0) {
                            		temp /= assList.size();
                            		finalScoring.averageAssessmentScoreList.set(i, temp.setScale(2));
                            	}
                            }
                            finalScoring.averageWeightedScore = (finalScoring.averageWeightedScore/assList.size()).setScale(2);
                            //get moderated scores
                            if(finalScoring.application.Moderated_Scores__c != null && finalScoring.application.Moderated_Scores__c != '') {
                            	List<String> strList = finalScoring.application.Moderated_Scores__c.split(';');
                            	while(strList.size() < assessmentScoringHeaderList.size())
                            		strList.add('');
                            	for(Integer i = 0; i < strList.size(); i++) {
                            		Decimal score, weightedScore;
                            		if(strList.get(i) == null || strList.get(i) == '') {
                            			score = 0;
                            			weightedScore = 0;
                            		} else {
                            			score = Decimal.valueOf(strList.get(i));
                            			weightedScore = weightingList.get(i)*score/100;
                            		}
                            		finalScoring.moderatedScoreList.add(new ModeratedScoreWrapper(score.setScale(2), weightedScore.setScale(2)));
                            	}
                            } else {
                            	for(Integer i = 0; i < assessmentScoringHeaderList.size(); i++)
                            		finalScoring.moderatedScoreList.add(new ModeratedScoreWrapper(0, 0));
                            }
                            //get moderated scores for the last column
                            for(ModeratedScoreWrapper ms : finalScoring.moderatedScoreList)
                            	finalScoring.averageWeightedModeratedScore += ms.weightedModeratedScore;
                            finalScoring.averageWeightedModeratedScore = finalScoring.averageWeightedModeratedScore.setScale(2);
                            
                            finalScoringWrapperList.add(finalScoring);
                        }
                    }

                }                
            }
        }
}

    public PageReference saveBtn() {
        SavePoint sp = Database.setSavePoint();
        List<Application__c> applicationUpdateList = new List<Application__c>();

        for(FinalScoringWrapper fscore : finalScoringWrapperList) {
            //set moderated scores
            fscore.application.Moderated_Scores__c = '';
            for(ModeratedScoreWrapper scoreWrapper : fscore.moderatedScoreList)
            	fscore.application.Moderated_Scores__c += (';' + scoreWrapper.moderatedScore);
            fscore.application.Moderated_Scores__c = fscore.application.Moderated_Scores__c.substring(1);
            applicationUpdateList.add(fscore.application);
        }
        try {
            update applicationUpdateList;
            PageReference pageRef = new PageReference('/' + appRoundId);
            return pageRef;
        } catch(Exception err) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Error on Saving. ' + err.getMessage() + ' ' + err.getLineNumber());
            ApexPages.addMessage(msg);
            return null;
        }
        return null;
    }

    public PageReference cancelBtn() {
        PageReference pageRef = new PageReference('/' + appRoundId);
        return pageRef;
    }

	//workaround the problem of apex:inputText not working inside nested apex:repeat tags
	public class ModeratedScoreWrapper {
		public Decimal moderatedScore {get;set;}
		public Decimal weightedModeratedScore {get;set;}
		public ModeratedScoreWrapper(Decimal score, Decimal weightedScore) {
			this.moderatedScore = score;
			this.weightedModeratedScore = weightedScore;
		}
	}

    public class FinalScoringWrapper {
        public Application__c application {get;set;}
        public List<Assessment__c> assessmentList {get;set;}
        public List<Decimal> averageAssessmentScoreList {get;set;}
        public Decimal averageWeightedScore {get;set;}
        public Decimal averageWeightedModeratedScore {get;set;}
        public List<ModeratedScoreWrapper> moderatedScoreList {get;set;}
        public FinalScoringWrapper() {
            application = new Application__c();
            assessmentList = new List<Assessment__c>();
            averageAssessmentScoreList = new List<Decimal>();
            moderatedScoreList = new List<ModeratedScoreWrapper>();
            averageWeightedScore = 0;
            averageWeightedModeratedScore = 0;
        }
    }    
}