force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>if(not(isblank(text(Decision__c))),  text(Decision__c),

if(not(isblank(Date_Shortlisted__c)), &quot;Shortlisted&quot;,

if(not(isblank(Date_Acknowledged__c)), &quot;Acknowledged&quot;,

if(not(isblank(Date_Received__c)) , &quot;Received&quot;, &quot;Error&quot;

))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/Application_Round__c.object-meta.xml
<CustomObject>
    <label>Application Round</label>
    <nameField>
        <label>Application Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Round__c/fields/Create_Assessments__c.field-meta.xml
<CustomField>
    <fullName>Create_Assessments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Assessments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the Investment Area that holds the budget that this application round relates to</inlineHelpText>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Application Rounds</relationshipLabel>
    <relationshipName>Application_Rounds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Assessment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <label>Weighting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessor__c/Assessor__c.object-meta.xml
<CustomObject>
    <label>Assessor</label>
    <nameField>
        <displayFormat>Assessor-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessor__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessors</relationshipLabel>
    <relationshipName>Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessor__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Partner_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Non-compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAssessorScoringController.cls
public with sharing class TestAssessorScoringController {
		/*
		public static void init() {
    	//Accounts
        List<Account> accountToInsertList = new List<Account>();
		Account accountObject = new Account();
		accountObject.Name = 'Athletics NZ';
		accountObject.Type = 'National Sporting Organization';
		accountToInsertList.add(accountObject);
		Account accountObjectLimited = new Account();
		accountObjectLimited.Name = 'Athletics Limited ';
		accountObjectLimited.Type = 'National Sporting Organization';
		accountToInsertList.add(accountObjectLimited);
		insert accountToInsertList;
		//Contact
		List<Contact> contactInsertList = new List<Contact>();
		Contact contactObject = new Contact();
		contactObject.LastName = 'PO';
		contactObject.Email = 'tst@davanti.co.nz';
		contactObject.AccountId = accountObjectLimited.id;
		contactInsertList.add(contactObject);
		insert contactInsertList;
		//Strategic Area
		Strategic_Area__c strategicAreaObject = new Strategic_Area__c();
		strategicAreaObject.Name = 'Community Sport';
		strategicAreaObject.Start_Date__c = date.today();
		strategicAreaObject.End_Date__c = date.today().addDays(5);
		insert strategicAreaObject;
		//Plan
	    List<Plan__c> planObjectInsertList = new List<Plan__c>();
		Plan__c planObject = new Plan__c();
		planObject.Partner__c = accountObject.id;
	    planObject.RecordTypeId = [Select Id from RecordType where sobjectType = 'Plan__c' and Name = 'Project Plan'].Id;
		planObject.Start_Date__c = date.today();
		planObject.End_Date__c = date.today().addDays(5);
		planObject.Status__c = 'Draft';
		planObjectInsertList.add(planObject);
		insert planObjectInsertList;
		//Investment Area
		list<Investment_Area__c> investmentAreaList = new list<Investment_Area__c>();
		Investment_Area__c investmentAreaObject = new Investment_Area__c();
		investmentAreaObject.Strategic_Area__c = strategicAreaObject.id;
		investmentAreaObject.Name = 'Sports NSO';
		investmentAreaObject.Start_Date__c = date.today();
		investmentAreaObject.End_Date__c = date.today().addDays(5);
	    investmentAreaObject.RecordTypeId = [Select Id from RecordType where sobjectType = 'Investment_Area__c' and Name = 'Contestable Investment'].Id;
		investmentAreaObject.Status__c = 'Active';
		investmentAreaList.add(investmentAreaObject);
		insert investmentAreaList;
		//Application Round
		List<Application_Round__c> appRoundList = new List<Application_Round__c>();
		Application_Round__c appRound1 = new Application_Round__c();
		appRound1.Name = 'Round 1';
		appRound1.Investment_Area__c = investmentAreaObject.id;
		appRound1.Status__c = 'Open';
		appRoundList.add(appRound1);
		insert appRoundList;
		//Application
		List<Application__c> applicationInsertList = new List<Application__c>();
		Application__c applicationObject = new Application__c();
		applicationObject.Applicant__c = accountObjectLimited.id;
		applicationObject.Application_Round__c = appRound1.id;
		applicationObject.Contact__c = contactObject.id;
		applicationObject.Date_Received__c = date.today();
		applicationInsertList.add(applicationObject);
		insert applicationInsertList;
		//User
       	Profile p = [Select Id From Profile where Name='Sport NZ - Finance'];
       	User u = new User(Alias='testpr', email='test@test.com', emailEncodingKey='UTF-8', lastname='Testing', languageLocaleKey='en_US',
	   	localeSidKey='en_US', profileId = p.Id,
    	timeZonesIdKey='Pacific/Auckland',
    	username='user1@sportsnz.org.nz.dev');
    	insert u;
		//Assessor
		Assessor__c assessorObject = new Assessor__c();
		assessorObject.Application_Round__c = appRound1.id;
		assessorObject.Assessor__c = u.id;
		insert assessorObject;
		//Assessment Criteria
		Assessment_Criteria__c assCriteriaObject = new Assessment_Criteria__c();
		assCriteriaObject.Name = 'Criteria 1';
		assCriteriaObject.Application_Round__c = appRound1.id;
		assCriteriaObject.Description__c = 'test';
		assCriteriaObject.Weighting__c = 20;
		insert assCriteriaObject;
		
		//update application round
		appRound1.Create_Assessments__c = true;
		update appRound1;
		
	}
	*/
	

}