force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/EOI_Application__c.field-meta.xml
<CustomField>
    <fullName>EOI_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EOI Application</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Application must be an Active Communities - Expression of Interest application</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Active Communities - EOI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/Application_Round__c.object-meta.xml
<CustomObject>
    <label>Application Round</label>
    <nameField>
        <label>Application Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Round__c/fields/Create_Assessments__c.field-meta.xml
<CustomField>
    <fullName>Create_Assessments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Assessments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/AssessorApplicationId__c.field-meta.xml
<CustomField>
    <fullName>AssessorApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>AssessorApplicationId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/Assessment_Score__c.object-meta.xml
<CustomObject>
    <label>Assessment Score</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Score__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/Assessment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Criteria__c</fullName>
    <label>Assessment Criteria</label>
    <referenceTo>Assessment_Criteria__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Score__c/fields/AssessmentCriteriaAssessment__c.field-meta.xml
<CustomField>
    <fullName>AssessmentCriteriaAssessment__c</fullName>
    <externalId>true</externalId>
    <label>AssessmentCriteriaAssessment</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Assessor__c/Assessor__c.object-meta.xml
<CustomObject>
    <label>Assessor</label>
    <nameField>
        <displayFormat>Assessor-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessor__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessors</relationshipLabel>
    <relationshipName>Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessor__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationRoundTriggerHandler.cls
public with sharing class ApplicationRoundTriggerHandler {
	public static void createAssessmentRecords(List<Application_Round__c> appRoundList) {
		Set<Id> appRoundIds = new Set<Id>();
		List<Application_Round__c> applicationRoundUpdateList = new List<Application_Round__c>();
		List<Assessment__c> assessmentInsertList = new List<Assessment__c>();
		List<Assessment_Score__c> assessmentScoreInsertList = new List<Assessment_Score__c>();
		for(Application_Round__c appRound :appRoundList) {
			if(appRound.Create_Assessments__c == true)
				appRoundIds.add(appRound.id);
		}
		List<Application_Round__c> appRoundRelatedList = [Select Id, (Select Id From Assessment_Criteria__r), (Select id From Applications__r), 
													(Select Id, Assessor__c From Assessors__r) From Application_Round__c where id=:appRoundIds];
		
		if(appRoundRelatedList.size() > 0) {
			//Assessor * Applications
			for(Application_Round__c appRound : appRoundRelatedList) {
				if(appRound.Assessors__r.size() > 0  && appRound.Applications__r.size() > 0) {
					for(Assessor__c ass : appRound.Assessors__r) {						
						for(Application__c app : appRound.Applications__r){
							Assessment__c assessment = new Assessment__c();
							assessment.Application__c = app.id;
							assessment.Assessor__c = ass.Assessor__c;
							assessment.AssessorApplicationId__c = ass.Assessor__c + '' + app.id;	
							assessmentInsertList.add(assessment);
						}	
					}
				}
			}
			if(assessmentInsertList.size() > 0) 
				upsert assessmentInsertList AssessorApplicationId__c; 
			//Assessment Criteria * Assessment
			for(Application_Round__c appRound : appRoundRelatedList) {
				if(appRound.Assessment_Criteria__r.size() > 0) {
					for(Assessment_Criteria__c assCriteria : appRound.Assessment_Criteria__r){
						for(Integer i=0; i < assessmentInsertList.size(); i ++){
							Assessment_Score__c assessmentScore = new Assessment_Score__c();
							assessmentScore.Assessment__c = assessmentInsertList.get(i).id;
							assessmentScore.Assessment_Criteria__c = assCriteria.id;
							assessmentScore.AssessmentCriteriaAssessment__c = assCriteria.id + '' + assessmentInsertList.get(i).id;
							assessmentScoreInsertList.add(assessmentScore);
						}	
					}
					//Reupdate Application Round List
					Application_Round__c applicationRound = new Application_Round__c();
					applicationRound.id = appRound.id;
					applicationRound.Create_Assessments__c = false;
					applicationRoundUpdateList.add(applicationRound);
				}
			}	
			if(assessmentScoreInsertList.size() > 0)
				upsert assessmentScoreInsertList AssessmentCriteriaAssessment__c;
				
			if(applicationRoundUpdateList.size() > 0)
				update applicationRoundUpdateList;	
		}	

			
	}
}