force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Date_Acknowledged__c.field-meta.xml
<CustomField>
    <fullName>Date_Acknowledged__c</fullName>
    <label>Date Acknowledged</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Date_Shortlisted__c.field-meta.xml
<CustomField>
    <fullName>Date_Shortlisted__c</fullName>
    <label>Date Shortlisted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <inlineHelpText>Project Name, Research Project Name or Team Name</inlineHelpText>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>if(not(isblank(text(Decision__c))),  text(Decision__c),

if(not(isblank(Date_Shortlisted__c)), &quot;Shortlisted&quot;,

if(not(isblank(Date_Acknowledged__c)), &quot;Acknowledged&quot;,

if(not(isblank(Date_Received__c)) , &quot;Received&quot;, &quot;Error&quot;

))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/Application_Round__c.object-meta.xml
<CustomObject>
    <label>Application Round</label>
    <nameField>
        <label>Application Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Round__c/fields/Application_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_End_Date__c</fullName>
    <inlineHelpText>This is the latest date/time when applications can be received.</inlineHelpText>
    <label>Application End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/fields/Application_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Start_Date__c</fullName>
    <inlineHelpText>This is the earliest date/time when applications can be received.</inlineHelpText>
    <label>Application Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/fields/Create_Assessments__c.field-meta.xml
<CustomField>
    <fullName>Create_Assessments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Assessments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the Investment Area that holds the budget that this application round relates to</inlineHelpText>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Application Rounds</relationshipLabel>
    <relationshipName>Application_Rounds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/fields/Shortlisting_Date__c.field-meta.xml
<CustomField>
    <fullName>Shortlisting_Date__c</fullName>
    <label>Shortlisting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Assessment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <formula>hyperlink(Application__r.Applicant__r.Id,Application__r.Applicant__r.Name)</formula>
    <label>Applicant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessor__c/Assessor__c.object-meta.xml
<CustomObject>
    <label>Assessor</label>
    <nameField>
        <displayFormat>Assessor-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessor__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessors</relationshipLabel>
    <relationshipName>Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessor__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_Security_Profile__c/Default_Security_Profile__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Default Security Profile</label>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAssessorTriggerHandler.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class TestAssessorTriggerHandler {

    static testMethod void TestAssessorTriggerHandler() {
        
        Default_Security_Profile__c profile = Default_Security_Profile__c.getValues('Profile');
		Id sportNZProfile = [Select Id from Profile where Name =:profile.Value__c].Id;
        //Id sportNZProfile = [Select Id from Profile where Name = 'Sport NZ'].Id;
        
        //Create User
        User userObject = new User();
        userObject.LastName = 'Test';
        userObject.Alias = 'test';
        userObject.Username = 'test@sportnz.org.nz';
        userObject.CommunityNickname = 'test';
        userObject.Email = 'test@sportnz.org.nz';
        userObject.EmailEncodingKey = 'UTF-8';
        userObject.LanguageLocaleKey = 'en_US';
        userObject.LocaleSidKey = 'en_NZ';
        userObject.TimeZoneSidKey = 'Pacific/Auckland';
        userObject.ProfileId = sportNZProfile;
        insert userObject;
        
        //Create Strategic Area
        Strategic_Area__c strategicAreaObject = new Strategic_Area__c();
        strategicAreaObject.Name = 'Test Strategic Area';
        strategicAreaObject.Start_Date__c = date.today();
        strategicAreaObject.End_Date__c = date.today().addDays(5);
        strategicAreaObject.Status__c ='Active';
        insert strategicAreaObject;
        
        Id investmentAreaStandardInvestmentRecordTypeId = [Select Id from RecordType where sobjectType = 'Investment_Area__c' and Name = 'Contestable Investment'].Id;
        //Create Investment Area
        Investment_Area__c investmentAreaObject = new Investment_Area__c();
        investmentAreaObject.RecordTypeId = investmentAreaStandardInvestmentRecordTypeId;
        investmentAreaObject.Strategic_Area__c = strategicAreaObject.id;
        investmentAreaObject.Name = 'Test Investment Area';
        investmentAreaObject.Start_Date__c = date.today();
        investmentAreaObject.End_Date__c = date.today().addDays(5);
        investmentAreaObject.Status__c = 'Active';
        insert investmentAreaObject;
        
        Application_Round__c appRound = new Application_Round__c();
        appRound.Application_End_Date__c = system.now().addDays(7);
        appRound.Application_Start_Date__c = system.now();
        appRound.Create_Assessments__c = true;
        appRound.Status__c = 'Open';
        appRound.Shortlisting_Date__c = system.now();
        appRound.Investment_Area__c = investmentAreaObject.Id;
        insert appRound;
        
        Application_Round__c appRound1 = new Application_Round__c();
        appRound1.Application_End_Date__c = system.now().addDays(7);
        appRound1.Application_Start_Date__c = system.now();
        appRound1.Create_Assessments__c = true;
        appRound1.Status__c = 'Pending Assessment';
        appRound1.Shortlisting_Date__c = system.now();
        appRound1.Investment_Area__c = investmentAreaObject.Id;
        insert appRound1;
        
        Id accountPartnerRecordTypeId = [Select Id from RecordType where sobjectType = 'Account' and Name = 'Organisation'].Id;
        Account accountObject = new Account();
        accountObject.RecordTypeId = accountPartnerRecordTypeId;
        accountObject.Name = 'Test Partner';
        accountObject.Type = 'National Sporting Organization';
        insert accountObject;
        
        Contact con = new Contact(lastName='test1',AccountId=accountObject.id);
        insert con;
        
        Application__c application = new Application__c();
        application.Name__c = 'testApp';
        application.Applicant__c = accountObject.Id;
        application.Contact__c = con.Id;
        application.Application_Round__c = appRound.Id;
        application.Date_Acknowledged__c = system.today().addDays(7);
        application.Date_Received__c = system.today().addDays(2);
        application.Date_Shortlisted__c = system.today().addDays(10);
        
        insert application;
        
        List<Assessor__c> lstAssessor = new list<Assessor__c>();
        Assessor__c assessor1 = new Assessor__c();
        assessor1.Application_Round__c = appRound.Id;
        assessor1.Assessor__c = userObject.Id; 
        lstAssessor.add(assessor1);
        
        Assessor__c assessor2 = new Assessor__c();
        assessor2.Application_Round__c = appRound1.Id;
        assessor2.Assessor__c = userObject.Id;
        lstAssessor.add(assessor2);
        
        insert lstAssessor;
        
        Assessment__c assessment = new Assessment__c();
        assessment.Application__c = application.Id;
        assessment.Assessor__c =userObject.Id;
        
        insert assessment;
        
        AssessorTriggerHandler.avoidAssessorDuplicate(lstAssessor);
        AssessorTriggerHandler.deleteOwnedAssessment(lstAssessor);
        
    }
}