force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/EOI_Application__c.field-meta.xml
<CustomField>
    <fullName>EOI_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EOI Application</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Application must be an Active Communities - Expression of Interest application</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Active Communities - EOI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/EOI_Clone__c.field-meta.xml
<CustomField>
    <fullName>EOI_Clone__c</fullName>
    <formula>if(not(EOI_Clone_Already_Cloned__c) &amp;&amp; EOI_Clone_Decision__c &amp;&amp; EOI_Clone_Full_Application_Round__c,true,false)</formula>
    <label>EOI Clone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/EOI_Clone_Already_Cloned__c.field-meta.xml
<CustomField>
    <fullName>EOI_Clone_Already_Cloned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EOI Clone - Already Cloned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Investment_Sought__c.field-meta.xml
<CustomField>
    <fullName>Investment_Sought__c</fullName>
    <label>Investment Sought</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <inlineHelpText>Project Name, Research Project Name or Team Name</inlineHelpText>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Total_Project_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Cost__c</fullName>
    <label>Total Project Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/Application_Round__c.object-meta.xml
<CustomObject>
    <label>Application Round</label>
    <nameField>
        <label>Application Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Round__c/fields/Full_Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Full_Application_Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Full Application Round</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Application_Round__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Active Communities - Full, Procurement - Full</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Application Rounds</relationshipLabel>
    <relationshipName>Application_Rounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/cloneApplication.cls
global with sharing class cloneApplication {

     webservice static String clone(Id applicationId, String recordTypeName) {
        //
        List<RecordType> recordTypeList = [Select Id, Name From RecordType where SobjectType='Application__c'];
        Map<String, Id> recordTypeMap = new Map<String, Id>();
        Application__c appClone = new Application__c();
        
        if(recordTypeList.size() > 0) {
            for(RecordType rec : recordTypeList) {
                recordTypeMap.put(rec.Name, rec.id);
            }
        }
        if(recordTypeName.endsWith('EOI')) {
            recordTypeName = recordTypeName.replace('EOI', 'Full');
            
            if(recordTypeMap.get(recordTypeName) != null) {
                //todo query the application
                List<Application__c> appUpsertList = new List<Application__c>();
                Application__c appObject = new Application__c();
                List<Application__c> appList = [Select Id, Name, Applicant__c, Application_Round__c, Contact__c, Description__c, End_Date__c,
                                            EOI_Application__c, Investment_Sought__c, Name__c, Plan__c, Start_Date__c, Total_Project_Cost__c, Application_Round__r.Full_Application_Round__c
                                            from Application__c where EOI_Clone__c=true and id=:applicationId];
                if(appList.size() > 0) {
                    appObject = appList.get(0);         
                    appObject.EOI_Clone_Already_Cloned__c = true;       
                    appClone = appObject.clone();
                    appClone.Date_Received__c = date.today();
                    appClone.EOI_Application__c = appObject.Id;
                    appClone.Application_Round__c = appObject.Application_Round__r.Full_Application_Round__c;
                    appClone.RecordTypeId = recordTypeMap.get(recordTypeName);
                    appUpsertList.add(appObject);
                    appUpsertList.add(appClone);            

                    if(appUpsertList.size() > 0) {
                        upsert appUpsertList;
                        return appClone.Id;
                    }
                    return null;    

                } return null;          
                
            }
            return null;
        }
        return null;
        
    }
}