force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Round__c/Application_Round__c.object-meta.xml
<CustomObject>
    <label>Application Round</label>
    <nameField>
        <label>Application Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessor__c/Assessor__c.object-meta.xml
<CustomObject>
    <label>Assessor</label>
    <nameField>
        <displayFormat>Assessor-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessor__c/fields/Application_Round__c.field-meta.xml
<CustomField>
    <fullName>Application_Round__c</fullName>
    <label>Application Round</label>
    <referenceTo>Application_Round__c</referenceTo>
    <relationshipLabel>Assessors</relationshipLabel>
    <relationshipName>Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessor__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssessorTriggerHandler.cls
public with sharing class AssessorTriggerHandler {
	public static void deleteOwnedAssessment(List<Assessor__c> assList) {
		Set<Id> appRoundIdSet = new Set<Id>();
		Set<Id> assessorIdSet = new Set<Id>();
		List<Assessment__c> assessmentDeleteList = new List<Assessment__c>();
		for(Assessor__c ass : assList) {
			appRoundIdSet.add(ass.Application_Round__c);
			assessorIdSet.add(ass.Assessor__c);
		}
		List<Assessment__c> assessmentList = [Select Id, Assessor__c, Application__r.Application_Round__c From Assessment__c Where Assessor__c =: assessorIdSet];
		
		if(assessmentList.size() > 0) {
				for(Assessment__c assessment : assessmentList) {
					if(appRoundIdSet.contains(assessment.Application__r.Application_Round__c)) {
						assessmentDeleteList.add(assessment);
					}
				}
				
			if(assessmentDeleteList.size() > 0)
				delete assessmentDeleteList;	
		}	
	}
	
	public static void avoidAssessorDuplicate(List<Assessor__c> assList) {
		Set<String> assAppRoundIdSet = new Set<String>();
		Set<Id> assessorIdSet = new Set<Id>();
		List<Assessment__c> assessmentDoubleList = new List<Assessment__c>();
		for(Assessor__c ass : assList) {
			assessorIdSet.add(ass.Assessor__c);
		}

		List<Assessment__c> assessmentList = [Select Id, Assessor__c, Application__r.Application_Round__c From Assessment__c Where Assessor__c =: assessorIdSet];
		if(assessmentList.size() > 0) {
			for(Assessment__c assessment : assessmentList) {
				for(Assessor__c ass : assList) {
					if(ass.Application_Round__c == assessment.Application__r.Application_Round__c)
						ass.Assessor__c.addError('The selected user is already an existing assessor for this application round');
				}
			}
		}	
	}
	

}