force-app/main/default/objects/Course_Participation_Data__c/Course_Participation_Data__c.object-meta.xml
<CustomObject>
    <label>Course Participation Data</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Course Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Participation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Participation_Data__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course Name</label>
    <referenceTo>Course_Activity_Profile_Data__c</referenceTo>
    <relationshipLabel>Course Participation Data</relationshipLabel>
    <relationshipName>Course_Participation_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Course_ParticipationController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of Course_Participation Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 30-11-2016       | Vivian Charlie   | 1. Created class to implement functionality of Course_Participation Page
   ==========================================================================================================================
*/
public class Course_ParticipationController{
    public Course_Participation_Data__c newCoursePart {get;set;}
    
    public Course_ParticipationController(){
        Id parentId = ApexPages.currentPage().getParameters().get('id');
        system.debug('parentId'+parentId);
        newCoursePart = new Course_Participation_Data__c();
        newCoursePart.Course__c = parentId;
    }
    
    public PageReference save()
    {   
    System.debug('in save');   
        try {
            upsert newCoursePart;
        } catch(exception e) {
            ApexPages.addMessages(e);          
        }
        return new PageReference('/' + newCoursePart.id);
    }
    
    public Pagereference cancel(){
        PageReference newpage = new Pagereference('/' + newCoursePart.Course__c);
        newpage.setRedirect(true);
        return newpage;
    }
}