force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Allocation__c/Funding_Allocation__c.object-meta.xml
<CustomObject>
    <label>Funding to Strategic Area</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Allocations to Strategic Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Allocation__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <label>Funding Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Allocation__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipName>Funding_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FundingAllocationTriggerHandler.cls
public with sharing class FundingAllocationTriggerHandler {

/* No Longer Required

    public static void updateStrategicArea(List<Funding_Allocation__c> triggerFundingAllocationList) {
        
        Set<Id> strategicAreaIdSet = new Set<Id>();
        List<Strategic_Area__c> updateStrategicAreaList = new List<Strategic_Area__c>();
        Map<Id,Decimal> strategicAreaBudgetMap = new Map<Id,Decimal>();
        
        for(Funding_Allocation__c f :triggerFun* NdingAllocationList){         
            strategicAreaIdSet.add(f.Strategic_Area__c);            
        }
        
        if(!strategicAreaIdSet.isEmpty()){                      
            List<Funding_Allocation__c> allFundingAllocationList = [SELECT Funding_Amount__c, Strategic_Area__c FROM Funding_Allocation__c WHERE Strategic_Area__c IN: strategicAreaIdSet AND Status__c = 'Approved'];
            for(Funding_Allocation__c fa: allFundingAllocationList){
                Decimal budget = strategicAreaBudgetMap.get(fa.Strategic_Area__c);  
                if(budget != null){
                    budget += fa.Funding_Amount__c; 
                    strategicAreaBudgetMap.put(fa.Strategic_Area__c,budget);                    
                }
                else{
                    strategicAreaBudgetMap.put(fa.Strategic_Area__c,fa.Funding_Amount__c);              
                }
            }
        }
        
        for(Id sa :strategicAreaIdSet){         
            Strategic_Area__c s = new Strategic_Area__c(Id=sa);
            Decimal updatedBudget = strategicAreaBudgetMap.get(sa);
            if(updatedBudget == null || updatedBudget == 0)
                s.budget__c = 0;
            else
                s.budget__c = updatedBudget;
            updateStrategicAreaList.add(s);
        }
            
        if(!updateStrategicAreaList.isEmpty())
            update updateStrategicAreaList;     
    }
    
    */
}