force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/recordTypes/Bundled_Plan.recordType-meta.xml
<RecordType>
    <fullName>Bundled_Plan</fullName>
    <active>true</active>
    <description>For initiatives that contribute to a project or contestable investment. All initiatives in a Project Plan will be of the same Investment Area.</description>
    <label>Project Plan</label>
</RecordType>

force-app/main/default/objects/Initiative__c/recordTypes/Partner_Plan.recordType-meta.xml
<RecordType>
    <fullName>Partner_Plan</fullName>
    <active>true</active>
    <description>For initiatives that are included in the Partner Planning process. Each Initiative in a Partner Plan will belong to only one Partner.</description>
    <label>Partner Plan</label>
</RecordType>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Partner_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/recordTypes/Bundled_Plan.recordType-meta.xml
<RecordType>
    <fullName>Bundled_Plan</fullName>
    <active>true</active>
    <description>Used for grouping initiatives for non-targeted Partners, contestable investments, programmes, and supplier contracts</description>
    <label>Project Plan</label>
</RecordType>

force-app/main/default/objects/Plan__c/recordTypes/Partner_Plan.recordType-meta.xml
<RecordType>
    <fullName>Partner_Plan</fullName>
    <active>true</active>
    <description>For engagement and investment planning with organisations that Sport NZ Group targets</description>
    <label>Partner Plan</label>
</RecordType>

force-app/main/default/classes/PlanTriggerhandler.cls
public with sharing class PlanTriggerhandler {

    public static void UpdateInitiativeFields(List<Plan__c> planlst){
         system.debug('Inside PlanTriggerhandler UpdateInitiativeFields() method');

        List<Initiative__c> updatedInitLst = new List<Initiative__c>();

        for (Initiative__c init : [SELECT Id, Partner__c, Investment_Area__c, Plan__r.Partner__c, Plan__r.Investment_Area__c, Plan__r.RecordType.DeveloperName FROM Initiative__c WHERE Plan__r.Id IN : planlst]) {
            if (init.Plan__r.RecordType.DeveloperName == 'Partner_Plan' && (init.Partner__c != init.Plan__r.Partner__c)) {
                init.Partner__c = init.Plan__r.Partner__c;
                updatedInitLst.add(init);
            }
            else if (init.Plan__r.RecordType.DeveloperName == 'Bundled_Plan' && (init.Investment_Area__c != init.Plan__r.Investment_Area__c)) {
                init.Investment_Area__c = init.Plan__r.Investment_Area__c;
                updatedInitLst.add(init);
            }                       
        }
        
        if(!updatedInitLst.IsEmpty()) { 
            update updatedInitLst;
        }
    }
}