force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The Name and Description of the Requirement are displayed in the Investment Schedule.  These should clearly describe what is required.</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Reporting_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Type__c</fullName>
    <label>Reporting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Written</fullName>
            </value>
            <value>
                <fullName>Verbal with Documentation</fullName>
            </value>
            <value>
                <fullName>Verbal</fullName>
            </value>
            <value>
                <fullName>Sport NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Requirement_Reporting_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Reporting_Record_Type__c</fullName>
    <description>This field will be used to determine whether Reporting is enabled for Partner users or not</description>
    <label>Requirement Reporting Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CS Case Study</fullName>
            </value>
            <value>
                <fullName>CS Board Diversity</fullName>
            </value>
            <value>
                <fullName>PI National</fullName>
            </value>
            <value>
                <fullName>PI Regional</fullName>
            </value>
            <value>
                <fullName>PI National + 1</fullName>
            </value>
            <value>
                <fullName>PI National + 2</fullName>
            </value>
            <value>
                <fullName>PI National + 3</fullName>
            </value>
            <value>
                <fullName>PI National + 4</fullName>
            </value>
            <value>
                <fullName>PI Regional + 1</fullName>
            </value>
            <value>
                <fullName>PI Regional + 2</fullName>
            </value>
            <value>
                <fullName>PI Regional + 3</fullName>
            </value>
            <value>
                <fullName>PI Regional + 4</fullName>
            </value>
            <value>
                <fullName>PI National 1</fullName>
            </value>
            <value>
                <fullName>PI National 2</fullName>
            </value>
            <value>
                <fullName>PI National 3</fullName>
            </value>
            <value>
                <fullName>PI National 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#FF9900</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#009900</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FF0000</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#DDDDDD</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Variation</fullName>
                <color>#BBBBBB</color>
                <label>Variation</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <color>#666666</color>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#333333</color>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HistoricInitiativeController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to implement functionality of Historic Reporting Page

=========================================================================================================================
Version | Date(DD-MM-YYYY) | Last Modified By | Comments
-------------------------------------------------------------------------------------------------------------------------
1.0     | 11-03-2022       | Aruna Mulik   | 1. Controller Historic Reporting Page
==========================================================================================================================
*/

public class HistoricInitiativeController {
    public List<Initiative__c> AllRecords {get;set;}
    public ApexPages.StandardSetController stdSetController 
    {                                
        get {
            list<user> lstUsr = [SELECT Id,
                                 ContactID,
                                 contact.accountId 
                                 FROM User 
                                 WHERE id=: UserInfo.getUserId()];
            if(lstUsr != null && !lstUsr.isEmpty()) {   
                
                AllRecords = [SELECT Id, 
                              Name, 
                              Partner__c,
                              Start_Date__c,
                              End_Date__c,
                              Description__c,
                              (Select Reporting_Type__c,Initiative__c From Requirements__r where Status__c ='Completed'  and Requirement_Reporting_Record_Type__c != NULL)
                              FROM Initiative__c
                              WHERE Partner__c=:lstUsr[0].contact.accountId];
            }
            //RUL Updated ends 18 March 2019
            set<Id> initIds = new set<Id>();
            list<Initiative__c> lstInit = new list<Initiative__c>();
            for(Initiative__c initObj: AllRecords) {
                if(initObj.Requirements__r != NULL){          
                    for (Requirement__c reqObj : initObj.Requirements__r) {
                        initIds.add(reqObj.Initiative__c);                
                    }
                }
                                 
            }
            
            List<Requirement__c> reqList = new List<Requirement__c>();
            List<Requirement__c> requirementList1 = [SELECT	Id, 
                                                    		Initiative__r.name, 
                                                    		Description__c, 
                                                    		Initiative__r.Id, 
                                                    		Initiative__r.Partner__c,
                        									Name, 
                                                    		Due_Date__c,
                                                    		Status__c, Requirement_Reporting_Record_Type__c  
                                                    from 	Requirement__c
                                                    WHERE 	Initiative__r.Partner__c=:lstUsr[0].contact.accountId
                                                    AND 	Initiative__r.Id IN :initIds 
                                                    AND		Status__c ='Completed'
                                                    AND 	Requirement_Reporting_Record_Type__c!=NULL
                                                    Order by Due_Date__c DESC];
            
            if(stdSetController == null) {
                for(Requirement__c req : requirementList1) {
                    reqList.add(req);
                }
                stdSetController = new ApexPages.StandardSetController(reqList);
                stdSetController.setPageSize(20);
            }
            return stdSetController;
        }
        set;       
    }
    
    public List<Requirement__c> getInitiatives() {
        return (List<Requirement__c>) stdSetController.getRecords();
    }
    
    public Boolean hasNext {
        get {
            return stdSetController.getHasNext();
        }
        set;
    }
    
    public Boolean hasPrevious {
        get {
            return stdSetController.getHasPrevious();
        }
        set;
    }   
    
    public void first() {
        stdSetController.first();
    }
    
    public void last() {
        stdSetController.last();
    }
    
    public void previous() {
        stdSetController.previous();
    }
    
    public void next() {
        stdSetController.next();
    }
}