force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Initiative_Owner__c.field-meta.xml
<CustomField>
    <fullName>Initiative_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <formula>Investment_Area__r.Strategic_Area__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Strategic Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Work_Brief__c.field-meta.xml
<CustomField>
    <fullName>Work_Brief__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Brief</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Work_Brief__c.Stage__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Work_Brief__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Investment_Area_Owner__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investment_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Partner_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Non-compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#FF9900</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#009900</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FF0000</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#DDDDDD</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Variation</fullName>
                <color>#BBBBBB</color>
                <label>Variation</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <color>#666666</color>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#333333</color>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sport NZ</fullName>
            </value>
            <value>
                <fullName>High Performance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Brief__c/Work_Brief__c.object-meta.xml
<CustomObject>
    <description>Work brief planning and reporting</description>
    <label>Work Brief</label>
    <nameField>
        <label>Work Brief ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Briefs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Brief__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestHistoricInitiativeController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of Historic Page

=========================================================================================================================
Version | Date(DD-MM-YYYY) | Last Modified By | Comments
-------------------------------------------------------------------------------------------------------------------------
1.0     | 31-03-2022       | Aruna Mulik   | 1. Created test class to test functionality of Historic Page
==========================================================================================================================
*/
@isTest
private class TestHistoricInitiativeController  {
/*
@ Description : Method to insert Initiative
*/
    public static testMethod void testInitiativeAccessToPartners() {
        //Creating test data
        Work_Brief__c workObj = new Work_Brief__c();
        workObj.Name = 'Test Work';
        workObj.Stage__c = 'Active';
        insert workObj;
        list<Strategic_Area__c> stratAreaList = new list<Strategic_Area__c>();
        for(Integer i=0; i<50; i++) {
            Strategic_Area__c sratObj = new Strategic_Area__c();
            sratObj.name = 'Test Strategic Area'+i;
            sratObj.Entity__c = 'Sport NZ';
            sratObj.End_Date__c = Date.Today()+i;
            sratObj.Start_Date__c = Date.Today();
            stratAreaList.add(sratObj);
        }
        insert stratAreaList;
        
        Account acc = new Account(name='TestAcc');
        insert acc;
        
        Profile profiles = [SELECT Id,
                            Name
                            FROM Profile
                            WHERE Name = 'Disability Community (Partner)' limit 1];
        Contact con= new Contact(LastName = 'TestCon',AccountId = acc.id);
        insert con;        
        
        User communityUser = new User(FirstName = 'Community',
                                      LastName = 'User'+1,
                                      Alias = 'CU',
                                      Email = 'commTest@test.com',
                                      Username = Math.random() + '@test.com',
                                      CommunityNickname = 'cust6',
                                      ContactId = con.Id,
                                      EmailEncodingKey = 'UTF-8',
                                      TimeZoneSidKey = 'America/Los_Angeles',
                                      LocaleSidKey = 'en_US',
                                      LanguageLocaleKey = 'en_US',
                                      PortalRole = 'Manager',
                                      ProfileId = profiles.Id,
                                      IsActive = true);      
        insert communityUser;
        
        list<Investment_Area__c> invAreaList = new list<Investment_Area__c>();
        for(Integer i=0; i<50; i++) {
            Investment_Area__c invObj = new Investment_Area__c();
            invObj.name = 'Test Investment Area'+i;
            invObj.Status__c = 'Active';
            invObj.End_Date__c = Date.Today()+i;
            invObj.Start_Date__c = Date.Today();
            invObj.Strategic_Area__c = stratAreaList[i].id;
            invObj.Investment_Area_Owner__c = communityUser.id;
            invAreaList.add(invObj);
        }
        insert invAreaList;
        
        list<Plan__c> planList = new list<Plan__c>();
        for(Integer i=0; i<50; i++) {
            Plan__c planObj = new Plan__c();
            planObj.Partner__c = acc.id;
            planObj.Status__c = 'Active';
            planObj.End_Date__c = Date.newInstance(2099, 06 ,30);
            planObj.Start_Date__c = Date.newInstance(2013, 01 ,01);
            planList.add(planObj);
        }
        insert planList;
        
        user usr= [Select id,contactId ,contact.accountId from User where contactId =: communityUser.ContactId and UserRoleId != NULL and IsActive =true limit 1];
        
        //system.runAs(usr) { 
            list<Initiative__c> initList = new list<Initiative__c>();
            for(Integer i=0; i<50; i++) {
                Initiative__c initObj = new Initiative__c();
                initObj.name = 'Test Initiative'+i;
                initObj.Investment_Area__c = invAreaList[0].id;
                initObj.Plan__c = planList[0].id;
                initObj.Initiative_Owner__c = communityUser.id;
                initObj.Priority__c = 'Must';
                initObj.Type__c = 'Paid Direct';           
                initObj.Planned__c = 200;
                initObj.Work_Brief__c = workObj.Id;
                initObj.End_Date__c = Date.Today().addYears(1);
                initObj.Start_Date__c = Date.Today();
                initObj.Partner__c = acc.id;
                initList.add(initObj);
            }
            insert initList;
            
            list<Requirement__c> reqList = new list<Requirement__c>();
            for(Integer i=0; i<50; i++) {
                Requirement__c reqObj = new Requirement__c();
                reqObj.name = 'Test Requirement'+i;
                reqObj.Reporting_Type__c = 'Written';
                reqObj.Description__c = 'Test Desc';
                reqObj.Partner__c = acc.id;
                reqObj.Due_Date__c = Date.Today()+10;
                reqObj.Initiative__c = initList[i].id;
                reqObj.Requirement_Reporting_Record_Type__c = 'CS Board Diversity';
                reqList.add(reqObj);
            }
            insert reqList;
            
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(initList);
            
            HistoricInitiativeController controller = new HistoricInitiativeController();
            controller.getInitiatives();
            controller.next();
            controller.previous();
            controller.last();
            controller.first();
            boolean test1 = controller.hasNext;
            boolean test2 = controller.hasPrevious;
            
            list<Initiative__c> lstInit = new list<Initiative__c>([SELECT Id,
                                                                   Name, 
                                                                   Partner__c,
                                                                   Start_Date__c,
                                                                   End_Date__c,
                                                                   (Select Reporting_Type__c,Initiative__c From Requirements__r where Requirement_Reporting_Record_Type__c != NULL)
                                                                   FROM Initiative__c]);
            system.assertEquals(50,lstInit.size());
        //}
    }
    /*
@ Description : Method to insert Initiative whose related Requirement has Reporting Record type as blank values
*/
    public static testMethod void testInitiativeWithoutReportingType() {
        //Creating test data
        list<Strategic_Area__c> stratAreaList = new list<Strategic_Area__c>();
        for(Integer i=0; i<50; i++) {
            Strategic_Area__c sratObj = new Strategic_Area__c();
            sratObj.name = 'Test Strategic Area'+i;
            sratObj.Entity__c = 'Sport NZ';
            sratObj.End_Date__c = Date.Today()+i;
            sratObj.Start_Date__c = Date.Today();
            stratAreaList.add(sratObj);
        }
        insert stratAreaList;
        
        Account acc = new Account(name='TestAcc');
        insert acc;
        
        Profile profiles = [SELECT Id,
                            Name
                            FROM Profile
                            WHERE Name = 'Disability Community (Partner)' limit 1];
        
        Contact con= new Contact(LastName = 'TestCon',AccountId = acc.id);
        insert con;        
        
        User communityUser = new User(FirstName = 'Community',
                                      LastName = 'User'+1,
                                      Alias = 'CU',
                                      Email = 'commTest@test.com',
                                      Username = Math.random() + '@test.com',
                                      CommunityNickname = 'cust6',
                                      ContactId = con.Id,
                                      EmailEncodingKey = 'UTF-8',
                                      TimeZoneSidKey = 'America/Los_Angeles',
                                      LocaleSidKey = 'en_US',
                                      LanguageLocaleKey = 'en_US',
                                      PortalRole = 'Manager',
                                      ProfileId = profiles.Id,
                                      IsActive = true);      
        insert communityUser;
        
        list<Investment_Area__c> invAreaList = new list<Investment_Area__c>();
        
        for(Integer i=0; i<50; i++) {
            Investment_Area__c invObj = new Investment_Area__c();
            invObj.name = 'Test Investment Area'+i;
            invObj.Status__c = 'Active';
            invObj.End_Date__c = Date.Today()+i;
            invObj.Start_Date__c = Date.Today();
            invObj.Strategic_Area__c = stratAreaList[i].id;
            invObj.Investment_Area_Owner__c = communityUser.id;
            invAreaList.add(invObj);
        }
        insert invAreaList;
        
        list<Plan__c> planList = new list<Plan__c>();
        for(Integer i=0; i<50; i++) {
            Plan__c planObj = new Plan__c();
            planObj.Partner__c = acc.id;
            planObj.Status__c = 'Active';
            planObj.End_Date__c = Date.newInstance(2099, 06 ,30);
            planObj.Start_Date__c = Date.newInstance(2013, 01 ,01);
            planList.add(planObj);
        }
        insert planList;
        
        user usr= [Select id,contactId ,contact.accountId from User where contactId =: communityUser.ContactId and UserRoleId != NULL and IsActive =true limit 1];
        
        Work_Brief__c workObj = new Work_Brief__c();
        workObj.Name = 'Test Work';
        workObj.Stage__c = 'Active';
        insert workObj;
        
        //system.runAs(usr) { 
            list<Initiative__c> initList = new list<Initiative__c>();
            for(Integer i=0; i<50; i++) {
                Initiative__c initObj = new Initiative__c();
                initObj.name = 'Test Initiative'+i;
                initObj.Investment_Area__c = invAreaList[0].id;
                initObj.Plan__c = planList[0].id;
                initObj.Initiative_Owner__c = communityUser.id;
                initObj.Priority__c = 'Must';
                initObj.Type__c = 'Paid Direct';           
                initObj.Planned__c = 200;
                initObj.Work_Brief__c = workObj.Id;
                initObj.End_Date__c = Date.Today().addYears(1);
                initObj.Start_Date__c = Date.Today();
                initObj.Partner__c = acc.id;
                initList.add(initObj);
            }
            insert initList;
            
            list<Requirement__c> reqList = new list<Requirement__c>();
            for(Integer i=0; i<50; i++) {
                Requirement__c reqObj = new Requirement__c();
                reqObj.name = 'Test Requirement'+i;
                reqObj.Reporting_Type__c = 'Written';
                reqObj.Description__c = 'Test Desc';
                reqObj.Partner__c = acc.id;
                reqObj.Due_Date__c = Date.Today()+10;
                reqObj.Initiative__c = initList[i].id;
                reqList.add(reqObj);
            }
            insert reqList;
            
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(initList);
            
            HistoricInitiativeController controller = new HistoricInitiativeController();
            controller.getInitiatives();
            controller.next();
            controller.previous();
            controller.last();
            controller.first();
            boolean test1 = controller.hasNext;
            boolean test2 = controller.hasPrevious;
            
            list<Initiative__c> lstInit = new list<Initiative__c>([SELECT Id,
                                                                   Name, 
                                                                   Partner__c,
                                                                   Start_Date__c,
                                                                   End_Date__c,
                                                                   (Select Reporting_Type__c,Initiative__c From Requirements__r where Requirement_Reporting_Record_Type__c != NULL)
                                                                   FROM Initiative__c]);
            List <Requirement__c> listReq = new List<Requirement__c>();
            for(Initiative__c objInit : lstInit ){
                for(Requirement__c objReq : objInit.Requirements__r){
                    listReq.add(objReq);
                }
            }
            system.assertEquals(0,listReq.size());
       // }
    }
}