force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <formula>Investment_Area__r.Strategic_Area__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Strategic Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Investment_Area_Owner__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investment_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Partner__c</field>
            <operation>equals</operation>
            <valueField>Initiative__c.Partner__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Update the Status when you receive results against this Measure.  This will generally be when you record the Result and Result Date.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
                <default>true</default>
                <label>Removed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Partially Met</fullName>
            </value>
            <value>
                <fullName>Not Met</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Partner_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Non-compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#FF9900</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#009900</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FF0000</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#DDDDDD</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Variation</fullName>
                <color>#BBBBBB</color>
                <label>Variation</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <color>#666666</color>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#333333</color>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sport NZ</fullName>
            </value>
            <value>
                <fullName>High Performance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Init_Measure_Requirement_ControllerTest.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of Initiative Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 16-12-2016       | Vivian Charlie   | 1. Created test class to test functionality of Initiative Requirement 
                                                           Measure Page
   ==========================================================================================================================
*/
@isTest
private class Init_Measure_Requirement_ControllerTest {
    /*
     @ Description : Method to insert Initiative
    */
    public static testMethod void testInitiativeMeasuresReq() {
        //Creating test data
        list<Strategic_Area__c> stratAreaList = new list<Strategic_Area__c>();
        for(Integer i=0; i<50; i++) {
            Strategic_Area__c sratObj = new Strategic_Area__c();
            sratObj.name = 'Test Strategic Area'+i;
            sratObj.Entity__c = 'Sport NZ';
            sratObj.End_Date__c = Date.Today()+i;
            sratObj.Start_Date__c = Date.Today();
            stratAreaList.add(sratObj);
        }
        insert stratAreaList;
        
        Account acc = new Account(name='TestAcc');
        insert acc;
        system.debug('acc'+acc);
        Profile profiles = [SELECT Id,
                                   Name
                            FROM Profile
                            WHERE Name like '%Partner%' limit 1];
        Contact con= new Contact(LastName = 'TestCon',AccountId = acc.id);
        insert con;        
        User communityUser = new User(FirstName = 'Community',
                                           LastName = 'User'+1,
                                           Alias = 'CU',
                                           Email = 'commTest@test.com',
                                           Username = Math.random() + '@test.com',
                                           CommunityNickname = 'cust6',
                                           ContactId = con.Id,
                                           EmailEncodingKey = 'UTF-8',
                                           TimeZoneSidKey = 'America/Los_Angeles',
                                           LocaleSidKey = 'en_US',
                                           LanguageLocaleKey = 'en_US',
                                           PortalRole = 'Manager',
                                           ProfileId = profiles.Id,
                                           IsActive = true);      
        insert communityUser;
        
        list<Investment_Area__c> invAreaList = new list<Investment_Area__c>();
        for(Integer i=0; i<50; i++) {
            Investment_Area__c invObj = new Investment_Area__c();
            invObj.name = 'Test Investment Area'+i;
            invObj.Status__c = 'Active';
            invObj.End_Date__c = Date.Today()+i;
            invObj.Start_Date__c = Date.Today();
            invObj.Strategic_Area__c = stratAreaList[i].id;
            invObj.Investment_Area_Owner__c = communityUser.id;
            invAreaList.add(invObj);
        }
        insert invAreaList;
        
        list<Plan__c> planList = new list<Plan__c>();
        for(Integer i=0; i<50; i++) {
            Plan__c planObj = new Plan__c();
            planObj.Partner__c = acc.id;
            planObj.Status__c = 'Active';
            planObj.End_Date__c = Date.Today()+i;
            planObj.Start_Date__c = Date.Today();
            planList.add(planObj);
        }
        insert planList;
        
        list<Initiative__c> initList = new list<Initiative__c>();
        for(Integer i=0; i<50; i++) {
            Initiative__c initObj = new Initiative__c();
            initObj.name = 'Test Initiative'+i;
            initObj.Investment_Area__c = invAreaList[0].id;
            initObj.Plan__c = planList[0].id;
            initObj.Initiative_Owner__c = communityUser.id;
            initObj.Priority__c = 'Must';
            initObj.Type__c = 'Paid Direct';           
            initObj.Planned__c = 200;
            initObj.End_Date__c = Date.Today();
            initObj.Start_Date__c = Date.Today();
            initObj.Partner__c = acc.id;
            initList.add(initObj);
        }
        insert initList;
        system.debug('initList'+initList);
        
        list<Measure__c> measuresList = new list<Measure__c>();
        for(Integer i=0; i<50; i++) {
            Measure__c measObj = new Measure__c();
            measObj.name = 'Test Measure'+i;
            measObj.Reporting_Type__c = 'Written';
            measObj.Description__c = acc.id;
            measObj.Partner__c = acc.id;
            measObj.Initiative__c = initList[i].id;
            measuresList.add(measObj);
        }
        insert measuresList;
        system.debug('measuresList'+measuresList);
        
        list<Requirement__c> reqList = new list<Requirement__c>();
        for(Integer i=0; i<50; i++) {
            Requirement__c reqObj = new Requirement__c();
            reqObj.name = 'Test Requirement'+i;
            reqObj.Reporting_Type__c = 'Written';
            reqObj.Description__c = acc.id;
            reqObj.Partner__c = acc.id;
            reqObj.Initiative__c = initList[i].id;
            reqList.add(reqObj);
        }
        insert reqList;
        system.debug('reqList'+reqList);
        
        user usr= [Select id,contactId ,contact.accountId from User where contactId =: communityUser.ContactId and UserRoleId != NULL and IsActive =true limit 1];
        system.debug(loggingLevel.error,'usr'+usr);
        
        system.runAs(usr) {            
            ApexPages.StandardController sc= new ApexPages.StandardController(initList[0]);
            
            Initiative_MeasureController MeasureController = new Initiative_MeasureController(sc);
            MeasureController.getMeasures();
            MeasureController.next1();
            MeasureController.previous1();
            MeasureController.last1();
            MeasureController.first1();
            boolean nextMeas = MeasureController.hasNext1;
            boolean prevMeas = MeasureController.hasPrevious1;
            
            Initiative_RequirementController ReqController = new Initiative_RequirementController(sc);
            ReqController.getRequirements();
            ReqController.next();
            ReqController.previous();
            ReqController.last();
            ReqController.first();
            boolean nextReq = ReqController.hasNext;
            boolean prevReq = ReqController.hasPrevious;
                                      
            list<Measure__c> lstMeas = new list<Measure__c>([SELECT Id
                                                             FROM Measure__c
                                                             WHERE Partner__c =:acc.Id AND Initiative__c IN:initList]);
            list<Requirement__c> lstRequi = new list<Requirement__c>([SELECT Id
                                                                      FROM Requirement__c
                                                                      WHERE Partner__c =:acc.Id AND Initiative__c IN:initList]);                                                 
            /*
            system.assertEquals(lstMeas.size(),MeasureController.measureList.size());
            system.assertEquals(lstMeas.size(),ReqController.reqList.size());
            */
        }
    }
}