force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status_Text__c.field-meta.xml
<CustomField>
    <fullName>Status_Text__c</fullName>
    <label>Status Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Update_Status_text__c.field-meta.xml
<CustomField>
    <fullName>Update_Status_text__c</fullName>
    <description>Field used by batch job to identify records where the status_text does not equal the status value. If field it true then record will update when batch next run.</description>
    <formula>Status__c  &lt;&gt;  Status_Text__c</formula>
    <label>Update Status_text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InitiativeStatusChangeBatch.cls
/*
*@ Author       :- Navneet Rajput 
*@ Company      :- Davanti
*@ Date         :- 03/07/2015
*@ Description  :- This batch will execute once in a day and it will check status field of Initiative. If status field of initiative is
                    not same as Status_Text of initiatve then it will update Status_Text with Status field.     
*@ History      :- 
*/


global class InitiativeStatusChangeBatch implements Database.Batchable<sObject>{

    global Database.querylocator start(Database.BatchableContext BC){
            
            DateTime lastDay = System.now().addDays(-1);
            
            return Database.getQueryLocator([SELECT ID,
                                                    Status__c,
                                                    Status_Text__c
                                             FROM   Initiative__c
                                             WHERE  Update_Status_text__c=TRUE]);
                                             
    }

    
    global void execute(Database.BatchableContext BC, List<Initiative__c> listOfInitiative){
        
        Savepoint savePt = Database.setSavepoint();
        try {
            List<Initiative__c> tempInitiativeLst = new List<Initiative__c>();
            for (Initiative__c initiative : listOfInitiative){
                if(initiative.Status__c <> initiative.Status_Text__c){
                    initiative.Status_Text__c = initiative.Status__c;
                    tempInitiativeLst.add(initiative);
                }
            }
            if (tempInitiativeLst<>NULL && !tempInitiativeLst.isEmpty()){
                update tempInitiativeLst;
            }
            
        } catch (System.DmlException e) {
            System.debug('Exception Is ' + e.getMessage());
            Database.rollback(savePt);
        } 
    }
        
    global void finish(Database.BatchableContext BC){
        
    }
    
}