force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitiativePayment__c/InitiativePayment__c.object-meta.xml
<CustomObject>
    <description>This object is created specifically for NintexDoc generation. This will hold data to overcome challenges faced with OOTB approach. The records in this object will be created through flow.</description>
    <label>InitiativePayment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>InitiativePayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InitiativePayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InitiativePayment__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitiativePayment__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>InitiativePayments</relationshipLabel>
    <relationshipName>InitiativePayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PA{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount (ex GST)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This will display on the remittance advice that is sent with the payment to the Organisation.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sent for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The Name and Description of the Requirement are displayed in the Investment Schedule.  These should clearly describe what is required.</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#FF9900</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#009900</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FF0000</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#DDDDDD</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Variation</fullName>
                <color>#BBBBBB</color>
                <label>Variation</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <color>#666666</color>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#333333</color>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequirementInitiative__c/RequirementInitiative__c.object-meta.xml
<CustomObject>
    <description>This object is created specifically for NintexDoc generation. This will hold data to overcome challenges faced with OOTB approach.
The records in this object will be created through flow.</description>
    <label>RequirementInitiative</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>RequirementInitiative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RequirementInitiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequirementInitiative__c/fields/Due_Date_Combine__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_Combine__c</fullName>
    <label>Due Date Combine</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RequirementInitiative__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To hold initiative Id</description>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>RequirementInitiatives</relationshipLabel>
    <relationshipName>RequirementInitiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequirementInitiative__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requirement</label>
    <referenceTo>Requirement__c</referenceTo>
    <relationshipLabel>RequirementInitiatives</relationshipLabel>
    <relationshipName>RequirementRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequirementInitiative__c/fields/Requirement_Name__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Name__c</fullName>
    <label>Requirement Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RequirementInitiative__c/fields/Status_Combine__c.field-meta.xml
<CustomField>
    <fullName>Status_Combine__c</fullName>
    <label>Status Combine</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DedupeRequirements.cls
public class DedupeRequirements {
 /*   
    @InvocableMethod(label = 'SendRequirementCollection GetDedupedRequirements'
                     description = 'returns Deduped Requirement Collection.')
    
    
    public static List < List < RequirementInitiative__c >> getDedupedRequirements(List<List< RequirementInitiative__c >> InitiativeRequirements) {
        
        //System.debug('InitiativeRequirements###'+InitiativeRequirements.size())
        List<InitiativePayment__c> listtoaddIR=new List<InitiativePayment__c>();
        List<AggregateResult> paymentList = new List<AggregateResult>();
        List<Id> initiativeIdForPayment=new List<Id>();
        List < List < RequirementInitiative__c >> deduped = new List < List <RequirementInitiative__c>> ();
        List < RequirementInitiative__c > dedupedRequirements = new List < RequirementInitiative__c > ();
        Date MyDate,theDate;
        String myString;
        
        //checking for duplicates
        List<RequirementInitiative__c> rilist=new List<RequirementInitiative__c>();//new
        Map<Id,RequirementInitiative__c> maprilist=new Map<Id,RequirementInitiative__c>();//new
        List<InitiativePayment__c> iplist=new List<InitiativePayment__c>();
        
        Set<Id> initiativeIds=new Set<Id>();
        for (List <RequirementInitiative__c> ReqObj: InitiativeRequirements) {
            for (RequirementInitiative__c innerReq: ReqObj) {
                
                initiativeIds.add(innerReq.Initiative__c);
            }
            
        }
        //Changes by Prajwal 6/10/2022
        iplist=[select Id, Initiative__c from InitiativePayment__c where Initiative__c IN: initiativeIds];//new
        rilist=[select Id, Initiative__c from RequirementInitiative__c where Initiative__c IN: initiativeIds];//new
        
        if(!rilist.isEmpty())
        {
            System.debug('**rilist :- '+rilist );
            delete rilist;
        }
        
        
        // Foreach iterate over the collection
        for (List <RequirementInitiative__c> ReqObj: InitiativeRequirements) {
            
            //System.debug('ReqObj###'+ReqObj.size());
            
            Map < String, RequirementInitiative__c > names = new Map < String, RequirementInitiative__c > ();
            Id checkReqId;
            //List<String> names=new List<String>();
            
            System.debug('Mapril****'+maprilist);
            System.debug('NamesForNull****'+names);
            System.debug('ReqObj****'+ReqObj);
            for (RequirementInitiative__c innerReq: ReqObj) {
                
                system.debug('innerReq###' + innerReq);
                //System.debug('dedupedRequirements###'+dedupedRequirements);
                System.debug('NAmes****'+names);
                
                if (names.isEmpty()) {
                    
                    names.put(String.ValueOf(innerReq.Requirement_Name__c), innerReq);
                    MyDate=names.get(innerReq.Requirement_Name__c).Due_Date__c;
                    names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(DateTime.newInstance(MyDate.year(),MyDate.month(),MyDate.day()).format('d MMM yyyy'));
                    names.get(innerReq.Requirement_Name__c).Status_Combine__c=names.get(innerReq.Requirement_Name__c).Status__c;
                    
                } else if (!names.containsKey(innerReq.Requirement_Name__c)) {
                    
                    names.put(String.ValueOf(innerReq.Requirement_Name__c), innerReq);
                    
                    MyDate=names.get(innerReq.Requirement_Name__c).Due_Date__c;
                    
                    //names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(names.get(innerReq.Requirement_Name__c).Due_Date__c);
                    names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(DateTime.newInstance(MyDate.year(),MyDate.month(),MyDate.day()).format('d MMM yyyy'));
                    names.get(innerReq.Requirement_Name__c).Status_Combine__c=names.get(innerReq.Requirement_Name__c).Status__c;
                    
                } else if (names.containsKey(innerReq.Requirement_Name__c)) {
                    
                    checkReqId = names.get(innerReq.Requirement_Name__c).Requirement__c;
                    
                    
                    if (innerReq.Requirement__c != checkReqId) {
                        
                        MyDate=innerReq.Due_Date__c;
                        //names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(names.get(innerReq.Requirement_Name__c).Due_Date__c);
                        names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c+'\n'+String.valueOf(DateTime.newInstance(MyDate.year(),MyDate.month(),MyDate.day()).format('d MMM yyyy')); 
                       names.get(innerReq.Requirement_Name__c).Status_Combine__c=names.get(innerReq.Requirement_Name__c).Status_Combine__c+'\n'+innerReq.Status__c;
                        
                        innerReq.Requirement_Name__c = null;
                        innerReq.Description__c = null;
                        //dedupedRequirements.add(innerReq);
                    }
                    // names.put(String.ValueOf(innerReq.Requirement_Name__c), innerReq);
                    
                }                    
                //*********************** Code for RequirementPayment *****************************
                
                initiativeIdForPayment.add(innerReq.Initiative__c);
                
                
            }
            
            dedupedRequirements.addall(names.values());
            deduped.add(dedupedRequirements);
            
            //code for inserting in InitiativePayment object---IPC Start
            
            
            
            if(!rilist.isEmpty())
            {
                System.debug('**iplist :- '+iplist );
                delete iplist;
            }
        }
            
            paymentList = [select Initiative__c, 
                           Financial_Year__c, 
                           sum(Amount__c) Amt 
                           from Payment__c 
                           where Initiative__c IN: initiativeIdForPayment 
                           Group By Initiative__c,Financial_Year__c ];
            System.debug('List Values ******'+ paymentList);
            Map<Id,AggregateResult> paymap=new Map<Id,AggregateResult>();
            
            
            
            System.debug('Map Values ******'+ paymap);
            for(AggregateResult a:paymentList)
            {
                listtoaddIR.add(
                    new InitiativePayment__c(
                        Initiative__c=(ID)a.get('Initiative__c'),
                        Financial_Year__c=(String)a.get('Financial_Year__c'),
                        Amount__c=(decimal)a.get('Amt')
                    )
                );
            }
            
            
            insert listtoaddIR;
            //IPC End
        
        return deduped;
        
    }
  */  
    @InvocableMethod(label = 'SendRequirementCollection GetDedupedRequirements'
                     description = 'returns Deduped Requirement Collection.')
    
    
    public static List < List < RequirementInitiative__c >> getDedupedRequirements(List<List< RequirementInitiative__c >> InitiativeRequirements) {
        
        //System.debug('InitiativeRequirements###'+InitiativeRequirements.size())
        List<InitiativePayment__c> listtoaddIR=new List<InitiativePayment__c>();
        List<AggregateResult> paymentList = new List<AggregateResult>();
        Map<Id,List<RequirementInitiative__c>> invVsReqList = new Map<Id,List<RequirementInitiative__c>>();
        List<Id> initiativeIdForPayment=new List<Id>();
        List < List < RequirementInitiative__c >> deduped = new List < List <RequirementInitiative__c>> ();
        List < RequirementInitiative__c > dedupedRequirements = new List < RequirementInitiative__c > ();
        Date MyDate,theDate;
        String myString;
        
        //checking for duplicates
        List<RequirementInitiative__c> rilist=new List<RequirementInitiative__c>();//new
        Map<Id,RequirementInitiative__c> maprilist=new Map<Id,RequirementInitiative__c>();//new
        List<InitiativePayment__c> iplist=new List<InitiativePayment__c>();
        
        Set<Id> initiativeIds=new Set<Id>();
        for (List <RequirementInitiative__c> ReqObj: InitiativeRequirements) {
            for (RequirementInitiative__c innerReq: ReqObj) {
                if(!invVsReqList.containsKey(innerReq.Initiative__c)){
                    invVsReqList.put(innerReq.Initiative__c,new List<RequirementInitiative__c>{innerReq});
                }else{
                    invVsReqList.get(innerReq.Initiative__c).add(innerReq);
                }
                initiativeIds.add(innerReq.Initiative__c);
            }
            
        }
        //Changes by Prajwal 6/10/2022
        iplist=[select Id, Initiative__c from InitiativePayment__c where Initiative__c IN: initiativeIds];//new
        rilist=[select Id, Initiative__c from RequirementInitiative__c where Initiative__c IN: initiativeIds];//new
        
        if(!rilist.isEmpty())
        {
            System.debug('**rilist :- '+rilist );
            delete rilist;
        }
        if(!rilist.isEmpty())
        {
            System.debug('**iplist :- '+iplist );
            delete iplist;
        }
        
System.debug('invVsReqList****'+invVsReqList);
        // Foreach iterate over the collection
        for (Id i: invVsReqList.KeySet()) {
            
            //System.debug('ReqObj###'+ReqObj.size());
            
            Id checkReqId;
            //List<String> names=new List<String>();
                    Map < String, RequirementInitiative__c > names = new Map < String, RequirementInitiative__c > ();
            
            System.debug('Mapril****'+maprilist);
            System.debug('NamesForNull****'+names);
            //System.debug('ReqObj****'+ReqObj);
            for (RequirementInitiative__c innerReq: invVsReqList.get(i)) {
                
                system.debug('innerReq###' + innerReq);
                //System.debug('dedupedRequirements###'+dedupedRequirements);
                System.debug('NAmes****'+names);
                
                if (names.isEmpty()) {
                    
                    names.put(String.ValueOf(innerReq.Requirement_Name__c), innerReq);
                    MyDate=names.get(innerReq.Requirement_Name__c).Due_Date__c;
                    names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(DateTime.newInstance(MyDate.year(),MyDate.month(),MyDate.day()).format('d MMM yyyy'));
                    names.get(innerReq.Requirement_Name__c).Status_Combine__c=names.get(innerReq.Requirement_Name__c).Status__c;
                    
                } else if (!names.containsKey(innerReq.Requirement_Name__c)) {
                    
                    names.put(String.ValueOf(innerReq.Requirement_Name__c), innerReq);
                    
                    MyDate=names.get(innerReq.Requirement_Name__c).Due_Date__c;
                    
                    //names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(names.get(innerReq.Requirement_Name__c).Due_Date__c);
                    names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(DateTime.newInstance(MyDate.year(),MyDate.month(),MyDate.day()).format('d MMM yyyy'));
                    names.get(innerReq.Requirement_Name__c).Status_Combine__c=names.get(innerReq.Requirement_Name__c).Status__c;
                    
                } else if (names.containsKey(innerReq.Requirement_Name__c)) {
                    
                    checkReqId = names.get(innerReq.Requirement_Name__c).Requirement__c;
                    
                    
                    if (innerReq.Requirement__c != checkReqId) {
                        
                        MyDate=innerReq.Due_Date__c;
                        //names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=String.valueOf(names.get(innerReq.Requirement_Name__c).Due_Date__c);
                        names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c=names.get(innerReq.Requirement_Name__c).Due_Date_Combine__c+'\n'+String.valueOf(DateTime.newInstance(MyDate.year(),MyDate.month(),MyDate.day()).format('d MMM yyyy')); 
                       names.get(innerReq.Requirement_Name__c).Status_Combine__c=names.get(innerReq.Requirement_Name__c).Status_Combine__c+'\n'+innerReq.Status__c;
                        
                        innerReq.Requirement_Name__c = null;
                        innerReq.Description__c = null;
                        //dedupedRequirements.add(innerReq);
                    }
                    // names.put(String.ValueOf(innerReq.Requirement_Name__c), innerReq);
                    
                }                    
                //*********************** Code for RequirementPayment *****************************
                
                initiativeIdForPayment.add(innerReq.Initiative__c);
                
                
            }
            
            dedupedRequirements.addall(names.values());   
            //code for inserting in InitiativePayment object---IPC Start
        }
        
        if(dedupedRequirements.size()>0){
            deduped.add(dedupedRequirements);
        }
            paymentList = [select Initiative__c, 
                           Financial_Year__c, 
                           sum(Amount__c) Amt 
                           from Payment__c 
                           where Initiative__c IN: initiativeIdForPayment 
                           Group By Initiative__c,Financial_Year__c ];
            System.debug('List Values ******'+ paymentList);
            Map<Id,AggregateResult> paymap=new Map<Id,AggregateResult>();
            
            
            
            System.debug('Map Values ******'+ paymap);
            for(AggregateResult a:paymentList)
            {
                listtoaddIR.add(
                    new InitiativePayment__c(
                        Initiative__c=(ID)a.get('Initiative__c'),
                        Financial_Year__c=(String)a.get('Financial_Year__c'),
                        Amount__c=(decimal)a.get('Amt')
                    )
                );
            }
            
            
            insert listtoaddIR;
            //IPC End
        
        return deduped;
        
    }
    
    
}