force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Baseline_Date__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Date__c</fullName>
    <label>Baseline Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Baseline_Text__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Text__c</fullName>
    <label>Baseline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Partner__c</field>
            <operation>equals</operation>
            <valueField>Initiative__c.Partner__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Result_Achieved_Icon__c.field-meta.xml
<CustomField>
    <fullName>Result_Achieved_Icon__c</fullName>
    <formula>IF(ISBLANK(TEXT( Status__c )),null, 

IMAGE( 

CASE(TEXT( Status__c ), 

&quot;Met&quot;, $Setup.Icons__c.Green__c, 
&quot;Mostly Met&quot;,$Setup.Icons__c.Yellow__c, 
&quot;Partially Met&quot;,$Setup.Icons__c.Orange__c, 
&quot;Not Met&quot;,$Setup.Icons__c.Red__c,
&quot;Pending&quot;,$Setup.Icons__c.Grey__c,
&quot;Removed&quot;,$Setup.Icons__c.Orange__c,
&quot;Variation&quot;,$Setup.Icons__c.Orange__c,
&quot;&quot;),&quot;&quot;))</formula>
    <label>Result Achieved</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Result_Date__c.field-meta.xml
<CustomField>
    <fullName>Result_Date__c</fullName>
    <label>Result Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Result_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Result_Rich_Text__c</fullName>
    <label>Result</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Update the Status when you receive results against this Measure.  This will generally be when you record the Result and Result Date.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
                <default>true</default>
                <label>Removed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Partially Met</fullName>
            </value>
            <value>
                <fullName>Not Met</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Target_Text__c.field-meta.xml
<CustomField>
    <fullName>Target_Text__c</fullName>
    <label>Target</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Initiative_MeasureController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of Initiative_Measure Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 12-12-2016       | Vivian Charlie   | 1. Created class to implement functionality of Initiative_Measure Page
   ==========================================================================================================================
*/
public class Initiative_MeasureController{

    public Initiative_MeasureController(ApexPages.StandardController controller) {

    }
 
    public  String initID {get; set;}
    public List<Measure__c> measureList{get;set;}
    
    public ApexPages.StandardSetController stdSetController 
    {                                
        get {
        list<user> lstUsr = [SELECT Id,
                                    ContactID,
                                    contact.accountId 
                             FROM User 
                             WHERE id=: UserInfo.getUserId()];
        if(lstUsr != null && !lstUsr.isEmpty()) {
        measureList = new List<Measure__c>();
        initID =  ApexPages.currentPage().getParameters().get('id');
            measureList =  [SELECT Name,
                                   Baseline_Text__c,
                                   Baseline_Date__c,
                                   Target_Text__c,
                                   Target_Date__c,
                                   Result_Rich_Text__c,
                                   Result_Date__c,
                                   Status__c,
                                   Result_Achieved_Icon__c,
                                   Partner__c
                            FROM Measure__c
                            WHERE Initiative__c =: initID AND Reporting_Type__c = 'Written' AND Partner__c=:lstUsr[0].contact.accountId ORDER BY Target_Date__c];
        }
        system.debug('measureList'+measureList); 
            if(stdSetController == null) {
                stdSetController = new ApexPages.StandardSetController(measureList);
                stdSetController.setPageSize(5);
            }
            return stdSetController;
        }
        set;       
    }
    
    public List<Measure__c> getMeasures() {
        List<Measure__c> measures = new list<Measure__c>();
        measures = stdSetController.getRecords();
        system.debug('measures '+measures);
        return measures;
    }
    
    public Boolean hasNext1 {
        get {
            return stdSetController.getHasNext();
        }
        set;
    }

    public Boolean hasPrevious1 {
        get {
            return stdSetController.getHasPrevious();
        }
        set;
    }

    public void first1() {
        stdSetController.first();
    }

    public void last1() {
        stdSetController.last();
    }

    public void previous1() {
        stdSetController.previous();
    }

    public void next1() {
        stdSetController.next();
    }
}