force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Investment_Schedule_Variation__c.field-meta.xml
<CustomField>
    <fullName>Investment_Schedule_Variation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Schedule Variation</label>
    <referenceTo>Variation__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Pending_Measures__c.field-meta.xml
<CustomField>
    <fullName>Pending_Measures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pending Measures</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/RUL_Incomplete_Measures__c.field-meta.xml
<CustomField>
    <fullName>RUL_Incomplete_Measures__c</fullName>
    <label>Incomplete Measures</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/RUL_Total_Measures__c.field-meta.xml
<CustomField>
    <fullName>RUL_Total_Measures__c</fullName>
    <label>Total Measures</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Total_cancelled_Measures_for_Initiative__c.field-meta.xml
<CustomField>
    <fullName>Total_cancelled_Measures_for_Initiative__c</fullName>
    <label>Total cancelled Measures for Initiative</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Baseline_Currency__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Currency__c</fullName>
    <label>Baseline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Baseline_Date__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Date__c</fullName>
    <label>Baseline Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Baseline_Number__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Number__c</fullName>
    <label>Baseline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Baseline_Percent__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Percent__c</fullName>
    <label>Baseline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Baseline_Text__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Text__c</fullName>
    <label>Baseline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The Measure Name and Description are displayed in the Investment Schedule.</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Partner__c</field>
            <operation>equals</operation>
            <valueField>Initiative__c.Partner__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Old_Status__c.field-meta.xml
<CustomField>
    <fullName>Old_Status__c</fullName>
    <label>Old Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Outcomes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outcome</label>
    <referenceTo>Outcome__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Outcome_Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Result_Currency__c.field-meta.xml
<CustomField>
    <fullName>Result_Currency__c</fullName>
    <label>Result</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Result_Date__c.field-meta.xml
<CustomField>
    <fullName>Result_Date__c</fullName>
    <label>Result Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Result_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Result_Rich_Text__c</fullName>
    <label>Result</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/RUL_Old_RecordType_Id__c.field-meta.xml
<CustomField>
    <fullName>RUL_Old_RecordType_Id__c</fullName>
    <description>This field is used for storing the record type ID except the read only record type id.</description>
    <label>Old RecordType Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Update the Status when you receive results against this Measure.  This will generally be when you record the Result and Result Date.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
                <default>true</default>
                <label>Removed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Partially Met</fullName>
            </value>
            <value>
                <fullName>Not Met</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Target_Currency__c.field-meta.xml
<CustomField>
    <fullName>Target_Currency__c</fullName>
    <label>Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Target_Text__c.field-meta.xml
<CustomField>
    <fullName>Target_Text__c</fullName>
    <label>Target</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/recordTypes/Number.recordType-meta.xml
<RecordType>
    <fullName>Number</fullName>
    <active>true</active>
    <description>To represent numerical volume measurement of KPIs</description>
    <label>Number</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Currency_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Currency_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Currency Read Only</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Number_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Number_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Number Read only</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Percent_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Percent_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Percent Read Only</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Text_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Text_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Text Read Only</label>
</RecordType>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variation__c/Variation__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule Variation</label>
    <nameField>
        <displayFormat>ISV-{00000}</displayFormat>
        <label>Investment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Schedule Variations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Variation__c/fields/Measures_Varied__c.field-meta.xml
<CustomField>
    <fullName>Measures_Varied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Measures Varied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the current Status of the variation</description>
    <formula>if(ISBLANK(Variation_Completed_Date__c), &quot;Draft&quot;, &quot;Completed&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Variation Status changes to Completed once the Varied Investment Schedule has been approved</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MeasureTriggerhandler.cls
/*------------------------------------------------------------
Author:         Jack Tan
Company:        Davanti Consulting
Description:    Handler of trigger TrgMeasure on Measure__c
Test Class:     TestMeasureTriggerhandler

History
03-08-2017      JTan    Created
24-05-2018      ESPL    Modified as per checkVariationConditionVariation functionality
03-12-2018      ESPL    As per SNIS-94 to update Pending Measure Count
------------------------------------------------------------*/

public class MeasureTriggerhandler {
    
    /**************************************************
    Purpose : Pass set of Initiative__c.Id to method rollupMeasuresOnInitiative
    Params  : List<Measure__c>
    *****************************************************/
    public static void updateInitiative(List<Measure__c> measureList) {
                system.debug('Inside MeasureTriggerhandler updateInitiative() method');

        Set<Id> initiativeIdSet = new Set<Id>();
        
        //RUL for all incomplete measures
        Set<Id> relatedInitiatives = new Set<Id>();
        //RUL for all cancelled measures
        Set<Id> relatedCancelledInitiatives = new Set<Id>();
        //RUL for count of measures linked
        Set<Id> relatedInit = new Set<Id>();
        
        for(Measure__c measure : measureList){
            if(measure.Initiative__c != null && measure.Status__c == 'Pending'){
                initiativeIdSet.add(measure.Initiative__c);
            }
            //Variation related changes
            if(measure.Initiative__c != null && measure.Status__c != 'Met'){
                relatedInitiatives.add(measure.Initiative__c);
            }
            //Variation related changes
            if(measure.Initiative__c != null && measure.Status__c == 'Cancelled'){
                relatedCancelledInitiatives.add(measure.Initiative__c);
            }
            if(measure.Initiative__c != null ){
            	relatedInit.add(measure.Initiative__c);
            }
        }
        if(!relatedInit.isEmpty()){
        	rollupMeasuresOnInitiative(initiativeIdSet,relatedInitiatives,relatedCancelledInitiatives);
        }
        
    }
    
    /**************************************************
    Purpose : Pass set of Initiative__c.Id to method rollupMeasuresOnInitiative
    Params  : Map<Id, Measure__c>, List<Measure__c>
    *****************************************************/
    public static void updateInitiative(Map<Id, Measure__c> oldMap, List<Measure__c> measureList) {
        system.debug('Inside MeasureTriggerhandler updateInitiative() method');

        if(Limits.getCpuTime() < Integer.valueOf(Label.Cpu_Time_Limit)){
	        Set<Id> initiativeIdSet = new Set<Id>();
	        
	         //RUL for all incomplete measures
	         Set<Id> relatedInitiatives = new Set<Id>();
	         
	         //RUL for all cancelled measures
        	Set<Id> relatedInitiativesMet = new Set<Id>();
	         //RUL for all cancelled measures
        	Set<Id> relatedCancelledInitiatives = new Set<Id>();
	        //RUL for count of measures linked
       		Set<Id> relatedInit = new Set<Id>();
        
	        for(Measure__c measure : measureList) {
	            if((measure.Status__c != oldMap.get(measure.Id).Status__c ||
	               measure.Initiative__c != oldMap.get(measure.Id).Initiative__c) ){
                       //Update by RUL on 03/12/2018 to update Pending Measure count on change of status from Measure to any other
	                   if(measure.Initiative__c != null && (measure.Status__c != 'Pending' || oldMap.get(measure.Id).Status__c == 'Pending'))
	                       initiativeIdSet.add(measure.Initiative__c);
	                   if(oldMap.get(measure.Id).Initiative__c != null && (measure.Status__c == 'Pending' || oldMap.get(measure.Id).Status__c != 'Pending'))
	                       initiativeIdSet.add(oldMap.get(measure.Id).Initiative__c);
	            }
	            if(measure.Initiative__c != null && measure.Status__c != 'Met' ){
	                relatedInitiatives.add(measure.Initiative__c);
	            }
	            if(measure.Initiative__c != null && measure.Status__c == 'Met'){
	                relatedInitiativesMet.add(measure.Initiative__c);
	            }
	            if(measure.Initiative__c != null && measure.Status__c == 'Cancelled'){
                	relatedCancelledInitiatives.add(measure.Initiative__c);
            	}
            	
	        }
	       if(!initiativeIdSet.isEmpty() || !relatedInitiatives.isEmpty() || !relatedCancelledInitiatives.isEmpty()){
				rollupMeasuresOnInitiative(initiativeIdSet,relatedInitiatives,relatedCancelledInitiatives);
	        }
	        if(!relatedInitiativesMet.isEmpty()){
	            AggregateResult[] aggregateResults = [SELECT COUNT(Id) CNT, Initiative__c INIT FROM Measure__c
	                                              WHERE Initiative__c IN :relatedInitiativesMet AND Status__c = 'Met' GROUP BY Initiative__c];
	             List<Initiative__c> initiativeToUpdate = new List<Initiative__c>();
	             for(AggregateResult ar : aggregateResults) {
	                initiativeToUpdate.add(
	                    new Initiative__c(
	                        Id = (Id) ar.get('INIT'),
	                        RUL_Incomplete_Measures__c = 0
	                    )
	                );
	             }
	             if(!initiativeToUpdate.isEmpty()){
	             	if(Limits.getCpuTime() < Integer.valueOf(Label.Cpu_Time_Limit)){
	             		update initiativeToUpdate;
	             	}
	             }
	        }
        }
    }

    /**************************************************
    Purpose : Count Pending Measure__c records and update Initiative__c.Pending_Measures__c
    Params  : Set<Id>
    *****************************************************/
    public static void rollupMeasuresOnInitiative(Set<Id> initiativeIdSet, Set<Id> relatedInitiatives, Set<Id> relatedCancelledInitiatives) {
                        system.debug('Inside MeasureTriggerhandler rollupMeasuresOnInitiative() method');

		if(Limits.getCpuTime() < Integer.valueOf(Label.Cpu_Time_Limit)){
	        //system.debug('@--MeasureTriggerhandler CPU Limits >>>>>>>>>>> '+Limits.getCpuTime());
	
	        List<Initiative__c> initiativeToUpdate = new List<Initiative__c>();
	
	         AggregateResult[] aggregateResults = new List<AggregateResult>();
	        if(!initiativeIdSet.isEmpty()){
	            aggregateResults = [SELECT COUNT(Id) CNT, Initiative__c INIT FROM Measure__c
	                                              WHERE Initiative__c IN :initiativeIdSet AND Status__c = 'Pending' GROUP BY Initiative__c];
	        	system.debug('Aggregate Result of Pending -----------------------'+aggregateResults.size());
	        }
	
	        AggregateResult[] aggregateResults1 = new List<AggregateResult>();
	        if(!relatedInitiatives.isEmpty()){
	            aggregateResults1 = [SELECT COUNT(Id) CNT, Initiative__c INIT FROM Measure__c
	                                              WHERE Initiative__c IN :relatedInitiatives AND Status__c != 'Met' GROUP BY Initiative__c];
	
	            //system.debug('Aggregate Result of not Met -----------------------'+aggregateResults1);
	        }
	        
	        AggregateResult[] aggregateResults2 = new List<AggregateResult>();
	        if(!relatedCancelledInitiatives.isEmpty()){
	            aggregateResults2 = [SELECT COUNT(Id) CNT, Initiative__c INIT FROM Measure__c
	                                              WHERE Initiative__c IN :relatedCancelledInitiatives AND Status__c = 'Cancelled' GROUP BY Initiative__c];
	
	            //system.debug('Aggregate Result of Cancelled -----------------------'+aggregateResults2);
	        }
	        
	        AggregateResult[] aggregateResults3 = new List<AggregateResult>();
	        if(!relatedCancelledInitiatives.isEmpty()){
	            aggregateResults3 = [SELECT COUNT(Id) CNT, Initiative__c INIT FROM Measure__c
	                                              WHERE Initiative__c != null GROUP BY Initiative__c];
	
	            //system.debug('Aggregate Result of Measures -----------------------'+aggregateResults3);
	        }
	
	        Map<Id,Initiative__c> initiativeToUpdateIdAndRecord = new Map<Id,Initiative__c>();
            if(aggregateResults.size() > 0){ //Added by RUL on 03/12/2018 to check the Pending Measure count is greater than o 
                for(AggregateResult ar : aggregateResults) {
	            initiativeToUpdateIdAndRecord.put((Id) ar.get('INIT'),new Initiative__c(
	                    Id = (Id) ar.get('INIT'),
	                    Pending_Measures__c = (Integer) ar.get('CNT')
                ));}
            }
            //Updated by RUL on 03/12/2018 to update the Pending Measure count on Initiative
            else{
                    for(id initid :initiativeIdSet ){
                     initiativeToUpdateIdAndRecord.put(initid,new Initiative__c(
	                    Id = initid,
	                    Pending_Measures__c = 0  ));  
                }
                                                
                }
            
            for(AggregateResult ar : aggregateResults3) {
	            initiativeToUpdateIdAndRecord.put((Id) ar.get('INIT'),new Initiative__c(
	                    Id = (Id) ar.get('INIT'),
	                    RUL_Total_Measures__c = (Integer) ar.get('CNT')
	                ));
	           
	        }
	        
	        for(AggregateResult ar : aggregateResults1) {
	            Id key = (Id) ar.get('INIT');
	            if(initiativeToUpdateIdAndRecord.containsKey(key)){
	                Initiative__c newInitiative = initiativeToUpdateIdAndRecord.get(key);
	                newInitiative.RUL_Incomplete_Measures__c = (Integer) ar.get('CNT');
	                initiativeToUpdateIdAndRecord.put(key,newInitiative);
	            }else{
	                Initiative__c newInitiative = new Initiative__c(
	                    Id = (Id) ar.get('INIT'),
	                    RUL_Incomplete_Measures__c = (Integer) ar.get('CNT')
	                );
	                initiativeToUpdateIdAndRecord.put(key,newInitiative);
	            }
	        }
	        for(AggregateResult ar : aggregateResults2) {
	            Id key = (Id) ar.get('INIT');
	            if(initiativeToUpdateIdAndRecord.containsKey(key)){
	                Initiative__c newInitiative = initiativeToUpdateIdAndRecord.get(key);
	                newInitiative.Total_cancelled_Measures_for_Initiative__c = (Integer) ar.get('CNT');
	                initiativeToUpdateIdAndRecord.put(key,newInitiative);
	            }else{
	                Initiative__c newInitiative = new Initiative__c(
	                    Id = (Id) ar.get('INIT'),
	                    Total_cancelled_Measures_for_Initiative__c = (Integer) ar.get('CNT')
	                );
	                initiativeToUpdateIdAndRecord.put(key,newInitiative);
	            }
	        }
	
	        for(String initiativeIds : initiativeToUpdateIdAndRecord.keySet()){
	            initiativeToUpdate.add(initiativeToUpdateIdAndRecord.get(initiativeIds));
	        }
	       if(!initiativeToUpdate.isEmpty()){
                system.debug('initiativeToUpdate============'+initiativeToUpdate);
	        	if(Limits.getCpuTime() < Integer.valueOf(Label.Cpu_Time_Limit)){
	        		update initiativeToUpdate;
                }
	        }
	        
		}
    }
    
    
    //Update checkbox at variation
    public static void updateVariation(Map<Id,Measure__c> newMeasures, Map<Id,Measure__c> oldMeasures){
                                system.debug('Inside MeasureTriggerhandler updateVariation() method');

    	Set<Id> initiative = new Set<Id>();
    	
    	for(String measureId :newMeasures.keySet()){
    		
    		if(((newMeasures.get(measureId).Name != oldMeasures.get(measureId).Name) || 
				(newMeasures.get(measureId).Partner__c != oldMeasures.get(measureId).Partner__c) || 
				(newMeasures.get(measureId).Initiative__c != oldMeasures.get(measureId).Initiative__c) || 
				(newMeasures.get(measureId).Reporting_Type__c != oldMeasures.get(measureId).Reporting_Type__c) || 
				(newMeasures.get(measureId).Baseline_Number__c != oldMeasures.get(measureId).Baseline_Number__c) || 
				(newMeasures.get(measureId).Result_Rich_Text__c != oldMeasures.get(measureId).Result_Rich_Text__c) || 
				(newMeasures.get(measureId).Target_Text__c != oldMeasures.get(measureId).Target_Text__c) || 
				(newMeasures.get(measureId).Target_Currency__c != oldMeasures.get(measureId).Target_Currency__c) || 
				(newMeasures.get(measureId).Baseline_Percent__c != oldMeasures.get(measureId).Baseline_Percent__c) || 
				(newMeasures.get(measureId).Status__c != oldMeasures.get(measureId).Status__c) || 
				(newMeasures.get(measureId).Outcomes__c != oldMeasures.get(measureId).Outcomes__c) || 
				(newMeasures.get(measureId).Description__c != oldMeasures.get(measureId).Description__c) || 
				(newMeasures.get(measureId).Instructions__c != oldMeasures.get(measureId).Instructions__c) || 
				(newMeasures.get(measureId).Baseline_Date__c != oldMeasures.get(measureId).Baseline_Date__c) || 
				(newMeasures.get(measureId).Target_Date__c != oldMeasures.get(measureId).Target_Date__c) || 
				(newMeasures.get(measureId).Result_Date__c != oldMeasures.get(measureId).Result_Date__c) || 
				(newMeasures.get(measureId).Baseline_Currency__c != oldMeasures.get(measureId).Baseline_Currency__c) || 
				(newMeasures.get(measureId).Result_Currency__c != oldMeasures.get(measureId).Result_Currency__c) || 
				(newMeasures.get(measureId).Baseline_Text__c != oldMeasures.get(measureId).Baseline_Text__c) || 
				(newMeasures.get(measureId).Target_Text__c != oldMeasures.get(measureId).Target_Text__c))){
				//system.debug('Measure changed --------------------');
				if(String.isNotBlank(newMeasures.get(measureId).Initiative__c)){
	    			initiative.add(newMeasures.get(measureId).Initiative__c);
	    		}
			}
    	}
    	system.debug('Changed Measures ------------------'+initiative);
    	
    	if(!initiative.isEmpty()){
    		List<Initiative__c> relatedInitiatives = [SELECT Id, 
    														 Investment_Schedule_Variation__c, 
    														 Investment_Schedule_Variation__r.Is_Active__c
    												  FROM   Initiative__c 
    												  WHERE  Id IN: initiative
    												 ];
    		system.debug('Related Initiatives ------------------'+relatedInitiatives);
            Map<ID,Initiative__c> mapInitiative = new Map<ID,Initiative__c>();
            mapInitiative.putall(mapInitiative);
    		if(mapInitiative.size()>0){
    			List<Variation__c> updateVariation = new List<Variation__c>();
    			for(Initiative__c objInitiative: mapInitiative.values()){
    				if(String.isNotBlank(objInitiative.Investment_Schedule_Variation__c)){
	    				if(objInitiative.Investment_Schedule_Variation__r.Is_Active__c){
	    					//update payment varied
	    					updateVariation.add(new Variation__c(
	    						Id = objInitiative.Investment_Schedule_Variation__c,
	    						Measures_Varied__c = true
	    					));
	    				}
    				}
    			}
    			system.debug('Variations to update -------------------'+updateVariation);
    			if(!updateVariation.isEmpty()){
    				update updateVariation;
    			}
    		}
    		
    	}
    }
    public static void updateOldRecordType(List<Measure__c> listMeasure){
       system.debug('Inside MeasureTriggerhandler updateOldRecordType() method');

        if(Limits.getCpuTime() < Integer.valueOf(Label.Cpu_Time_Limit)){
            //To have number of SOQL queries executed so far
            Set<String>setRecordTypes = new Set<String>{'RUL_Currency_Read_Only','RUL_Number_Read_Only','RUL_Percent_Read_Only','RUL_Text_Read_Only'};
            for(Measure__c objMeasure : listMeasure){
                //system.debug('objMeasure.RecordType.DeveloperName'+objMeasure.RecordType.DeveloperName);
                if(objMeasure.RecordTypeId != fetchRecordTypeId('RUL_Currency_Read_Only') 
                   && objMeasure.RecordTypeId != fetchRecordTypeId('RUL_Number_Read_Only')
                   && objMeasure.RecordTypeId != fetchRecordTypeId('RUL_Percent_Read_Only')
                   && objMeasure.RecordTypeId != fetchRecordTypeId('RUL_Text_Read_Only')){
                       objMeasure.RUL_Old_RecordType_Id__c = objMeasure.RecordTypeID;
                  }
                  if(!objMeasure.Status__c.containsIgnoreCase('Variation')){
                    objMeasure.Old_Status__c = objMeasure.Status__c;
                }
             }
        }
    }
     public static String fetchRecordTypeId (String recordTypeName) {
        system.debug('Inside MeasureTriggerhandler fetchRecordTypeId() method');

        String recordTypeId =  Schema.SObjectType.Measure__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();        
        return recordTypeId;
    }
}