force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The Name and Description of the Requirement are displayed in the Investment Schedule.  These should clearly describe what is required.</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Hold_Payments__c.field-meta.xml
<CustomField>
    <fullName>Hold_Payments__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If this requirement becomes overdue, it will automatically hold all payments for the associated Initiative that have a Payment due date after the Requirement due date.</inlineHelpText>
    <label>Hold Payments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement_Template__c/Requirement_Template__c.object-meta.xml
<CustomObject>
    <label>Requirement Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddRequirementExtension.cls
public with sharing class AddRequirementExtension {
	private String retUrl;
	private Id recTypeId;
	private Id accountId;
	private Id initiativeId;
	public List<RequirementWrapper> requirementList {get;set;}
	public List<Requirement_Template__c> requirementTemplateList {get{
		if(requirementTemplateList == null){
			requirementTemplateList = [Select Id, Name, Description__c From Requirement_Template__c Order By Name];
		}
		return requirementTemplateList;
	}set;}
	public AddRequirementExtension(ApexPages.StandardController controller) {
		requirementList = new List<RequirementWrapper>();
		List<RecordType> recordTypeList = new List<RecordType>([Select Id, Name From RecordType Where SObjectType='Requirement__c']);
		Map<String, RecordType> recordTypeMap = new Map<String, RecordType>();
		if(recordTypeList.size() > 0) {
			for(RecordType rt : recordTypeList) {
				recordTypeMap.put(rt.Name, rt);
			}
		}
		/*
		// Kahiwi Fixes - commented out code related to 'Organisation Requirement' record type
		if(ApexPages.currentPage().getParameters().get('accountId') != null) {
			accountId = ApexPages.currentPage().getParameters().get('accountId');
			recTypeId = recordTypeMap.get('Organisation Requirement').Id;
		}
		*/
		if(ApexPages.currentPage().getParameters().get('initiativeId') != null) {
			initiativeId = ApexPages.currentPage().getParameters().get('initiativeId');
			recTypeId = recordTypeMap.get('Initiative Requirement').Id;
		}
		if(ApexPages.currentPage().getParameters().get('retUrl') != null) {
			retUrl = ApexPages.currentPage().getParameters().get('retUrl');
		}
		if(requirementTemplateList.size() > 0) {
			for(Requirement_Template__c reqT : requirementTemplateList) {
				RequirementWrapper reqWrapper = new RequirementWrapper();
				reqWrapper.requirement.Name = reqT.Name;
				reqWrapper.requirement.Description__c = reqT.Description__c;
				reqWrapper.requirement.Due_Date__c = null;
				reqWrapper.requirement.Hold_Payments__c = null;
				reqWrapper.requirement.RecordTypeId = recTypeId;
				if(accountId != null)
					reqWrapper.requirement.Partner__c = accountId;
				if(initiativeId != null)
					reqWrapper.requirement.Initiative__c = initiativeId;	
				requirementList.add(reqWrapper);
			}				
		}
	}
	public PageReference saveButton() {
		PageReference pageRef = null;
		List<Requirement__c> requirementInsertList = new List<Requirement__c>();
		for(RequirementWrapper req : requirementList) {
			if(req.bSelected) {
				//validate row
				if(validate(req.requirement) == false) return pageRef;
				requirementInsertList.add(req.requirement);
			}
		}
		if(requirementInsertList.size() > 0) {
			//save the record
			Database.insert(requirementInsertList, false); system.debug('###: insert ');    
			if(retUrl != null) {
				pageRef = new PageReference(retUrl);
				return pageRef;
			} 
		}
		addPageMessage(ApexPages.severity.Error,'No rows selected.');
		return pageRef;
	}
	public PageReference cancelButton() {
		if(retUrl != null) {
			PageReference pageRef = new PageReference(retUrl);
			return pageRef;
		} else {
			return null;
		}
	}
    // VALIDATION
    public Boolean validate(Requirement__c req) {
        Boolean bReturnValue = true;
		if(req.Name == null) {
			addPageMessage(ApexPages.severity.Error,'Requirement Name is required');
			bReturnValue = false;
		}
		if(req.Description__c == '' || req.Description__c == null || req.Description__c == ' ') {
			addPageMessage(ApexPages.severity.Error,'Description is required');
			bReturnValue = false;
		}
		if(req.Due_Date__c == null) {
			addPageMessage(ApexPages.severity.Error, 'Due Date is required');
			bReturnValue = false;
		}
		if(req.Due_Date__c != null && req.Due_Date__c <= date.today()){
			addPageMessage(ApexPages.severity.Error, 'Due Date should be a future date');
			bReturnValue = false;
		}
		return bReturnValue;
    }
	
    // Add Page Messages
    public void addPageMessage(ApexPages.severity severity, Object objMessage) {
        ApexPages.Message pMessage = new ApexPages.Message(severity, String.valueOf(objMessage));
        ApexPages.addMessage(pMessage);
    }
    public void addPageMessage(Object objMessage) {
        addPageMessage(ApexPages.severity.INFO, objMessage);
    }       
	//Wrapper
	public class RequirementWrapper {
		public boolean bSelected {get;set;}
		public Requirement__c requirement {get;set;}
		public RequirementWrapper() {
			bSelected = false;
			requirement = new Requirement__c();
		}
	}
}