force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/RRD_Status__c.field-meta.xml
<CustomField>
    <fullName>RRD_Status__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>RRD Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#FF9900</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#009900</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FF0000</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#DDDDDD</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Variation</fullName>
                <color>#BBBBBB</color>
                <label>Variation</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <color>#666666</color>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#333333</color>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement_Reporting_Detail__c/Requirement_Reporting_Detail__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the Partner response for a list of questions.</description>
    <label>Requirement Reporting Detail</label>
    <nameField>
        <label>Requirement Reporting Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Reporting Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement_Reporting_Detail__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requirement</label>
    <referenceTo>Requirement__c</referenceTo>
    <relationshipLabel>Requirement Reporting Details</relationshipLabel>
    <relationshipName>Requirement_Reporting_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement_Reporting_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Being Reviewed</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>SME review underway</fullName>
            </value>
            <value>
                <fullName>SME review complete</fullName>
            </value>
            <value>
                <fullName>Review being finalised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchToUpdateRequirementRRDstatus.cls
global class BatchToUpdateRequirementRRDstatus implements Database.Batchable<sObject> {
    String query='select Id,Status__c,RRD_Status__c from Requirement__c';
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<Requirement__c> records){
        // process each batch of records
        List<Requirement_Reporting_Detail__c> rrdlist =[select Id,Requirement__c,Status__c from Requirement_Reporting_Detail__c where Requirement__c IN : records];
            Map<Id,String> reqvsrrdMap= New Map<Id,String>();
            for(Requirement_Reporting_Detail__c rrd:rrdlist)
            {
                reqvsrrdMap.put(rrd.Requirement__c,rrd.Status__c);
            }
            for(Requirement__c req : records){
            	if(!reqvsrrdMap.containsKey(req.Id))
                {
                    req.RRD_Status__c=req.Status__c;
                }
                else
                {
                    req.RRD_Status__c=reqvsrrdMap.get(req.Id);
                }
            }
        update records;
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }    
}