force-app/main/default/objects/Workforce_Numbers__c/Workforce_Numbers__c.object-meta.xml
<CustomObject>
    <label>Workforce Numbers</label>
    <nameField>
        <displayFormat>WN-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workforce Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workforce_Numbers__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Workforce_Category__r.End_Date__c</formula>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Workforce_Numbers__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Workforce_Category__r.Start_Date__c</formula>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Workforce_Numbers__c/fields/Workforce_Category__c.field-meta.xml
<CustomField>
    <fullName>Workforce_Category__c</fullName>
    <label>Name</label>
    <referenceTo>Workforce_Numbers_Category__c</referenceTo>
    <relationshipLabel>Workforce Numbers</relationshipLabel>
    <relationshipName>Workforce_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workforce_Numbers_Category__c/Workforce_Numbers_Category__c.object-meta.xml
<CustomObject>
    <label>Workforce Numbers Category</label>
    <nameField>
        <label>Workforce Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workforce Numbers Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workforce_Numbers_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coaching</fullName>
            </value>
            <value>
                <fullName>Officials</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workforce_Numbers_Category__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Workforce Numbers Category</relationshipLabel>
    <relationshipName>Workforce_Numbers_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Workforce_NumbersControllerTest.cls
@isTest
private class Workforce_NumbersControllerTest {
    private static testmethod void testSaveWorkNos() {
        list<Account> accList = RUL_Util.createAccounts();
        insert accList ;
        
        Workforce_Numbers_Category__c tempCat = new Workforce_Numbers_Category__c();
        tempCat.Organisation__c = accList[0].Id;
        tempCat.Category__c = 'Other';
        tempCat.End_Date__c = system.today();
        tempCat.Start_Date__c = system.today();
        insert tempCat;
        
        Workforce_Numbers__c tempWork = new Workforce_Numbers__c();
        tempWork.Workforce_Category__c = tempCat.Id;
        insert tempWork;
        
        PageReference newPageRef = Page.Workforce_Numbers;
        newPageRef.getParameters().put('Id',tempWork.Id);
        Test.setCurrentPage(newPageRef);
    
        Workforce_NumbersController newController = new Workforce_NumbersController();
        newController.save();
        newController.cancel();
        
        //System.assertEquals(1, [select count() from Workforce_Numbers__c WHERE Workforce_Category__c =: tempCat.id]);
    }
}