force-app/main/default/objects/Workforce_Numbers__c/Workforce_Numbers__c.object-meta.xml
<CustomObject>
    <label>Workforce Numbers</label>
    <nameField>
        <displayFormat>WN-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workforce Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workforce_Numbers__c/fields/Workforce_Category__c.field-meta.xml
<CustomField>
    <fullName>Workforce_Category__c</fullName>
    <label>Name</label>
    <referenceTo>Workforce_Numbers_Category__c</referenceTo>
    <relationshipLabel>Workforce Numbers</relationshipLabel>
    <relationshipName>Workforce_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Workforce_NumbersController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of Workforce_Numbers Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 30-11-2016       | Vivian Charlie   | 1. Created class to implement functionality of Workforce_Numbers Page
   ==========================================================================================================================
*/
public class Workforce_NumbersController{
    public Workforce_Numbers__c newWorkforceNo {get;set;}
    
    public Workforce_NumbersController(){
        Id parentId = ApexPages.currentPage().getParameters().get('id');
        newWorkforceNo  = new Workforce_Numbers__c();
        newWorkforceNo.Workforce_Category__c = parentId;
    }
    
    public PageReference save()
    {      
        try {
            upsert newWorkforceNo ;
        } catch(exception e) {
            ApexPages.addMessages(e);          
        }
        return new PageReference('/' + newWorkforceNo.id);
    }
    
    public Pagereference cancel(){
        PageReference newpage = new Pagereference('/' + newWorkforceNo.Workforce_Category__c);
        newpage.setRedirect(true);
        return newpage;
    }
}