force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>TWR Activities</label>
    <nameField>
        <label>Activity  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TWR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Diamension_By_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_By_Score__c</fullName>
    <label>By Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <isActive>false</isActive>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
                <isActive>false</isActive>
                <label>5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_For_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_For_Score__c</fullName>
    <label>For Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_InOn_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_InOn_Score__c</fullName>
    <label>InOn Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_Thorugh_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_Thorugh_Score__c</fullName>
    <label>Through Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_With_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_With_Score__c</fullName>
    <label>With Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/DiamensionBy_DescRichText__c.field-meta.xml
<CustomField>
    <fullName>DiamensionBy_DescRichText__c</fullName>
    <label>By Dimension</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/DiamensionFor_DescRichText__c.field-meta.xml
<CustomField>
    <fullName>DiamensionFor_DescRichText__c</fullName>
    <label>For Dimension</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/DiamensionInOn_DescRichText__c.field-meta.xml
<CustomField>
    <fullName>DiamensionInOn_DescRichText__c</fullName>
    <label>InOn Dimension</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/DiamensionThrough_DescRichText__c.field-meta.xml
<CustomField>
    <fullName>DiamensionThrough_DescRichText__c</fullName>
    <label>Through Dimension</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/DiamensionWith_DescRichText__c.field-meta.xml
<CustomField>
    <fullName>DiamensionWith_DescRichText__c</fullName>
    <label>With Dimension</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date For Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Is_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Is_Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/communitySportNz_URL__c/communitySportNz_URL__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>communitySportNz_URL</label>
</CustomObject>

force-app/main/default/objects/communitySportNz_URL__c/fields/communitySportNz_URLField__c.field-meta.xml
<CustomField>
    <fullName>communitySportNz_URLField__c</fullName>
    <label>communitySportNz_URLField</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/RULconfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RUL configurations</label>
</CustomObject>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_End_Year_Report__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_End_Year_Report__c</fullName>
    <label>Due Date For End Year Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activities</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_ActivityLandingVfPageController.cls
@isTest
public class Test_ActivityLandingVfPageController {
    static testMethod void Test_ActivityLandingVfPageController(){
        Profile p = [SELECT Id,Name FROM Profile WHERE Name='Disability Community (Partner)']; 
        User u = new User(FirstName='test',Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        
       RULconfigurations__c config= new RULconfigurations__c();
        config.Due_Date_For_End_Year_Report__c=system.today()+10;
        config.Due_Date_For_Planned_Activities__c=system.today()+10;
        config.Name='Change Request approval setting';
        insert config;
        
        communitySportNz_URL__c communityurl = new communitySportNz_URL__c();
        communityurl.Name='';
        communityurl.communitySportNz_URLField__c = '';
        insert communityurl;
        
        Activity__c act = new Activity__c();
        act.Name='test';
        act.Due_Date__c = config.Due_Date_For_End_Year_Report__c;
       act.Due_Date_For_Planned_Activities__c=config.Due_Date_For_Planned_Activities__c;
        act.DiamensionBy_DescRichText__c='testing Editor2';
        act.DiamensionFor_DescRichText__c='testing Editor2';
        act.DiamensionInOn_DescRichText__c='testing Editor2';
        act.DiamensionThrough_DescRichText__c='testing Editor2';
        act.DiamensionWith_DescRichText__c='testing Editor2';
        act.Diamension_By_Score__c='2';
        act.Diamension_For_Score__c='2';
        act.Diamension_InOn_Score__c='2';
        act.Diamension_Thorugh_Score__c='2';
        act.Diamension_With_Score__c='2';
        act.Is_Read_Only__c=true;
        insert act;
        
        PageReference pageRef = Page.QuillRichTextEditor;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',act.id);
        
        test.startTest();
        ActivityLandingVfPageController testActivityPlan = new ActivityLandingVfPageController();
        testActivityPlan.getScores();
        testActivityPlan.saveTextEditorData();
        ActivityLandingVfPageController.sendChangeNotificationToPartner();
       //testActivityPlan.insertImageAsFile();
        ActivityLandingVfPageController.Dimension();
        ActivityLandingVfPageController.gotoReadonlyMode();
       ActivityLandingVfPageController.setChangeRequest();
        ActivityLandingVfPageController alpc = new ActivityLandingVfPageController();
        alpc.refreshPage();
        test.stopTest();
        
    }
}