force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>TWR Activities</label>
    <nameField>
        <label>Activity  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TWR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date For Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/communitySportNz_URL__c/communitySportNz_URL__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>communitySportNz_URL</label>
</CustomObject>

force-app/main/default/objects/communitySportNz_URL__c/fields/communitySportNz_URLField__c.field-meta.xml
<CustomField>
    <fullName>communitySportNz_URLField__c</fullName>
    <label>communitySportNz_URLField</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/RULconfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RUL configurations</label>
</CustomObject>

force-app/main/default/objects/RULconfigurations__c/fields/Default_Change_request_Approval__c.field-meta.xml
<CustomField>
    <fullName>Default_Change_request_Approval__c</fullName>
    <label>Default Change request Approval</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_End_Year_Report__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_End_Year_Report__c</fullName>
    <label>Due Date For End Year Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activities</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_DueDateHandler.cls
@isTest
public class Test_DueDateHandler {
    static testmethod void Test_DueDateHandlerMethod(){
        
        RULconfigurations__c rulConfiguration = new RULconfigurations__c();
        rulConfiguration.Name='Change Request approval setting';
        rulConfiguration.Default_Change_request_Approval__c= '';
        rulConfiguration.Due_Date_For_End_Year_Report__c=system.today()+10;
        rulConfiguration.Due_Date_For_Planned_Activities__c=system.today()+10;
        insert rulConfiguration;
        
        Account acc = new Account(name='TestAcc');
        insert acc;
        
        Contact con= new Contact(LastName = 'TestCon',AccountId = acc.id);
        insert con; 
        
        Profile profiles = [SELECT Id,
                            Name
                            FROM Profile
                            WHERE Name = 'Disability Community (Partner)' limit 1];
        
        User communityUser = new User(FirstName = 'Community',
                                      LastName = 'User'+1,
                                      Alias = 'CU',
                                      Email = 'commTest@test.com',
                                      Username = Math.random() + '@test.com',
                                      CommunityNickname = 'cust6',
                                      ContactId = con.Id,
                                      EmailEncodingKey = 'UTF-8',
                                      TimeZoneSidKey = 'America/Los_Angeles',
                                      LocaleSidKey = 'en_US',
                                      LanguageLocaleKey = 'en_US',
                                      PortalRole = 'Manager',
                                      ProfileId = profiles.Id,
                                      IsActive = true);      
        insert communityUser;
        system.runAs(communityUser) {
            
            RULconfigurations__c  customsetting =[select id,Name,Default_Change_request_Approval__c from RULconfigurations__c where Name=:rulConfiguration.Name];
            List <Activity__c> actt1 = new List <Activity__c>();
            
            Activity__c actt = new Activity__c();
            actt.Name='Test Act';
            actt.Due_Date__c = rulConfiguration.Due_Date_For_End_Year_Report__c;
            actt.Due_Date_For_Planned_Activities__c=rulConfiguration.Due_Date_For_Planned_Activities__c;
            actt.Organisation__c=acc.Id;
            
            insert actt;
            actt1.add(actt);
            
            DueDateHandler.DueDateMethod(actt1);
        }
    }
    static testmethod void Test_DueDateHandlerCatch(){
        Profile p1 = [SELECT Id,Name FROM Profile WHERE Name='Disability Community (Partner)']; 
        User u1 = new User(FirstName='test',Alias = 'standt', Email='standarduser@testorg.com', 
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p1.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        communitySportNz_URL__c comm1 = new communitySportNz_URL__c();
        comm1.communitySportNz_URLField__c='';
        insert comm1;
        
        RULconfigurations__c rulConfiguration1 = new RULconfigurations__c();
        rulConfiguration1.Name='Change Request approval setting';
        rulConfiguration1.Default_Change_request_Approval__c= '';
        rulConfiguration1.Due_Date_For_End_Year_Report__c=system.today()+10;
        rulConfiguration1.Due_Date_For_Planned_Activities__c=system.today()+10;
        insert rulConfiguration1;
        RULconfigurations__c  customsetting1 =[select id,Name,Default_Change_request_Approval__c from RULconfigurations__c where Name=:rulConfiguration1.Name];

        Activity__c actt1 = new Activity__c();
        actt1.Name='Test Act';
        actt1.Due_Date__c = rulConfiguration1.Due_Date_For_End_Year_Report__c;
        actt1.Due_Date_For_Planned_Activities__c=rulConfiguration1.Due_Date_For_Planned_Activities__c;
        insert actt1;
    }   
}