force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>TWR Activities</label>
    <nameField>
        <label>Activity  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TWR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/RULconfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RUL configurations</label>
</CustomObject>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_End_Year_Report__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_End_Year_Report__c</fullName>
    <label>Due Date For End Year Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activities</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/googleAddressAutoFillTest.cls
@isTest
public class googleAddressAutoFillTest {

   @isTest
    public static void getPlaceDetailsTest() {
        Test.setMock(HttpCalloutMock.class, new googleAddressAutoFillMock());
        googleAddressAutofill.getPlaceDetails('001');
    }
    
    @istest
    public static void getSuggestionsTest() {
        Test.setMock(HttpCalloutMock.class, new googleAddressAutoFillMock());
        googleAddressAutofill.getSuggestions('abc');
    }
    
    @istest
    public static void getAddressTest() {
        RULconfigurations__c rulObj = new RULconfigurations__c();
        rulObj.Name = 'Test';
        rulObj.Due_Date_For_End_Year_Report__c = Date.today()+8;
        rulObj.Due_Date_For_Planned_Activities__c = Date.today()+10;
        System.debug('rulObj###'+rulObj);
        insert rulObj;
        Activity__c activityObj = new Activity__c();
        activityObj.Name = 'TEST';
        insert activityObj;
        googleAddressAutofill.getAddress(activityObj.Id, 'street', 'city', 'state', 'country', '662', '', '');
    }
    
    @istest
    public static void opportunityTest() {
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'TEST';
        oppObj.StageName = 'Prospecting';
        oppObj.CloseDate = Date.today();
        insert oppObj;
        googleAddressAutofill.getOppStage(oppObj.Id);
    }
}