force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>TWR Activities</label>
    <nameField>
        <label>Activity  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TWR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Change_Request_Reason__c.field-meta.xml
<CustomField>
    <fullName>Change_Request_Reason__c</fullName>
    <label>Change Request Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Is_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Is_Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/requestForChangeRequest__c.field-meta.xml
<CustomField>
    <fullName>requestForChangeRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request For Change Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/communitySportNz_URL_ForPartnerUser__c/communitySportNz_URL_ForPartnerUser__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>communitySportNz_URL_ForPartnerUser</label>
</CustomObject>

force-app/main/default/objects/communitySportNz_URL_ForPartnerUser__c/fields/URL_ForPartnerUser__c.field-meta.xml
<CustomField>
    <fullName>URL_ForPartnerUser__c</fullName>
    <label>URL_ForPartnerUser</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/RULconfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RUL configurations</label>
</CustomObject>

force-app/main/default/objects/RULconfigurations__c/fields/Default_Change_request_Approval__c.field-meta.xml
<CustomField>
    <fullName>Default_Change_request_Approval__c</fullName>
    <label>Default Change request Approval</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/Test_VfForApprovalController.cls
@isTest
public class Test_VfForApprovalController {
    static testmethod void Test_VfForApprovalController(){
        Profile p = [SELECT Id,Name FROM Profile WHERE Name='Disability Community (Partner)']; 
        User u = new User(FirstName='test',Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        communitySportNz_URL_ForPartnerUser__c communityurl = new communitySportNz_URL_ForPartnerUser__c();
        communityurl.URL_ForPartnerUser__c='test';
        insert communityurl;
		
        RULconfigurations__c rulConfiguration = new RULconfigurations__c();
        rulConfiguration.Name='Change Request approval setting';
        rulConfiguration.Default_Change_request_Approval__c= '';
        insert rulConfiguration;
        
       Activity__c act = new Activity__c();
        act.requestForChangeRequest__c= true;
        act.Is_Read_Only__c=true;
        act.Name='test';
        act.Change_Request_Reason__c='';
        insert act;
        
        PageReference pageRef = Page.VfForApproval;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',act.id);
        
        test.startTest();        
        VfForApprovalController testActivityPlan = new VfForApprovalController();
        testActivityPlan.callApproved();
        testActivityPlan.callApprovedPlannedAct();
        test.stopTest();
    }
}