force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>TWR Activities</label>
    <nameField>
        <label>Activity  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TWR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date For Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/RULconfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RUL configurations</label>
</CustomObject>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_End_Year_Report__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_End_Year_Report__c</fullName>
    <label>Due Date For End Year Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activities</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DueDateHandler.cls
public class DueDateHandler {
    
    public static void DueDateMethod(List<Activity__c> ActList){
        RULconfigurations__c  customsettingdate =[select Due_Date_For_End_Year_Report__c,Due_Date_For_Planned_Activities__c from RULconfigurations__c];
        List<User> communityUser =[SELECT Username, Id,ContactId, ProfileId, IsPortalEnabled FROM User where IsPortalEnabled =true And Id=:UserInfo.getUserId()];
        
        try{
            Contact AccountIds =  [select Id,AccountId from Contact where AccountId != null and Id =: communityUser[0].ContactId ];//AccountId != null and
            Account acc=[select id,Name,Partner_Logo__c from Account where Id =: AccountIds.AccountId];
            for(Activity__c act:ActList){
                act.Due_Date__c=customsettingdate.Due_Date_For_End_Year_Report__c;
                act.Due_Date_For_Planned_Activities__c=customsettingdate.Due_Date_For_Planned_Activities__c;     
                act.Organisation__c=acc.Id;
            }    
        }
        catch(exception e){
            for(Activity__c act:ActList){
                act.Due_Date__c=customsettingdate.Due_Date_For_End_Year_Report__c;
                act.Due_Date_For_Planned_Activities__c=customsettingdate.Due_Date_For_Planned_Activities__c;
            }
        }
    }
}