force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>TWR Activities</label>
    <nameField>
        <label>Activity  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TWR Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Diamension_By_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_By_Score__c</fullName>
    <label>By Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <isActive>false</isActive>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
                <isActive>false</isActive>
                <label>5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_For_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_For_Score__c</fullName>
    <label>For Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_InOn_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_InOn_Score__c</fullName>
    <label>InOn Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_Thorugh_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_Thorugh_Score__c</fullName>
    <label>Through Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Diamension_With_Score__c.field-meta.xml
<CustomField>
    <fullName>Diamension_With_Score__c</fullName>
    <label>With Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date For Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Is_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Is_Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/reason_for_dimension_by__c.field-meta.xml
<CustomField>
    <fullName>reason_for_dimension_by__c</fullName>
    <label>By - Change Request Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/reason_for_dimension_for__c.field-meta.xml
<CustomField>
    <fullName>reason_for_dimension_for__c</fullName>
    <label>For - Change Request Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/reason_for_dimension_inon__c.field-meta.xml
<CustomField>
    <fullName>reason_for_dimension_inon__c</fullName>
    <label>InOn - Change Request Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/reason_for_dimension_through__c.field-meta.xml
<CustomField>
    <fullName>reason_for_dimension_through__c</fullName>
    <label>Through - Change Request Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/reason_for_dimension_with__c.field-meta.xml
<CustomField>
    <fullName>reason_for_dimension_with__c</fullName>
    <label>With - Change Request Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity_Report__c/Activity_Report__c.object-meta.xml
<CustomObject>
    <label>Activity Report</label>
    <nameField>
        <displayFormat>Act-{0000}</displayFormat>
        <label>Activity Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Report__c/fields/Activity_Name__c.field-meta.xml
<CustomField>
    <fullName>Activity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Name</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Activities Report</relationshipLabel>
    <relationshipName>Activities_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Report__c/fields/Partner_User__c.field-meta.xml
<CustomField>
    <fullName>Partner_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner user</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Activities_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Report__c/fields/Raraunga_Kaunga_Question1__c.field-meta.xml
<CustomField>
    <fullName>Raraunga_Kaunga_Question1__c</fullName>
    <label>Q1.</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity_Report__c/fields/Raraunga_Kaunga_Question2__c.field-meta.xml
<CustomField>
    <fullName>Raraunga_Kaunga_Question2__c</fullName>
    <label>Q2.</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity_Report__c/fields/Raraunga_Kaunga_Question3__c.field-meta.xml
<CustomField>
    <fullName>Raraunga_Kaunga_Question3__c</fullName>
    <label>Q3.</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity_Report__c/fields/Raraunga_Kaunga_Question4__c.field-meta.xml
<CustomField>
    <fullName>Raraunga_Kaunga_Question4__c</fullName>
    <label>Q4.</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity_Report__c/fields/Raraunga_Kaunga_Question5__c.field-meta.xml
<CustomField>
    <fullName>Raraunga_Kaunga_Question5__c</fullName>
    <label>Q5.</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/communitySportNz_URL__c/communitySportNz_URL__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>communitySportNz_URL</label>
</CustomObject>

force-app/main/default/objects/communitySportNz_URL__c/fields/communitySportNz_URLField__c.field-meta.xml
<CustomField>
    <fullName>communitySportNz_URLField__c</fullName>
    <label>communitySportNz_URLField</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/RULconfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RUL configurations</label>
</CustomObject>

force-app/main/default/objects/RULconfigurations__c/fields/Default_Change_request_Approval__c.field-meta.xml
<CustomField>
    <fullName>Default_Change_request_Approval__c</fullName>
    <label>Default Change request Approval</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_End_Year_Report__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_End_Year_Report__c</fullName>
    <label>Due Date For End Year Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RULconfigurations__c/fields/Due_Date_For_Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Planned_Activities__c</fullName>
    <label>Due Date For Planned Activities</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_VfForSwiperCntroller.cls
@isTest
public class Test_VfForSwiperCntroller {
    static testmethod void Test_VfForSwiperCntroller(){
        Profile p = [SELECT Id,Name FROM Profile WHERE Name='Disability Community (Partner)']; 
        User u = new User(FirstName='test',Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        communitySportNz_URL__c comm = new communitySportNz_URL__c();
        comm.communitySportNz_URLField__c='';
        insert comm;

        RULconfigurations__c rulConfiguration = new RULconfigurations__c();
        rulConfiguration.Name='Change Request approval setting';
        rulConfiguration.Default_Change_request_Approval__c= '';
        rulConfiguration.Due_Date_For_End_Year_Report__c=system.today()+10;
        rulConfiguration.Due_Date_For_Planned_Activities__c=system.today()+10;
        insert rulConfiguration;
 		RULconfigurations__c  customsetting =[select id,Name,Default_Change_request_Approval__c from RULconfigurations__c where Name=:rulConfiguration.Name];
      
       // RULconfigurations__c  customsettingemail =[select id,Name,Default_Change_request_Approval__c from RULconfigurations__c where Name='Change Request approval setting'];
        Activity__c act = new Activity__c();
        act.Name='test';
        /*act.Raraunga_Kaunga_Question1__c='hello welcome';
        act.Raraunga_Kaunga_Question2__c='hello welcome';
        act.Raraunga_Kaunga_Question3__c='hello welcome';
        act.Raraunga_Kaunga_Question4__c='hello welcome';
        act.Raraunga_Kaunga_Question5__c='hello welcome';*/
        act.Diamension_By_Score__c='3';
        act.Diamension_For_Score__c='4';
        act.Diamension_InOn_Score__c='2';
        act.Diamension_Thorugh_Score__c='1';
        act.Diamension_With_Score__c='5';
        act.Is_Read_Only__c=true;
        act.reason_for_dimension_by__c='test'; 
        act.reason_for_dimension_for__c='test';
        act.reason_for_dimension_inon__c='test';
        act.reason_for_dimension_through__c='test';
        act.reason_for_dimension_with__c='test';
        act.Due_Date__c=system.today();
        
        insert act;
        Activity_Report__c act1 = new Activity_Report__c();
        act1.Activity_Name__c=act.Id;
        act1.Partner_User__c=u.id;
        act1.Raraunga_Kaunga_Question1__c='hello welcome';
        act1.Raraunga_Kaunga_Question2__c='hello welcome';
        act1.Raraunga_Kaunga_Question3__c='hello welcome';
        act1.Raraunga_Kaunga_Question4__c='hello welcome';
        act1.Raraunga_Kaunga_Question5__c='hello welcome';
        insert act1;
        
        PageReference pageRef = Page.VfForSwiper;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',act.id);
        
        test.startTest();        
        VfForSwiperCntroller testActivityPlan = new VfForSwiperCntroller();
        testActivityPlan.getScores();
        VfForSwiperCntroller.completeActivity();
        VfForSwiperCntroller.saveTextEditorData();
        VfForSwiperCntroller.setScore();
        VfForSwiperCntroller.setChangeRequest();
        VfForSwiperCntroller.sendChangeNotificationToPartner();
        test.stopTest();
          
    }
}