force-app/main/default/objects/Participation_Data__c/Participation_Data__c.object-meta.xml
<CustomObject>
    <label>Participation Data</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Participation Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation_Data__c/fields/Programme_Name__c.field-meta.xml
<CustomField>
    <fullName>Programme_Name__c</fullName>
    <label>Programme Name</label>
    <referenceTo>Participation_Activity_Profile_Data__c</referenceTo>
    <relationshipLabel>Participation Data</relationshipLabel>
    <relationshipName>Participation_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Participation_DataController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of Participation_Data Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 30-11-2016       | Vivian Charlie   | 1. Created class to implement functionality of Participation_Data Page
   ==========================================================================================================================
*/
public class Participation_DataController{
    public Participation_Data__c newPart {get;set;}
    
    public Participation_DataController(){
        Id parentId = ApexPages.currentPage().getParameters().get('id');
        newPart = new Participation_Data__c();
        newPart.Programme_Name__c = parentId;
    }
    
    public PageReference save()
    {      
        try {
            upsert newPart;
        } catch(exception e) {
            ApexPages.addMessages(e);          
        }
        return new PageReference('/' + newPart.id);
    }
    
    public Pagereference cancel(){
        PageReference newpage = new Pagereference('/' + newPart.Programme_Name__c);
        newpage.setRedirect(true);
        return newpage;
    }
}