force-app/main/default/objects/Performance_Representative__c/Performance_Representative__c.object-meta.xml
<CustomObject>
    <label>Performance/Representative</label>
    <nameField>
        <label>Performance/Representative Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performance/Representative</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Performance_Representative__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Performance/Representative</relationshipLabel>
    <relationshipName>Performance_Representative_Event_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Performance_Representative_Event_Data__c/Performance_Representative_Event_Data__c.object-meta.xml
<CustomObject>
    <label>Performance/Representative Event Data</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance/Representative Event Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Performance_Representative_Event_Data__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Performance_Representative__r.End_Date__c</formula>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Performance_Representative_Event_Data__c/fields/Performance_Representative__c.field-meta.xml
<CustomField>
    <fullName>Performance_Representative__c</fullName>
    <label>Performance/Representative Event Name</label>
    <referenceTo>Performance_Representative__c</referenceTo>
    <relationshipLabel>Performance/Representative Event Data</relationshipLabel>
    <relationshipName>Performance_Representative_Event_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Performance_Representative_Event_Data__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Performance_Representative__r.Start_Date__c</formula>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PerformanceRepEventDataControllerTest.cls
@isTest
private class PerformanceRepEventDataControllerTest {
    private static testmethod void testSavePerRepData() {
        //Creating Test data
        list<Account> accList = RUL_Util.createAccounts();
        insert accList ;
        
        Performance_Representative__c tempRep = new Performance_Representative__c();
        tempRep.Organisation__c = accList[0].Id;
        tempRep.Start_Date__c = system.today();
        tempRep.End_Date__c = system.today();
        insert tempRep ;
        
        PageReference newPageRef = Page.Performance_Representative_Event_Data;
        newPageRef.getParameters().put('Id',tempRep.Id);
        Test.setCurrentPage(newPageRef);
        
        PerformanceRepEventDataController newObj = new PerformanceRepEventDataController();
        newObj.save();
        newObj.cancel();
        
        System.assertEquals(1, [select count() from Performance_Representative_Event_Data__c WHERE Performance_Representative__c =: tempRep.id]); 
    }
}