force-app/main/default/objects/Performance_Representative__c/Performance_Representative__c.object-meta.xml
<CustomObject>
    <label>Performance/Representative</label>
    <nameField>
        <label>Performance/Representative Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performance/Representative</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Performance_Representative_Event_Data__c/Performance_Representative_Event_Data__c.object-meta.xml
<CustomObject>
    <label>Performance/Representative Event Data</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance/Representative Event Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Performance_Representative_Event_Data__c/fields/Performance_Representative__c.field-meta.xml
<CustomField>
    <fullName>Performance_Representative__c</fullName>
    <label>Performance/Representative Event Name</label>
    <referenceTo>Performance_Representative__c</referenceTo>
    <relationshipLabel>Performance/Representative Event Data</relationshipLabel>
    <relationshipName>Performance_Representative_Event_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PerformanceRepEventDataController.cls
/*---------------------------------------------------------------------------------------------------------------------------
Description: This class is used to test functionality of PerformanceRepEventData Page

    =========================================================================================================================
        Version | Date(DD-MM-YYYY) | Last Modified By | Comments
    -------------------------------------------------------------------------------------------------------------------------
        1.0     | 30-11-2016       | Vivian Charlie   | 1. Created class to implement functionality of PerformanceRepEventData Page
   ==========================================================================================================================
*/
public class PerformanceRepEventDataController{
    public Performance_Representative_Event_Data__c perRepEventData {get;set;}
    
    public PerformanceRepEventDataController(){
        Id parentId = ApexPages.currentPage().getParameters().get('id');
        perRepEventData  = new Performance_Representative_Event_Data__c();
        perRepEventData.Performance_Representative__c = parentId;
    }
    
    public PageReference save()
    {      
        try {
            upsert perRepEventData ;
        } catch(exception e) {
            ApexPages.addMessages(e);          
        }
        return new PageReference('/' + perRepEventData.id);
    }
    
    public Pagereference cancel(){
        PageReference newpage = new Pagereference('/' + perRepEventData.Performance_Representative__c);
        newpage.setRedirect(true);
        return newpage;
    }
}