force-app/main/default/objects/Challenge__c/Challenge__c.object-meta.xml
<CustomObject>
    <label>Challenge</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Challenge__c/fields/Partner_Plan__c.field-meta.xml
<CustomField>
    <fullName>Partner_Plan__c</fullName>
    <label>Partner Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Challenges</relationshipLabel>
    <relationshipName>Challenges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Challenge__c/fields/Sport_NZ_Support__c.field-meta.xml
<CustomField>
    <fullName>Sport_NZ_Support__c</fullName>
    <label>Sport NZ Group Support</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <label>Investment Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Investment_Area__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <formula>Investment_Area__r.Strategic_Area__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Strategic Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Work_Brief__c.field-meta.xml
<CustomField>
    <fullName>Work_Brief__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Brief</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Work_Brief__c.Stage__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Work_Brief__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Partner_Plan__c.field-meta.xml
<CustomField>
    <fullName>Partner_Plan__c</fullName>
    <label>Partner Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Business_Improvement_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Business_Improvement_Proposition__c</fullName>
    <label>Business Improvement</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Community_Sport_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Community_Sport_Proposition__c</fullName>
    <label>Community Sport</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Events_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Events_Proposition__c</fullName>
    <label>Events</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Facilities_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Facilities_Proposition__c</fullName>
    <label>Facilities</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/High_Performance_Proposition__c.field-meta.xml
<CustomField>
    <fullName>High_Performance_Proposition__c</fullName>
    <label>High Performance</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Partner_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner_Mission_Statement__c.field-meta.xml
<CustomField>
    <fullName>Partner_Mission_Statement__c</fullName>
    <label>Partner Mission Statement</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner_Plan__c.field-meta.xml
<CustomField>
    <fullName>Partner_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Non-compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Brief__c/Work_Brief__c.object-meta.xml
<CustomObject>
    <description>Work brief planning and reporting</description>
    <label>Work Brief</label>
    <nameField>
        <label>Work Brief ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Briefs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Brief__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPlanEditExtension.cls
@isTest
private class TestPlanEditExtension {
    static testMethod void mySinglePageTest() {
        Account accountObject = new Account();
		accountObject.Name = 'Athletics NZ';
		accountObject.Type = 'National Sporting Organization';
		insert accountObject;
        
        Work_Brief__c workObj = new Work_Brief__c();
        workObj.Name = 'Test';
        workObj.Stage__c = 'Active';
        insert workObj;
        
		Plan__c planObject = new Plan__c();
		planObject.Partner__c = accountObject.id;
		planObject.Start_Date__c = date.today();
		planObject.End_Date__c = date.today().addDays(5);
		planObject.Status__c = 'Draft';
		insert planObject;
		Strategic_Area__c strategicAreaObject = new Strategic_Area__c();
		strategicAreaObject.Name = 'Community Sport';
		strategicAreaObject.Start_Date__c = date.today();
		strategicAreaObject.End_Date__c = date.today().addDays(5);
		insert strategicAreaObject;
		Investment_Area__c investmentAreaObject = new Investment_Area__c();
		investmentAreaObject.Strategic_Area__c = strategicAreaObject.id;
		investmentAreaObject.Name = 'Sports NSO';
		investmentAreaObject.Start_Date__c = date.today();
		investmentAreaObject.End_Date__c = date.today().addDays(5);
		investmentAreaObject.Status__c = 'Active';
		insert investmentAreaObject;
		Initiative__c initiativeObject = new Initiative__c();
		initiativeObject.Plan__c = planObject.id;
		initiativeObject.Name = 'Init';
        initiativeObject.Work_Brief__c = workObj.Id;
		initiativeObject.Investment_Area__c = investmentAreaObject.id;
		insert initiativeObject;
		Challenge__c challengeObject = new Challenge__c();
		challengeObject.Partner_Plan__c = planObject.id;
		challengeObject.Name = 'Challenge';
		challengeObject.Description__c = 'Challenge Desc';
		challengeObject.Sport_NZ_Support__c = 'Challenge NZ';
		insert challengeObject;
		Opportunity__c opportunityObject = new Opportunity__c();
		opportunityObject.Partner_Plan__c = planObject.id;
		opportunityObject.Name = 'Challenge';
		opportunityObject.Description__c = 'Challenge Desc';
		opportunityObject.Sport_NZ_Support__c = 'Challenge NZ';
		insert opportunityObject;
		Test.startTest();
		//Call single page
		ApexPages.currentPage().getParameters().put('id', planObject.id);
		ApexPages.StandardController stCon = new ApexPages.StandardController(planObject);
		PlanEditExtension planExtension = new PlanEditExtension(stCon);
		//Call the methods
		//planExtension.pageSectionFields = 'Information:#2::#Partner__c##Status__c##Start_Date__c##End_Date__c##:::#Success:#1::#Partner_Mission_Statement__c##:::#Engagement:#1::#Engagement_Rating__c##Engagement_Plan__c##:::#Value Propositions:#1::#High_Performance_Proposition__c##Community_Sport_Proposition__c##Business_Improvement_Proposition__c##Facilities_Proposition__c##Events_Proposition__c##:::#';
		planExtension.loadEditSectionCall();
		planExtension.refreshPage();
		planExtension.cancelDetails();
		//plain save
		planExtension.saveDetails();
		//validation for blank fields
		planExtension.initWrapList.get(0).initiative.Name = null;
		planExtension.oppWrapList.get(0).opportunity.Name = null;
		planExtension.challengeWrapList.get(0).challenge.Name = null;
		planExtension.saveDetails();
		//delete existing list
		planExtension.addInitiativeRow();
		planExtension.addOpportunityRow();
		planExtension.addChallengeRow();
		planExtension.rowInitDelete = 0;
		planExtension.deleteInitiativeRow();
		planExtension.rowOppDelete = 0;
		planExtension.deleteOpportunityRow();
		planExtension.rowChallDelete = 0;
		planExtension.deleteChallengeRow();
		planExtension.saveDetails();
		Test.stopTest();
		//Call single page with no id
		ApexPages.StandardController stConNo = new ApexPages.StandardController(planObject);
		PlanEditExtension planExtensionNone = new PlanEditExtension(stConNo);
		//Call the methods
		//planExtensionNone.pageSectionFields = 'Information:#2::#Partner__c##Status__c##Start_Date__c##End_Date__c##:::#Success:#1::#Partner_Mission_Statement__c##:::#Engagement:#1::#Engagement_Rating__c##Engagement_Plan__c##:::#Value Propositions:#1::#High_Performance_Proposition__c##Community_Sport_Proposition__c##Business_Improvement_Proposition__c##Facilities_Proposition__c##Events_Proposition__c##:::#';
		planExtensionNone.loadEditSectionCall();
		planExtensionNone.saveDetails();
    }
}