force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Conga_Workflow_Investment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Conga_Workflow_Investment_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conga Workflow Investment Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/StartInvestmentScheduleReportController.cls
public with sharing class StartInvestmentScheduleReportController {

    private Business_Case__c investmentSchedule;

    public StartInvestmentScheduleReportController(ApexPages.StandardController sc) {
        investmentSchedule = [SELECT Id FROM Business_Case__c WHERE Id = :sc.getId()];
    }

    public void startInvestmentScheduleReport() {
        try {
            investmentSchedule.Conga_Workflow_Investment_Schedule__c = true;
            update investmentSchedule;

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Document sent'));
        } catch (Exception e) {
            System.debug(e.getMessage() + '\n' + e.getStackTraceString());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Something went wrong, please contact your System Administrator'));
        }
    }
}