force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Variation_Count__c.field-meta.xml
<CustomField>
    <fullName>Variation_Count__c</fullName>
    <inlineHelpText>This indicates the number of times the Investment Schedule has been Varied.</inlineHelpText>
    <label>Variation Count</label>
    <summaryForeignKey>Variation__c.Investment_Schedule__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Business_Case__c.field-meta.xml
<CustomField>
    <fullName>Business_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Schedule</label>
    <referenceTo>Business_Case__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Old_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Old_RecordTypeID__c</fullName>
    <label>Old RecordTypeID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid Direct</fullName>
            </value>
            <value>
                <fullName>Paid to Third Party</fullName>
            </value>
            <value>
                <fullName>Time &amp; Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative__c/recordTypes/RUL_Read_Only_Initiative.recordType-meta.xml
<RecordType>
    <fullName>RUL_Read_Only_Initiative</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Read Only Initiative</label>
</RecordType>

force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Partner__c</field>
            <operation>equals</operation>
            <valueField>Initiative__c.Partner__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Old_Status__c.field-meta.xml
<CustomField>
    <fullName>Old_Status__c</fullName>
    <label>Old Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Update the Status when you receive results against this Measure.  This will generally be when you record the Result and Result Date.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
                <default>true</default>
                <label>Removed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Partially Met</fullName>
            </value>
            <value>
                <fullName>Not Met</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
                <default>true</default>
                <label>Number</label>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/recordTypes/Currency.recordType-meta.xml
<RecordType>
    <fullName>Currency</fullName>
    <active>true</active>
    <description>To capture financial measurements against KPIs</description>
    <label>Currency</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/Number.recordType-meta.xml
<RecordType>
    <fullName>Number</fullName>
    <active>true</active>
    <description>To represent numerical volume measurement of KPIs</description>
    <label>Number</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/Percent.recordType-meta.xml
<RecordType>
    <fullName>Percent</fullName>
    <active>true</active>
    <description>To reflect the percentage portion of a KPI benchmark or threshold</description>
    <label>Percent</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Currency_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Currency_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Currency Read Only</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Number_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Number_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Number Read only</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Percent_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Percent_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Percent Read Only</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/RUL_Text_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Text_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Text Read Only</label>
</RecordType>

force-app/main/default/objects/Measure__c/recordTypes/Text.recordType-meta.xml
<RecordType>
    <fullName>Text</fullName>
    <active>true</active>
    <description>For qualitative and commentary based assessment of measures against KPIs</description>
    <label>Text</label>
</RecordType>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PA{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Old_Status__c.field-meta.xml
<CustomField>
    <fullName>Old_Status__c</fullName>
    <label>Old Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sent for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/recordTypes/Buy_Back_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Buy_Back_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Buy Back Read Only</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Typically used where a payment was sent to the FMIS in error (cancelled before being paid) and needs to be balanced in Salesforce</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/Credit_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Credit_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Credit Read Only</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/Payment.recordType-meta.xml
<RecordType>
    <fullName>Payment</fullName>
    <active>true</active>
    <description>For all payments going from Sport NZ Group to an investment recipient or service provider</description>
    <label>Payment</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/Refund.recordType-meta.xml
<RecordType>
    <fullName>Refund</fullName>
    <active>true</active>
    <description>Used to reflect money received as a refund against an investment or procurement made from Salesforce</description>
    <label>Refund</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/Refund_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Refund_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Refund Read Only</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/RUL_Payment_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>RUL_Payment_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Payment Read Only</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/Service_Credit.recordType-meta.xml
<RecordType>
    <fullName>Service_Credit</fullName>
    <active>true</active>
    <description>Applies a credit in the FMIS AP, where a portion of an organisation&apos;s investment is allocated to services provided by Sport NZ Group</description>
    <label>Buy Back</label>
</RecordType>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#FF9900</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#009900</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FF0000</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#DDDDDD</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Variation</fullName>
                <color>#BBBBBB</color>
                <label>Variation</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <color>#666666</color>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#333333</color>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/recordTypes/Initiative_Requirement.recordType-meta.xml
<RecordType>
    <fullName>Initiative_Requirement</fullName>
    <active>true</active>
    <description>For applying conditions and requirements to initiatives. Can hold all payments in the initiative if the &apos;Hold&apos; box is checked.</description>
    <label>Initiative Requirement</label>
</RecordType>

force-app/main/default/objects/Requirement__c/recordTypes/Initiative_Requirement_Completed_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Initiative_Requirement_Completed_Read_Only</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Initiative Requirement Completed Read Only</label>
</RecordType>

force-app/main/default/objects/Requirement__c/recordTypes/Requirement_Completed.recordType-meta.xml
<RecordType>
    <fullName>Requirement_Completed</fullName>
    <active>true</active>
    <label>Initiative Requirement Completed</label>
</RecordType>

force-app/main/default/objects/Requirement__c/recordTypes/RUL_Initiative_Requirement_ReadOnly.recordType-meta.xml
<RecordType>
    <fullName>RUL_Initiative_Requirement_ReadOnly</fullName>
    <active>true</active>
    <description>This record type will be used to prevent edit of record when Inv schedule status is Approved or Signed.</description>
    <label>Initiative Requirement Read Only</label>
</RecordType>

force-app/main/default/objects/Variation__c/Variation__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule Variation</label>
    <nameField>
        <displayFormat>ISV-{00000}</displayFormat>
        <label>Investment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Schedule Variations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Variation__c/fields/Investment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Investment_Schedule__c</fullName>
    <label>Investment Schedule</label>
    <referenceTo>Business_Case__c</referenceTo>
    <relationshipLabel>Investment Schedule Variations</relationshipLabel>
    <relationshipName>Investment_Schedule_Variations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the current Status of the variation</description>
    <formula>if(ISBLANK(Variation_Completed_Date__c), &quot;Draft&quot;, &quot;Completed&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Variation Status changes to Completed once the Varied Investment Schedule has been approved</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Variation_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Variation_Completed_Date__c</fullName>
    <label>Variation Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BusinessCaseTriggerHelper.cls
public with sharing class BusinessCaseTriggerHelper {
    
    public static  List<Business_Case__c> updateinvestmentScheduleToSigned (Set<Id> setInvestmentSchedule){

        List<Business_Case__c> listInvSchedule = new List<Business_Case__c>();
        for(Business_case__c objInvSch : [Select ID,status__c from Business_case__c Where ID IN : setInvestmentSchedule]){
            objInvSch.status__c = 'Signed';
            listInvSchedule.add(objInvSch);
        }
        return listInvSchedule;
    }
    
    public static  List<Variation__c> updateVariation(Set<Id> investmentsToUpdateReadOnly){

         List<Business_Case__c >listBusinessCase = getListofInvestmentSchedules(investmentsToUpdateReadOnly);
         if(!listBusinessCase.isEmpty()){
             List<Variation__c> relatedVariation = new List<Variation__c>();
             //system.debug('relatedVariation >>>>>>>>>>>>>'+relatedVariation );
             //if(!relatedVariation.isEmpty()){
                  for(Variation__c objVariation: [SELECT Id, Variation_Completed_Date__c, Is_Active__c FROM Variation__c WHERE Is_Active__c = true AND Investment_Schedule__c IN: listBusinessCase ]){
                      objVariation.Variation_Completed_Date__c = Date.today();
                      relatedVariation.add(objVariation);
                  } 
             //}
              return relatedVariation;
         }else{
            return new List<Variation__c>();
         }
        
    }
    
    private static  List<Business_Case__c > getListofInvestmentSchedules(Set<Id> investmentsToUpdateReadOnly){

        List<Business_Case__c >listBusinessCase = new List<Business_Case__c>();
         for(Business_Case__c objIS : [Select ID,Variation_Count__c From Business_Case__c Where ID IN: investmentsToUpdateReadOnly]){
           //System.debug('BusinessCase List>>>>>>>>>>>'+objIS.Variation_Count__c);
              if(objIS.Variation_Count__c > 0 ){
               //System.debug('Business Count>>>>>>>>'+objIS);
               listBusinessCase.add(objIS);
              }
          }
          return listBusinessCase;
    }
    
    public static List<Initiative__c> relatedInitiativesReadOnly(Set<Id> investmentsToUpdateReadOnly){

        return [SELECT Id, 
                       Business_Case__c,
                       Old_RecordTypeID__c, 
                       Business_Case__r.Status__c, 
                       Type__c,
                       Partner__r.Type,
                       Approved__c,
                       RecordType.DeveloperName , 
                       (SELECT Id, 
                               Old_Status__c,
                               Initiative__c, 
                               RecordTypeId, 
                               RecordType.DeveloperName 
                        FROM Measures__r
                        WHERE Status__c !='Met' ), 
                       (SELECT Id, 
                               Old_Status__c,
                               Initiative__c, 
                               RecordTypeId, 
                               RecordType.DeveloperName ,
                               Status__c,
                               Supplier_Invoice_Date__c,
                               Supplier_Invoice_Number__c 
                        FROM Payments__r
                        WHERE Status__c != 'Paid'), 
                       (SELECT Id, 
                               Old_Status__c,
                               Initiative__c, 
                               RecordTypeId, 
                               RecordType.DeveloperName 
                        FROM Requirements__r
                        WHERE status__C not in ('Completed','Cancelled')) 
                FROM   Initiative__c 
                WHERE Business_Case__c IN: investmentsToUpdateReadOnly];
    }
    
    public static List<Measure__c> updateMeasureWithOldStatus(List<Measure__c> listofRelatedMeasure){
         List<Measure__c> listMeasure = new List<Measure__c>();
         for(Measure__c objMeasure : listofRelatedMeasure){
             if(objMeasure.Old_Status__c != NULL){
                objMeasure.Status__c = objMeasure.Old_Status__c ;
                listMeasure.add(objMeasure);
             }
         }
         return listMeasure;
    }
    
    public static List<Requirement__c> updateRequirementWithOldStatus(List<Requirement__c> listofRelatedRequirement){

        List<Requirement__c> listRequirement = new List<Requirement__c>();
        for(Requirement__c objReq :listofRelatedRequirement){
            if(objReq.Old_Status__c != NULL){
                objReq.Status__c = objReq.Old_Status__c;
                listRequirement.add(objReq);
            }
        }
         return listRequirement;
    }
    
    public static List<Payment__c> updatePaymentWithOldStatus(List<Payment__c> listofRelatedPayment){

         List<Payment__c> listPayment = new List<Payment__c>();
         for(Payment__c objPay : listofRelatedPayment){
              if(objPay.Old_Status__c != NULL){
                  objPay.Status__c = objPay.Old_Status__c;
                  listPayment.add(objPay);
              }
          }
         return listPayment;
    }
    
    public static Boolean updateInitiativeApproved(List<Initiative__c> relatedInitiatives,Boolean isReadOnly, Map<String,Id> recordTypesAvailable){
        
	for(Initiative__c objInitiative : relatedInitiatives){
                
                if(isReadOnly){
                    objInitiative.RecordTypeId = recordTypesAvailable.get('RUL_Read_Only_Initiative');
                }else if(String.isNotBlank(objInitiative.Old_RecordTypeID__c)){
                    objInitiative.RecordTypeId = objInitiative.Old_RecordTypeID__c;
                }
                //////ool//////////////////////////////////
                if(objInitiative.Approved__c && objInitiative.Business_Case__r.Status__c != 'Approved' && objInitiative.Business_Case__r.Status__c != 'Signed'){
                    //System.debug('false');
                    objInitiative.Approved__c = false;
                }
                else if (!objInitiative.Approved__c && (objInitiative.Business_Case__r.Status__c == 'Approved' || objInitiative.Business_Case__r.Status__c == 'Signed')){
                    //System.debug('true');
                    objInitiative.Approved__c = true;
                }
                
              //////////////////////////////////////////////
        }
        //system.debug('relatedInitiatives -------------------------'+relatedInitiatives);
        
        try{
            update relatedInitiatives;
            return false;
        }catch(DmlException e){
           system.debug('The following exception has occurred during making records readonly(Initiative): ' + e.getMessage());
           return true;
        }
    }
    
    public static Boolean updateMeasureRecordType(Set<Id> investmentsToUpdateReadOnly, List<Initiative__c> relatedInitiatives,  Map<String,Id> recordTypesAvailable ){

        List<Measure__c> relatedMeasure = new List<Measure__c>();
        for(Initiative__c objInitiative : relatedInitiatives){
            //system.debug('Measure Present ---------------------'+(investmentsToUpdateReadOnly.contains(objInitiative.Id)));
            if(investmentsToUpdateReadOnly.contains(objInitiative.Business_Case__c)){
                //system.debug('Inside Measure>>>>>>>>');
                for(Measure__c objMeasure : objInitiative.Measures__r){
                    //system.debug('Messure>>>>>>>>>>>'+objMeasure.id);
                    if(objMeasure.RecordType.DeveloperName == 'Percent'){
                        objMeasure.RecordTypeId = recordTypesAvailable.get('RUL_Percent_Read_Only');
                    }else if(objMeasure.RecordType.DeveloperName == 'Number'){
                        objMeasure.RecordTypeId = recordTypesAvailable.get('RUL_Number_Read_Only');
                    }else if(objMeasure.RecordType.DeveloperName == 'Currency'){
                        objMeasure.RecordTypeId = recordTypesAvailable.get('RUL_Currency_Read_Only');
                    }else if(objMeasure.RecordType.DeveloperName == 'Text'){
                        objMeasure.RecordTypeId = recordTypesAvailable.get('RUL_Text_Read_Only');
                    }
                    relatedMeasure.add(objMeasure);
                    //system.debug('relatedMeasure>>>>>>>'+relatedMeasure);
                }
            }
        }
        if(!relatedMeasure.isEmpty()){
            try{
                update relatedMeasure;
                return false;
            }catch(DmlException e){
               system.debug('The following exception has occurred during making records readonly(Measure): ' + e.getMessage());
               return true;
            }
        }else{
            return false;
        }
        
    }
    
    public static Boolean updateRequirementRecordType(Set<Id> investmentsToUpdateReadOnly, List<Initiative__c> relatedInitiatives,  Map<String,Id> recordTypesAvailable ){

        List<Requirement__c> relatedRequirements =  new List<Requirement__c>();
        for(Initiative__c objInitiative : relatedInitiatives){
            if(investmentsToUpdateReadOnly.contains(objInitiative.Business_Case__c)){
                for(Requirement__c objRequirement : objInitiative.Requirements__r){
                    //system.debug('Inside Requirement'+objRequirement.RecordTypeId);
                   // system.debug('Condition Requirement>>>>>>'+(objRequirement.RecordTypeId != recordTypesAvailable.get('RUL Read Only')));
                    if(objRequirement.RecordType.DeveloperName == 'Initiative_Requirement' ){
                        objRequirement.RecordTypeId = recordTypesAvailable.get('RUL_Initiative_Requirement_ReadOnly');
                        //System.debug('Update Requirem,ent'+objRequirement);
                        relatedRequirements.add(objRequirement);
                    }else if(objRequirement.RecordType.DeveloperName == 'Requirement_Completed' ){
                        objRequirement.RecordTypeId = recordTypesAvailable.get('Initiative_Requirement_Completed_Read_Only');
                        //System.debug('Update Requirem,ent'+objRequirement);
                        relatedRequirements.add(objRequirement);
                    }
                }
            }
        }
        if(!relatedRequirements.isEmpty()){
            try{
                update relatedRequirements;
                return false;
            }catch(DmlException e){
               system.debug('The following exception has occurred during making records readonly(Requirement): ' + e.getMessage());
               return true;
            }
        }else{
            return false;
        }
    }
    
    public static Boolean updatePaymentsRecordType(Set<Id> investmentsToUpdateReadOnly, List<Initiative__c> relatedInitiatives,  Map<String,Id> recordTypesAvailable ){

        Boolean paymentUpdated = false;
        List<Payment__c> relatedPayments = new List<Payment__c>();
        for(Initiative__c objInitiative : relatedInitiatives){
            if(investmentsToUpdateReadOnly.contains(objInitiative.Business_Case__c)){
                for(Payment__c objPayment : objInitiative.Payments__r){
                    if(objInitiative.Business_Case__c<>NULL && (objInitiative.Business_Case__r.Status__c =='Approved') && objInitiative.Type__c == 'Paid to Third Party'){
                        if (objPayment.Status__c=='Draft' && objPayment.Supplier_Invoice_Date__c<>NULL && objPayment.Supplier_Invoice_Number__c<>NULL && !String.isBlank(objPayment.Supplier_Invoice_Number__c)){
                            objPayment.Status__c = 'Scheduled';
                            paymentUpdated = true;
                        }
                    }else if(objInitiative.Business_Case__c<>NULL && (objInitiative.Business_Case__r.Status__c =='Approved') && objInitiative.Type__c == 'Paid Direct' && objInitiative.Partner__r.Type=='Supplier'){
                        if (objPayment.Status__c=='Draft' && objPayment.Supplier_Invoice_Date__c<>NULL && 
                            objPayment.Supplier_Invoice_Number__c<>NULL && !String.isBlank(objPayment.Supplier_Invoice_Number__c)){
                            objPayment.Status__c = 'Scheduled';
                            paymentUpdated = true;
                        }
                    }
                    //system.debug('objpayment recordtype>>>'+objPayment.RecordTypeId);
                    //system.debug('Condition Payment>>>>>>'+(objPayment.RecordTypeId != recordTypesAvailable.get('RUL Payment Read Only')));
                    if(objPayment.RecordType.DeveloperName == 'Payment'){
                        objPayment.RecordTypeId = recordTypesAvailable.get('RUL_Payment_Read_Only');
                        paymentUpdated = true;
                       // system.debug('Update payemtn'+objPayment);
                    }else if(objPayment.RecordType.DeveloperName == 'Refund'){
                        objPayment.RecordTypeId = recordTypesAvailable.get('Refund_Read_Only');
                        paymentUpdated = true;
                        //system.debug('Update payemtn'+objPayment);
                    }else if(objPayment.RecordType.DeveloperName == 'Credit'){
                        objPayment.RecordTypeId = recordTypesAvailable.get('Credit_Read_Only');
                        paymentUpdated = true;
                        //system.debug('Update payemtn'+objPayment);
                    }else if(objPayment.RecordType.DeveloperName == 'Service_Credit'){
                        objPayment.RecordTypeId = recordTypesAvailable.get('Buy_Back_Read_Only');
                        paymentUpdated = true;
                        //system.debug('Update payemtn'+objPayment);
                    }
                    relatedPayments.add(objPayment);
                }
            }
        }
        if(!relatedPayments.isEmpty()){
            try{
                update relatedPayments;
            }catch(DmlException e){
               system.debug('The following exception has occurred during making records readonly(Payment): ' + e.getMessage());
               paymentUpdated = false;
            }
        }
        return paymentUpdated;
    }
}