force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Variation Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Investment_Schedule_ID__c.field-meta.xml
<CustomField>
    <fullName>Investment_Schedule_ID__c</fullName>
    <displayFormat>IS{000000}</displayFormat>
    <label>Investment Schedule ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variation__c/Variation__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule Variation</label>
    <nameField>
        <displayFormat>ISV-{00000}</displayFormat>
        <label>Investment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Schedule Variations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Variation__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <inlineHelpText>“Briefly describe the purpose of this variation. This will be useful information for the approver and for future reference.”</inlineHelpText>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Initiated_By__c.field-meta.xml
<CustomField>
    <fullName>Initiated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investment_Schedule_Variations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Investment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Investment_Schedule__c</fullName>
    <label>Investment Schedule</label>
    <referenceTo>Business_Case__c</referenceTo>
    <relationshipLabel>Investment Schedule Variations</relationshipLabel>
    <relationshipName>Investment_Schedule_Variations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the current Status of the variation</description>
    <formula>if(ISBLANK(Variation_Completed_Date__c), &quot;Draft&quot;, &quot;Completed&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Variation Status changes to Completed once the Varied Investment Schedule has been approved</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Variation_Initiation_Date__c.field-meta.xml
<CustomField>
    <fullName>Variation_Initiation_Date__c</fullName>
    <label>Variation Initiation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InitiateVariatonController.cls
/**
* @Author: Eternus Solutions
* @Class: InitiateVariatonController
* @Description: This class is used to insert variations for specific Investment Schedule.
* @Date: 24/05/2018
**/

public with sharing class InitiateVariatonController{
    
    public String isID {get;set;}
    public String isNum {get;set;}
    public String isName {get;set;}
    public Date initiationDate {get;set;}
    public String initiatedBy {get;set;}
    public String purpose {get;set;}
    public String comments {get;set;}
    public boolean showVariation{get;set;}
    public boolean showMessage{get;set;}
    public boolean showContinue{get;set;}
    public variation__c objVar{get;set;}
    
    public InitiateVariatonController(ApexPages.StandardController stdController){
        showContinue = false;
        showMessage = false;
        isID = apexpages.currentpage().getparameters().get('id');
        
        system.debug('#InitiateVariatonController##isID-->>'+isID);
        
        if(String.isNotBlank(isID)){
            List<Business_Case__c> isList = [Select  Id,
                                             Investment_Schedule_ID__c,
                                             Name,
                                             CreatedBy.Name,
                                             Status__c
                                             From Business_Case__c
                                             Where Id =: isID
                                             Limit 1];
            if(isList[0].status__c == 'Approved' ||isList[0].status__c == 'Signed' || isList[0].status__c == 'Closed' ){
                 showVariation = true;
                 
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.info,System.Label.VariationWarning));
            }
            else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,System.Label.VariationCannotBeCreated));
            }
            
            isNum = isList[0].Investment_Schedule_ID__c;
            isName = isList[0].Name;
            initiationDate = System.today();
            initiatedBy = UserInfo.getName();
        }
        else{
            isID ='';
        }
        
    }
    
   public  void  NextButtonMethod(){
        showMessage = true;
        showVariation = false;
    }
    public PageReference insertVariation(){
        List<Profile> PROFILE = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String MyProflieName = PROFILE[0].Name;
        if(MyProflieName == 'Kahiwi' || MyProflieName == 'System Administrator'){
            RecursionHandler.TrgVariationBypass = true;
        }
        if( String.isNotBlank(comments)){
            
            Variation__c varRec = new Variation__c();
            varRec.Comments__c = comments;
            varRec.Initiated_By__c = UserInfo.getUserId();
            varRec.Variation_Initiation_Date__c = System.today();
            varRec.Investment_Schedule__c = isID;
            varRec.Is_Active__c = true;
            try{
                if(Limits.getCpuTime() < Integer.valueOf(Label.Cpu_Time_Limit)){
                    insert varRec;
                 }else{
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'CPU Limit Exceeding!! Current CPU Time is '+Limits.getCpuTime()));
                }
                PageReference pgRef = new PageReference('/'+isID);
                updateCustomSettingKahiwi();
                return pgRef;
            }
            catch(Exception ex){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,ex.getMessage()));
            }
        }
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please Select Mandatory Fields'));
        }
        return null;
    }
    
    public PageReference cancelVariation(){
        system.debug('@InitiateVariatonController@isID-->>'+isID);
        
        PageReference pgRef;
        if(String.isNotBlank(isID)){
            pgRef = new PageReference('/'+isID);
        }
        else{
            Map<String, Schema.SObjectType> globalMap  = Schema.getGlobalDescribe() ;
            Schema.SObjectType inShdlObj = globalMap.get('Business_Case__c') ;
            Schema.DescribeSObjectResult descResult = inShdlObj.getDescribe() ;
            String keyPrefix = descResult.getKeyPrefix();
            pgRef = new PageReference('/'+keyPrefix);
        }
        pgRef.setRedirect(true);
        updateCustomSettingKahiwi();
        return pgRef;
    }
    
    
    private static void updateCustomSettingKahiwi(){
        RecursionHandler.TrgVariationBypass = false;
    }
}