force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manager Delegation</fullName>
                <default>true</default>
                <label>Manager Delegation</label>
            </value>
            <value>
                <fullName>GM Delegation</fullName>
            </value>
            <value>
                <fullName>CEO Delegation</fullName>
            </value>
            <value>
                <fullName>Board Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Variation Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipName>Business_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/T_Cs__c.field-meta.xml
<CustomField>
    <fullName>T_Cs__c</fullName>
    <label>T&amp;Cs</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BC 2015 T&amp;C</fullName>
            </value>
            <value>
                <fullName>Rural Travel Fund T&amp;C</fullName>
            </value>
            <value>
                <fullName>Short form T&amp;C</fullName>
            </value>
            <value>
                <fullName>Long form T&amp;C</fullName>
            </value>
            <value>
                <fullName>New T&amp;C&apos;s</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IsVariationInititated__c/IsVariationInititated__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Is Variation Inititated</label>
</CustomObject>

force-app/main/default/objects/IsVariationInititated__c/fields/Variation_Inititated__c.field-meta.xml
<CustomField>
    <fullName>Variation_Inititated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Variation Inititated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Variation__c/Variation__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule Variation</label>
    <nameField>
        <displayFormat>ISV-{00000}</displayFormat>
        <label>Investment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Schedule Variations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Variation__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <inlineHelpText>“Briefly describe the purpose of this variation. This will be useful information for the approver and for future reference.”</inlineHelpText>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Investment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Investment_Schedule__c</fullName>
    <label>Investment Schedule</label>
    <referenceTo>Business_Case__c</referenceTo>
    <relationshipLabel>Investment Schedule Variations</relationshipLabel>
    <relationshipName>Investment_Schedule_Variations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the current Status of the variation</description>
    <formula>if(ISBLANK(Variation_Completed_Date__c), &quot;Draft&quot;, &quot;Completed&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Variation Status changes to Completed once the Varied Investment Schedule has been approved</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestInitiateVariationController.cls
@isTest
public class TestInitiateVariationController {
    /*@isTest
    public static void testMethod1(){
        Business_Case__c businessCaseObject = new Business_Case__c();
        //businessCaseObject.RecordTypeId = businessCaseRecordTypeId;
        businessCaseObject.Name = 'Test Business Case';
        //businessCaseObject.Investment_Area__c = investmentAreaObject.id;
        businessCaseObject.Approval_Type__c = 'Manager Delegation';
        businessCaseObject.Status__c = 'Approved';
        businessCaseObject.T_Cs__c ='Rural Travel Fund T&C';
        insert businessCaseObject;
        
         Variation__c objVar = new Variation__c();
        objVar.Comments__c = 'Test';
        objVar.Investment_Schedule__c = businessCaseObject.Id;
        insert objVar;
        Test.StartTest(); 
        //Test.setCurrentPageReference(new PageReference('Page.VariationCreationPage'));
        //ApexPages.StandardController controllerer = new ApexPages.standardController(businessCaseObject.id);
        //InitiateVariatonController testClass= new InitiateVariatonController(controllerer);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(businessCaseObject);
        InitiateVariatonController testClass= new InitiateVariatonController(sc);
        
        PageReference pageRef = Page.VariationCreationPage;
        pageRef.getParameters().put('id', businessCaseObject.Id);
        Test.setCurrentPage(pageRef);
       
        
        testClass.getoptns();
        testClass.insertVariation();
        testClass.cancelVariation();
        //testClass.function1Name();
        
        //testClass.function2Name();

        Test.StopTest();
    }*/
   /* @IsTest
    public static void testMethod1() {
        Variation__c obj = new Variation__c();

        Business_Case__c ivs = new Business_Case__c();
        ivs.Name = 'RUL Test INVS';
        ivs.Approval_Tpe__c = 'Manager Delegation';
        ivs.Status__c = 'Approved';
        insert ivs;

        PageReference pg = Page.VariationCreationPage;
        pg.getParameters().put('retURL','/'+ivs.Id );
        Test.setCurrentPage(pg);
        //Test.setCurrentPageReference( Page.PageName);
      System.currentPageReference().getParameters().put('id', ivs.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        InitiateVariatonController controller = new InitiateVariatonController(sc);
        controller.isID = ivs.Id;
        controller.purpose = 'Remove the obligations and commitments of an Initiative';
        controller.comments = 'Test Class Comments';

        test.startTest();
            controller.insertVariation();
            controller.cancelVariation();
            controller.getoptns();
        //controller.NextButtonMethod();
        test.stopTest();

        List<Variation__c> varRecList = [Select Id, Comments__c From Variation__c Where Investment_Schedule__c =:ivs.Id ];
        system.assertEquals(varRecList.size(),1);
        system.assertEquals(varRecList[0].Comments__c,'Test Class Comments');
      }
*/ @isTest
     public static void testMethod2() {
        Variation__c obj = new Variation__c();

        Business_Case__c ivs = new Business_Case__c();
        ivs.Name = 'RUL Test INVS';
        ivs.Approval_Type__c = 'Manager Delegation';
        ivs.Status__c = 'Being Varied';
        insert ivs;
         
         /*IsVariationInititated__c obj1 = new IsVariationInititated__c();
		 obj1.Name = 'test';
         insert obj1;*/
         //ID profileID = [Select ID from Profile where Name = 'Kahiwi' Limit 1].id;
         insert new IsVariationInititated__c(SetupOwnerId=UserInfo.getProfileId(), Variation_Inititated__c=true);
         
         //system.debug()
         
		//IsVariationInititated__c.Variation_Inititated__c = false;
         //IsVariationInititated__c.id =mcs[0].id; 

        PageReference pg = Page.VariationCreationPage;
        pg.getParameters().put('retURL','/'+ivs.Id );
        Test.setCurrentPage(pg);
        //Test.setCurrentPageReference( Page.PageName);
      System.currentPageReference().getParameters().put('id', ivs.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        InitiateVariatonController controller = new InitiateVariatonController(sc);
        controller.isID = ivs.Id;
        controller.purpose = 'Remove the obligations and commitments of an Initiative';
        controller.comments = 'Test Class Comments';

        test.startTest();
            controller.insertVariation();
            controller.cancelVariation();
           // controller.getoptns();
       // controller.NextButtonMethod();
        test.stopTest();

        List<Variation__c> varRecList = [Select Id, Comments__c From Variation__c Where Investment_Schedule__c =:ivs.Id ];
        system.assertEquals(varRecList.size(),1);
        system.assertEquals(varRecList[0].Comments__c,'Test Class Comments');
      }
    
     @IsTest
    public static void testMethod3() {
        Variation__c obj = new Variation__c();

        Business_Case__c ivs = new Business_Case__c();
        ivs.Name = 'RUL Test INVS';
        ivs.Approval_Type__c = 'Manager Delegation';
        ivs.Status__c = 'Approved';
        insert ivs;

        PageReference pg = Page.VariationCreationPage;
        pg.getParameters().put('retURL','/'+ivs.Id );
        Test.setCurrentPage(pg);
        //Test.setCurrentPageReference( Page.PageName);
      System.currentPageReference().getParameters().put('id', ivs.Id);
	insert new IsVariationInititated__c(SetupOwnerId=UserInfo.getProfileId(), Variation_Inititated__c=true);
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        InitiateVariatonController controller = new InitiateVariatonController(sc);
        controller.isID = ivs.Id;
        controller.purpose = 'Remove the obligations and commitments of an Initiative';
        controller.comments = 'Test Class Comments';

        test.startTest();
            controller.insertVariation();
            controller.cancelVariation();
          //  controller.getoptns();
        //controller.NextButtonMethod();
        test.stopTest();

        List<Variation__c> varRecList = [Select Id, Comments__c From Variation__c Where Investment_Schedule__c =:ivs.Id ];
        system.assertEquals(varRecList.size(),1);
        system.assertEquals(varRecList[0].Comments__c,'Test Class Comments');
      }

     public static void testMethod4() {
        Variation__c obj = new Variation__c();

        Business_Case__c ivs = new Business_Case__c();
        ivs.Name = 'RUL Test INVS';
        ivs.Approval_Type__c = 'Manager Delegation';
        ivs.Status__c = 'Being Varied';
        insert ivs;

        PageReference pg = Page.VariationCreationPage;
        pg.getParameters().put('retURL','/'+ivs.Id );
        Test.setCurrentPage(pg);
        //Test.setCurrentPageReference( Page.PageName);
      System.currentPageReference().getParameters().put('id', ivs.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        InitiateVariatonController controller = new InitiateVariatonController(sc);
        controller.isID = ivs.Id;
        controller.purpose = 'Remove the obligations and commitments of an Initiative';
        controller.comments = 'Test Class Comments';

        test.startTest();
            controller.insertVariation();
            controller.cancelVariation();
          //  controller.getoptns();
       // controller.NextButtonMethod();
        test.stopTest();

        List<Variation__c> varRecList = [Select Id, Comments__c From Variation__c Where Investment_Schedule__c =:ivs.Id ];
        system.assertEquals(varRecList.size(),1);
        system.assertEquals(varRecList[0].Comments__c,'Test Class Comments');
      }

}