force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Variation Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Investment_Schedule_ID__c.field-meta.xml
<CustomField>
    <fullName>Investment_Schedule_ID__c</fullName>
    <displayFormat>IS{000000}</displayFormat>
    <label>Investment Schedule ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variation__c/Variation__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule Variation</label>
    <nameField>
        <displayFormat>ISV-{00000}</displayFormat>
        <label>Investment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Schedule Variations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Variation__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <inlineHelpText>“Briefly describe the purpose of this variation. This will be useful information for the approver and for future reference.”</inlineHelpText>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Initiated_By__c.field-meta.xml
<CustomField>
    <fullName>Initiated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investment_Schedule_Variations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Investment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Investment_Schedule__c</fullName>
    <label>Investment Schedule</label>
    <referenceTo>Business_Case__c</referenceTo>
    <relationshipLabel>Investment Schedule Variations</relationshipLabel>
    <relationshipName>Investment_Schedule_Variations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the current Status of the variation</description>
    <formula>if(ISBLANK(Variation_Completed_Date__c), &quot;Draft&quot;, &quot;Completed&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Variation Status changes to Completed once the Varied Investment Schedule has been approved</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variation__c/fields/Variation_Initiation_Date__c.field-meta.xml
<CustomField>
    <fullName>Variation_Initiation_Date__c</fullName>
    <label>Variation Initiation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateVariatonController.cls
/**
     * @Author: Eternus Solutions
     * @Class: CreateVariatonController
     * @Description: This class is used to insert variations for specific Investment Schedule.
     * @Date: 31/05/2018
  **/

public with sharing class CreateVariatonController{

    public ID isID {get;set;}
    public String isNum {get;set;}
    public String isName {get;set;}
    public String purpose {get;set;}
    public String comments {get;set;}
	public Variation__c newVariation {get;set;}
    public String invShdlStrId;
    public Id invSchId;
    public String invShdlStatus {get;set;}

    public CreateVariatonController(ApexPages.StandardController stdController){

        newVariation =(Variation__c)stdController.getrecord();
		invShdlStrId = ApexPages.currentPage().getParameters().get('retURL');
		if(invShdlStrId !=NULL ){
            invShdlStrId = string.valueof(invShdlStrId).substringAfter('/');
        }
        else{
            invShdlStrId ='';
        }

        if(invShdlStrId.length() >=15 ) {
            invSchId = id.valueof(invShdlStrId);
        }

        newVariation = new Variation__c();

        // Check whethere request came from Investment Schedule Page or Investment Schedule Variation Page
        if(invShdlStrId.length() >=15 && Schema.Business_Case__c.SObjectType == invSchId.getSobjectType()) {
            newVariation.Investment_Schedule__c = invSchId;

            List<Business_Case__c> isList = [Select  Id,
                                                  Investment_Schedule_ID__c,
                                                  Name,
                                                  Status__c,
                                                  CreatedBy.Name
                                             From Business_Case__c
                                            Where Id =: invSchId
                                            Limit 1];
            isID = isList[0].Id;
            isNum = isList[0].Investment_Schedule_ID__c;
            isName = isList[0].Name;
            invShdlStatus = isList[0].Status__c;
            
            System.debug('Status VAlue:--'+invShdlStatus);

        }
        newVariation.Initiated_By__c = UserInfo.getUserId();
        newVariation.Variation_Initiation_Date__c = System.today();
    }
 //Insert the variation record.
    public PageReference insertVariation(){

        if(String.isNotBlank(comments)){
            //newVariation.what_is_the_purpose_of_this_variation__c = purpose;
            newVariation.Comments__c = comments;

            try{
                insert newVariation;
            }
            catch(Exception ex){
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,ex.getMessage()));
            }

            PageReference newpage;
                if(invShdlStrId.length()>=15) {
                    newpage = new PageReference('/' + newVariation.Investment_Schedule__c);
                } else {
                    newpage = new PageReference('/' + newVariation.id);
                }
            newpage.setRedirect(true);
            return newpage;
        }
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please Select Mandatory Fields'));
        }

        return null;
    }

    // Cancel the variation creation.
    public PageReference cancelVariation(){

        PageReference newpage ;//= new PageReference();
        if(String.isNotBlank(invShdlStrId)){
            if(invShdlStrId.length() >=15 ) {
                newpage = new PageReference('/' + invSchId);
            } else {
                newpage = new PageReference('/' + invShdlStrId);
            }
        }
        else{
            Map<String, Schema.SObjectType> globalMap = Schema.getGlobalDescribe() ;
            Schema.SObjectType inShdlObj = globalMap.get('Business_Case__c') ;
            Schema.DescribeSObjectResult descResult = inShdlObj.getDescribe() ;
            String keyPrefix = descResult.getKeyPrefix();
            newpage = new PageReference('/'+keyPrefix);
        }
        newpage.setRedirect(true);
        return newpage;
    }
}