force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Executive_Summary__c.field-meta.xml
<CustomField>
    <fullName>Executive_Summary__c</fullName>
    <label>Executive Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipName>Business_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Schedules</relationshipLabel>
    <relationshipName>Investment_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Partner_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Non-compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/recordTypes/Bundled_Plan.recordType-meta.xml
<RecordType>
    <fullName>Bundled_Plan</fullName>
    <active>true</active>
    <description>Used for grouping initiatives for non-targeted Partners, contestable investments, programmes, and supplier contracts</description>
    <label>Project Plan</label>
</RecordType>

force-app/main/default/objects/Plan__c/recordTypes/Partner_Plan.recordType-meta.xml
<RecordType>
    <fullName>Partner_Plan</fullName>
    <active>true</active>
    <description>For engagement and investment planning with organisations that Sport NZ Group targets</description>
    <label>Partner Plan</label>
</RecordType>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestStartInvestmentScheduleReport.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestStartInvestmentScheduleReport {

    static testMethod void TestStartInvestmentScheduleReport() {
        
         List<Account> accountToInsertList = new List<Account>();
        Account accountObject = new Account();
        accountObject.Name = 'Athletics NZ';
        accountObject.Type = 'National Sporting Organization';
        accountToInsertList.add(accountObject);

        Account accountObjectLimited = new Account();
        accountObjectLimited.Name = 'Athletics Limited ';
        accountObjectLimited.Type = 'National Sporting Organization';
        accountToInsertList.add(accountObjectLimited);
        
        insert accountToInsertList;
        
    
        
        Strategic_Area__c strategicAreaObject = new Strategic_Area__c();
        strategicAreaObject.Name = 'Community Sport';
        strategicAreaObject.Start_Date__c = date.today();
        strategicAreaObject.End_Date__c = date.today().addDays(5);
        insert strategicAreaObject;
        
        
        
        List<Plan__c> planObjectInsertList = new List<Plan__c>();

        Plan__c planObject = new Plan__c();
        planObject.Partner__c = accountObject.id;
        planObject.RecordTypeId = [Select Id from RecordType where sobjectType = 'Plan__c' and DeveloperName = 'Partner_Plan'].Id;
        //planObject.investment_area__c = investmentAreaObject.id;
        planObject.Start_Date__c = date.today();
        planObject.End_Date__c = date.today().addDays(5);
        planObject.Status__c = 'Draft';
        planObjectInsertList.add(planObject);

        Plan__c planObjectLimited = new Plan__c();
        planObjectLimited.Partner__c = accountObjectLimited.id;
        planObjectLimited.RecordTypeId = [Select Id from RecordType where sobjectType = 'Plan__c' and DeveloperName = 'Bundled_Plan' ].Id;
        //planObjectLimited.investment_area__c = investmentAreaObject.id;
        planObjectLimited.Start_Date__c = date.today();
        planObjectLimited.End_Date__c = date.today().addDays(5);
        planObjectLimited.Status__c = 'Draft';
        planObjectInsertList.add(planObjectLimited);
        
        insert planObjectInsertList;
        
        list<Investment_Area__c> investmentAreaList = new list<Investment_Area__c>();
        
        Investment_Area__c investmentAreaObject = new Investment_Area__c();
        investmentAreaObject.Strategic_Area__c = strategicAreaObject.id;
        investmentAreaObject.Name = 'Sports NSO';
        investmentAreaObject.Start_Date__c = date.today();
        investmentAreaObject.End_Date__c = date.today().addDays(5);
        investmentAreaObject.Status__c = 'Active';
        investmentAreaList.add(investmentAreaObject);
        
        Investment_Area__c investmentAreaObject2 = new Investment_Area__c();
        investmentAreaObject2.Strategic_Area__c = strategicAreaObject.id;
        investmentAreaObject2.Name = 'Sports NSO212';
        investmentAreaObject2.Start_Date__c = date.today();
        investmentAreaObject2.End_Date__c = date.today().addDays(5);
        investmentAreaObject2.Status__c = 'Active';
        investmentAreaList.add(investmentAreaObject2);
        insert investmentAreaList;
        
        //list<Business_Case__c> BusLst = new list<Business_Case__c>();
        
        Business_Case__c businesscaseparentobject = new Business_Case__c();
        
        businesscaseparentobject.name= 'Testing Parent Business Case';
        businesscaseparentobject.Executive_Summary__c ='bla bla bla ';
        businesscaseparentobject.Status__c= 'Draft';
        businesscaseparentobject.Investment_Area__c = investmentAreaObject.id;
        //Buslst.Add(businesscaseparentobject);
        
        insert businesscaseparentobject;
        
        Test.startTest();
        
			ApexPages.StandardController stCon = new ApexPages.StandardController(businesscaseparentobject);
			StartInvestmentScheduleReportController invScheduleRep = new StartInvestmentScheduleReportController(stCon);
			invScheduleRep.startInvestmentScheduleReport();
			
			try {
				businesscaseparentobject=null;
				update businesscaseparentobject;
			 
			} catch (Exception e){
				system.debug('e.getMessage() >>>>>>>>>>>>> '+e.getMessage());
				Boolean expectedExceptionThrown =  e.getMessage().contains('Attempt to de-reference a null object') ? true : false;
				system.debug('expectedExceptionThrown >>>>>>>>>>>>> '+expectedExceptionThrown);
				System.AssertEquals(expectedExceptionThrown, true);
				
			}
		Test.stopTest();	
		
		
        
    }
}