force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Date_Signed_By_External_Party__c.field-meta.xml
<CustomField>
    <fullName>Date_Signed_By_External_Party__c</fullName>
    <description>Date the Investment Schedule was signed by the external party</description>
    <label>Date Signed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Document_Link_1__c.field-meta.xml
<CustomField>
    <fullName>Document_Link_1__c</fullName>
    <label>Document Link 1</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Document_Link_2__c.field-meta.xml
<CustomField>
    <fullName>Document_Link_2__c</fullName>
    <label>Document Link 2</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/External_Signatory__c.field-meta.xml
<CustomField>
    <fullName>External_Signatory__c</fullName>
    <description>The name of the person who signed the Investment Schedule for the Party/Vendor</description>
    <label>External Signatory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractSignedExt.cls
public with sharing class ContractSignedExt {

    public boolean show{get;set;}
    public Business_Case__c iSched {get;set;}
    public ContractSignedExt(ApexPages.StandardController con) {
        
        iSched = [Select Id, Name,Status__c, External_Signatory__c, Date_Signed_By_External_Party__c, Document_Link_1__c, 
                    Document_Link_2__c from Business_Case__c where id=:con.getId() LIMIT 1];
        if(iSched.status__c !='Approved'){
            addPageMessage('The Contract Signed fields can only be recorded when the Investment Schedule status is Approved.');
            show = false;
        }
        else{
            show = true;
        }
    }
    public PageReference saveBtn() {
        PageReference pageRef = null;
        Database.SaveResult sr = database.update(isched,false);
        if(!sr.isSuccess()) {
            for(Database.Error err : sr.getErrors()) {
                addPageMessage(ApexPages.severity.Error, err.getMessage());
            }
        } else {
            pageRef = new PageReference('/' + isched.Id);
        }
        return pageRef;
    }
    // Add Page Messages
    public void addPageMessage(ApexPages.severity severity, Object objMessage) {
        ApexPages.Message pMessage = new ApexPages.Message(severity, String.valueOf(objMessage));
        ApexPages.addMessage(pMessage);
    }
    public void addPageMessage(Object objMessage) {
        addPageMessage(ApexPages.severity.INFO, objMessage);
    }   
}