force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Executive_Summary__c.field-meta.xml
<CustomField>
    <fullName>Executive_Summary__c</fullName>
    <label>Executive Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Investment_Area__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Investment Area</label>
    <referenceTo>Investment_Area__c</referenceTo>
    <relationshipName>Business_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Investment_Area_Owner__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Schedules</relationshipLabel>
    <relationshipName>Investment_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/Investment_Area__c.object-meta.xml
<CustomObject>
    <label>Investment Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment_Area__c/fields/Investment_Area_Owner__c.field-meta.xml
<CustomField>
    <fullName>Investment_Area_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Area Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investment_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment_Area__c/fields/Strategic_Area__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Area__c</fullName>
    <label>Strategic Area</label>
    <referenceTo>Strategic_Area__c</referenceTo>
    <relationshipLabel>Investment Areas</relationshipLabel>
    <relationshipName>Investment_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/Strategic_Area__c.object-meta.xml
<CustomObject>
    <label>Strategic Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Area__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sport NZ</fullName>
            </value>
            <value>
                <fullName>High Performance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Strategic_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/sendPDFEmailClassTest.cls
@isTest
private class sendPDFEmailClassTest {
    private static testmethod void testCaseOne() {
        Account testAccount = new Account( Name = 'Test Account', Type = 'Other');
        insert testAccount;
       
        Strategic_Area__c sArea = new Strategic_Area__c();
        sArea.Name = 'Wellington';
        sArea.Entity__c = 'Sportz Anz';
        sArea.Status__c = 'Draft';
        sArea.Start_Date__c = system.Today();
        sArea.End_Date__c = system.Today().addDays(2);
        insert sArea; 
        
        Investment_Area__c iArea = new Investment_Area__c();
        iArea.Name = 'Davanti';
        iArea.Strategic_Area__c = sArea.Id;
        iArea.Status__c = 'Active';
        iArea.Start_Date__c = system.Today();
        iArea.End_Date__c = system.Today().addDays(2);
        //iArea.Investment_Area_Owner__c = usr.Id;
        insert iArea;         
                                   
        Business_Case__c businesscaseobject = new Business_Case__c();
        businesscaseobject.name= 'Testing Parent Business Case';
        businesscaseobject.Executive_Summary__c ='bla bla bla ';
        //businesscaseobject.Status__c= 'Approved';
        businesscaseobject.Investment_Area__c = iArea.id;
        insert businesscaseobject;
        
        PageReference newPageRef = Page.InitiativeSchedulePage;
        newPageRef.getParameters().put('Id',businesscaseobject.Id);
        Test.setCurrentPage(newPageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(businesscaseobject);
        sendPDFEmailClass newObj = new sendPDFEmailClass(sc);
        newObj.emailLeadPdf();
        
        System.assert(Limits.getEmailInvocations()==1);
    }    
}