force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Case__c/fields/Actual_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Approval_Date__c</fullName>
    <label>Actual Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Actual_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Actual_Approver_Name__c</fullName>
    <label>Actual Approver Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Actual_Approver_Signature__c.field-meta.xml
<CustomField>
    <fullName>Actual_Approver_Signature__c</fullName>
    <formula>IF (ISBLANK(Actual_Approver_Signature_URL__c), &quot;BLANK&quot;, IMAGE(Actual_Approver_Signature_URL__c, &quot;Signature&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Approver Signature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Actual_Approver_Title__c.field-meta.xml
<CustomField>
    <fullName>Actual_Approver_Title__c</fullName>
    <label>Actual Approver Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Executive_Summary__c.field-meta.xml
<CustomField>
    <fullName>Executive_Summary__c</fullName>
    <label>Executive Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Schedules</relationshipLabel>
    <relationshipName>Investment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Being Varied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/T_Cs__c.field-meta.xml
<CustomField>
    <fullName>T_Cs__c</fullName>
    <label>T&amp;Cs</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BC 2015 T&amp;C</fullName>
            </value>
            <value>
                <fullName>Rural Travel Fund T&amp;C</fullName>
            </value>
            <value>
                <fullName>Short form T&amp;C</fullName>
            </value>
            <value>
                <fullName>Long form T&amp;C</fullName>
            </value>
            <value>
                <fullName>New T&amp;C&apos;s</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Case__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Planned Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Business_Case__c.field-meta.xml
<CustomField>
    <fullName>Business_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Schedule</label>
    <referenceTo>Business_Case__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Partner__c</field>
            <operation>equals</operation>
            <valueField>Initiative__c.Partner__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Update the Status when you receive results against this Measure.  This will generally be when you record the Result and Result Date.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
                <default>true</default>
                <label>Removed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Partially Met</fullName>
            </value>
            <value>
                <fullName>Not Met</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PA{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount (ex GST)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>This is the due date for the payment.</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sent for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#FF9900</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#009900</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FF0000</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#DDDDDD</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Variation</fullName>
                <color>#BBBBBB</color>
                <label>Variation</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <color>#666666</color>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#333333</color>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InitiativeSchedule.cls
/**
 * InitiativeSchedule Class is a controller used to fetch all the intiatives ,related Requirements,Measures and 
   Payments to and display in a PDF format 
 */

public class InitiativeSchedule{
    public Business_Case__c objBusinessCase {get;set;}
    public Payment__c oppInstance{get;set;}
    public Id recId;
    
    public List<Initiative__c> lstInitiative{get; set;}
    public List<Payment__c> lstPayment{get; set;}
    
    public Map<String,List<Requirement__c>> mapwithNameAndRequirement{get;set;}
    public Map<Id,Map<String,List<Requirement__c>>> mapwithInitiativeIdAndMapofRequirement{get;set;}
    public Map<String,List<Measure__c>> mapwithNameAndMeasure{get;set;}
    public Map<Id,Map<String,List<Measure__c>>> mapwithInitiativeIdAndMapofMeasure{get;set;}
    public Map<Date,Payment__c> mapwithPaymentDateandAmount{get;set;}
    public Map<String,Payment__c> mapwithPaymentFinancialyearDateandAmount{get;set;}
    public Map<String,Map<String,Payment__c>> mapwithInitiativeIdAndMapofFinancialyear{get;set;}
    public Map<Id,List<Payment__c>> mapwihtInsitativeIdAndpayment{get;set;}
    public Map<Id,String> mapwithInitiaticeIdandInitiativename{get;set;}
    
    public Set<String> setReqName;
    public Set<String> setReqDescription;
    public Set<String> setMeasureName;
    public Set<String> setMeasureDescription;
     
    public Decimal sumAmount {get;set;}
    public boolean blnApproved {get;set;}
    public boolean blnTnC {get;set;}

    public InitiativeSchedule(ApexPages.StandardController stdController) {
        this.objBusinessCase = (Business_Case__c)stdController.getRecord();
       /* recId = apexpages.currentpage().getparameters().get('id');*/
        blnApproved = false;
        blnTnC = false;
        this.objBusinessCase = [Select name,Organisation__r.Name,Total_Amount__c,T_Cs__c,
                                       Executive_Summary__c,Status__c,Actual_Approval_Date__c,
                                       Actual_Approver_Title__c,Actual_Approver_Name__c,
                                       Actual_Approver_Signature__c,Actual_Approver_Signature_URL__c,
                                       Commencement_Date__c,
                                       End_Date__c,
                                       Variation_Count__c 
                                From Business_Case__c
                                Where id =: this.objBusinessCase.id];
                                
        if(objBusinessCase.Status__c == 'Approved' || objBusinessCase.Status__c == 'Signed') {
            blnApproved = true;
        }
        
        if(String.isNotBlank(objBusinessCase.T_Cs__c)) {
            blnTnC = true;
        }
        oppInstance = new Payment__c();
        mapwithNameAndRequirement = new Map<String,List<Requirement__c>>();
        mapwithInitiativeIdAndMapofRequirement = new Map<Id,Map<String,List<Requirement__c>>>();
        mapwithNameAndMeasure = new  Map<String,List<Measure__c>>();
        mapwithInitiativeIdAndMapofMeasure = new Map<Id,Map<String,List<Measure__c>>>();
        mapwithPaymentDateandAmount = new Map<Date,Payment__c>();
        mapwithPaymentFinancialyearDateandAmount = new Map<String,Payment__c>();
        mapwithInitiativeIdAndMapofFinancialyear = new Map<String,Map<String,Payment__c>>();
        mapwihtInsitativeIdAndpayment = new Map<Id,List<Payment__c>>();
        mapwithInitiaticeIdandInitiativename = new Map<Id,String>();
        fetchInitiative();
        PageReference p = Apexpages.currentPage();
        p.getHeaders().put('content-disposition', 'inline; filename=' + Label.ReportName + ' '+ objBusinessCase.Name +'.pdf');
    }
    
  /**
   * Fetch Initiative is used to fetch all the inititatives, related Requirements,Measures and payments
   */
    public void fetchInitiative() {
        
        
        lstPayment = new List<Payment__c>();
        sumAmount = 0;
        
        lstInitiative = [Select Business_Case__r.name,
                                Business_Case__r.Executive_Summary__c,
                                Business_Case__r.Commencement_Date__c,
                                Business_Case__r.End_Date__c,
                                Name,
                                Description__c,
                                Start_Date__c,
                                End_Date__c,
                                Type__c,
                                Details__c,Planned__c,
                                (Select Name,
                                        Description__c,
                                        Due_Date__c,
                                        Status__c
                                 From Requirements__r
                                 Where Status__c != 'Cancelled'
                                 AND Status__c != 'Completed'
                                 order by name,Due_Date__c),
                                
                                (Select Name,
                                        Description__c,
                                        Baseline_Formula__c,
                                        Target_Formula__c,
                                        Target_Date__c,
                                 		Status__c
                                 From Measures__r
                                 Where Status__c != 'Cancelled'
                                 AND Status__c != 'Met'
                                 AND Status__c != 'Partially Met'	
                                 order by name,Target_Date__c)
                         From Initiative__c
                         Where Business_Case__r.Id =: this.objBusinessCase.id];
                         
        lstPayment = [Select Initiative__r.Id,
                             Initiative__r.name, 
                             Date__c, 
                             Amount__c ,
                             Financial_Year__c
                      From Payment__c
                      Where Initiative__r.Business_Case__c =:this.objBusinessCase.id 
                      	   AND Status__c != 'Cancelled'
                      order by  Date__c ASC];
        
        // Callculate sum amount              
        for(Payment__c objPayment : lstPayment) {
            
            Payment__c oppAmount = new Payment__c();
            if(objPayment.Date__c != null) {
                        
                if(mapwithPaymentDateandAmount.containskey(objPayment.Date__c)){
                    
                    oppAmount = mapwithPaymentDateandAmount.get(objPayment.Date__c);
                    
                    if(objPayment.Amount__c != null)
                    oppAmount.Amount__c =  oppAmount.Amount__c + objPayment.Amount__c;
                    
                    mapwithPaymentDateandAmount.put(objPayment.Date__c,oppAmount);
                }            
                else {
                    if(objPayment.Amount__c != null)
                    oppAmount.Amount__c = objPayment.Amount__c;
                    
                    mapwithPaymentDateandAmount.put(objPayment.Date__c,oppAmount);
                }   
            }
            
            if(objPayment.Initiative__r.Id != null) {
                if(mapwihtInsitativeIdAndpayment.containskey(objPayment.Initiative__r.Id)) {
                    mapwihtInsitativeIdAndpayment.get(objPayment.Initiative__r.Id).add(objPayment);
                }
                else {
                    mapwihtInsitativeIdAndpayment.put(objPayment.Initiative__r.Id,new List<Payment__c>{objPayment});
                }
            }
            
            if(objPayment.Amount__c != null)
            sumAmount = sumAmount + objPayment.Amount__c;
        }
        
        
        oppInstance.Amount__c = sumAmount;
                        
        for(Initiative__c objInitiative : lstInitiative) {
            setReqDescription = new Set<String>();
            setMeasureDescription = new Set<String>();
            Payment__c oppAmount = new Payment__c();
            mapwithNameAndRequirement = new Map<String,List<Requirement__c>>();
            mapwithNameAndMeasure = new  Map<String,List<Measure__c>>();
            mapwithPaymentFinancialyearDateandAmount = new Map<String,Payment__c>();
            
            
            // Map for Initiative id and name usefull for displaying name in payments
            
            mapwithInitiaticeIdandInitiativename.put(objInitiative.Id,objInitiative.Name);
            
            // Insert values in Map for Requirements
            for(Requirement__c objRequirement : objInitiative .Requirements__r) {
                //if(objRequirement.Status__c != 'Cancelled'){
                    string tempreq = objRequirement.Name.trim();
                    
                    if(objRequirement.Description__c != null) {
                        tempreq = tempreq + objRequirement.Description__c.trim();
                    }
                    else {
                        tempreq = tempreq + objRequirement.Description__c;
                    }
                    if(setReqDescription.contains(tempreq.trim())) {
                        objRequirement.Description__c = null;
                    }
                    else {
                        if(!String.isBlank(objRequirement.Description__c))
                        setReqDescription.add(tempreq.trim());
                    }
                    if(mapwithNameAndRequirement.containskey(objRequirement.Name)){
                        
                        mapwithNameAndRequirement.get(objRequirement.Name).add(objRequirement);
                    }            
                    else {
                        mapwithNameAndRequirement.put(
                            objRequirement.Name,new List<Requirement__c>{objRequirement});
                    }
                }
            //}
            
            if(mapwithInitiativeidAndMapofRequirement.containskey(objInitiative.Id)) {
                mapwithInitiativeidAndMapofRequirement.put(objInitiative.Id,mapwithNameAndRequirement);             
            }
            else {
                mapwithInitiativeidAndMapofRequirement.put(objInitiative.Id,mapwithNameAndRequirement);
            }
        
            // Insert values in Map for Measures
            
            for(Measure__c objMeasure : objInitiative .Measures__r) {
                //if(objMeasure.Status__c != 'Cancelled'){
                    String temp = objMeasure.Name.trim();
                    
                    if(objMeasure.Description__c != null) {
                        temp = temp + objMeasure.Description__c.trim();
                    }
                    else {
                        temp = temp + objMeasure.Description__c;
                    }
                    
                    if(setMeasureDescription.contains(temp.trim())) {
                        objMeasure.Description__c = null;
                    }
                    else {
                        if(!String.isBlank(objMeasure.Description__c))
                            setMeasureDescription.add(temp.trim());
                    }
                    if(mapwithNameAndMeasure.containskey(objMeasure.Name)) {
                        mapwithNameAndMeasure.get(objMeasure.Name).add(objMeasure);
                    }            
                    else {
                        mapwithNameAndMeasure.put(objMeasure.Name,new List<Measure__c>{objMeasure});
                    }
                }
           // }
            
            if(mapwithInitiativeIdAndMapofMeasure.containskey(objInitiative.Id)) {
                mapwithInitiativeIdAndMapofMeasure.put(objInitiative.Id,mapwithNameAndMeasure);             
            }
            else{
                mapwithInitiativeIdAndMapofMeasure.put(objInitiative.Id,mapwithNameAndMeasure);
            }
            
            if(mapwihtInsitativeIdAndpayment.containskey(objInitiative.Id)) {
                for(Payment__c objPayment : mapwihtInsitativeIdAndpayment.get(objInitiative.Id)) {
                    if(objPayment.Financial_Year__c != null) {
                        oppAmount = new Payment__c();
                        if(mapwithPaymentFinancialyearDateandAmount.containskey(objPayment.Financial_Year__c)) {
                    
                            oppAmount = mapwithPaymentFinancialyearDateandAmount.get(objPayment.Financial_Year__c);
                            oppAmount.Amount__c =  oppAmount.Amount__c + objPayment.Amount__c;
                            mapwithPaymentFinancialyearDateandAmount.put(objPayment.Financial_Year__c,oppAmount);
                        }            
                        else {
                            oppAmount.Amount__c = objPayment.Amount__c;
                            mapwithPaymentFinancialyearDateandAmount.put(
                            objPayment.Financial_Year__c,oppAmount);
                        }
                
                
                    }
            
                    if(objPayment.Initiative__r.name != null) {
                        if(mapwithInitiativeIdAndMapofFinancialyear.containskey(objPayment.Initiative__c)) {
                            mapwithInitiativeIdAndMapofFinancialyear.put(objPayment.Initiative__c,mapwithPaymentFinancialyearDateandAmount);           
                        }
                        else {
                            mapwithInitiativeIdAndMapofFinancialyear.put(objPayment.Initiative__c,mapwithPaymentFinancialyearDateandAmount);
                        }
                    }
                }
            }
        }
   }
}