force-app/main/default/objects/Business_Case__c/Business_Case__c.object-meta.xml
<CustomObject>
    <label>Investment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/Business_Case__c.field-meta.xml
<CustomField>
    <fullName>Business_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment Schedule</label>
    <referenceTo>Business_Case__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( (Is_Initiative_Closed__c = true &amp;&amp; End_Date__c &lt; TODAY()) || ($User.Id = Investment_Area__r.Investment_Area_Owner__r.Id &amp;&amp; Close_the_Initiative__c = true &amp;&amp; Total_Completed_Requirements__c = Total_Requirements__c &amp;&amp; Total_Payments__c = Total_Completed_Payments__c &amp;&amp; Pending_Measures__c = 0), 
&quot;Closed&quot;, 
IF(OR(isblank(Business_Case__c),text(Business_Case__r.Status__c) = &quot;Draft&quot;,text(Business_Case__r.Status__c) = &quot;Rejected&quot;), 

&quot;Draft&quot;, 

IF(text(Business_Case__r.Status__c) = &quot;Pending Approval&quot;, 

&quot;Pending Investment Schedule Approval&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c = 0), 

&quot;Approved&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Scheduled__c &gt; 0), 

&quot;Scheduled&quot;, 

IF(AND(OR(text(Business_Case__r.Status__c) = &quot;Approved&quot;,text(Business_Case__r.Status__c) = &quot;Signed&quot;),Planned__c = Paid__c), 

&quot;Paid&quot;,

IF(text(Business_Case__r.Status__c) = &quot;Being Varied&quot;,&quot;Variation&quot; ,

&quot;Error&quot; 

)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PA{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>This is the due date for the payment.</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Old_Status__c.field-meta.xml
<CustomField>
    <fullName>Old_Status__c</fullName>
    <label>Old Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Overdue_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Overdue_Requirements__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overdue Requirements</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Pending_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Pending_Requirements__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Requirements</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/RUL_Old_RecordType_Id__c.field-meta.xml
<CustomField>
    <fullName>RUL_Old_RecordType_Id__c</fullName>
    <label>Old RecordType Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sent for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/recordTypes/Payment.recordType-meta.xml
<RecordType>
    <fullName>Payment</fullName>
    <active>true</active>
    <description>For all payments going from Sport NZ Group to an investment recipient or service provider</description>
    <label>Payment</label>
</RecordType>

force-app/main/default/classes/BatchApexForPaymentFromFlow.cls
global class BatchApexForPaymentFromFlow implements Database.Batchable<sObject>, Database.Stateful {

    public Date payDate;
    public integer count = 0;
  
    public BatchApexForPaymentFromFlow(List<Date> datelist)

    {
		Date dT=datelist.get(0);
        Date dateFromDateTime = Date.newInstance(dT.year(), dT.month(), dT.day());
        system.debug('dateFromDateTime : '+dateFromDateTime);
        //this.payDate= datelist.get(0);
        this.payDate = dateFromDateTime;

    }

    public class FlowInputs {

        @InvocableVariable public List<Date> pDate;

    }

    @invocablemethod(label='Get Payment records to change status')

    public static void getPaymentRecords(List<FlowInputs> reqDate)

    {

        system.debug('Date List : '+reqDate);
        List<date> conlist = new List<date>();

        for(FlowInputs req : reqDate)   

        {

            conlist.addAll(req.pDate);

        }

        Id jobId = Database.executeBatch(new BatchApexForPaymentFromFlow(conlist));

    }

   
   global Database.QueryLocator start(Database.BatchableContext BC){

      String query = 'SELECT Id, Old_Status__c,Status__c,Initiative__r.Status__c,RUL_Old_RecordType_Id__c,Date__c,'  
          			 +'Initiative__r.Business_Case__r.Status__c,Initiative__r.Business_Case__r.Id,Initiative__r.Business_Case__r.Name'
                     +' from Payment__c'
                     +' where Date__c = :payDate'
				     +' and (Initiative__r.Business_Case__r.Status__c=\'Approved\' or Initiative__r.Business_Case__r.Status__c=\'Signed\' )'
                     +' and (Initiative__r.Status__c =\'Approved\' or Initiative__r.Status__c =\'Scheduled\')'
                     +' and Status__c =\'Variation\' and Overdue_Requirements__c = '+False+'  and Pending_Requirements__c = '+False;

      return Database.getQueryLocator(query);

   }

    global void execute(Database.BatchableContext BC , List<Payment__c> scope){
    	system.debug('Scope is : '+scope);
        system.debug('Size of list : '+scope.size());
       // integer count = 0;
        if(scope != null && !scope.isEmpty()) {
            for(Payment__c p : scope) {
                p.status__c = 'Scheduled';
            }
            try{

                Database.SaveResult[] ds =  Database.update(scope,false);
                
                for(Database.SaveResult d : ds){
                    system.debug('@@in for loop');
                    if(d.isSuccess()){
                        system.debug('@@in if in for');
                        count++;
                        
                    }
                    system.debug('count in for = '+count);
                    
                }
                system.debug('count : '+count);
                             
            }
            
            catch(exception e){
                
                system.debug('update failed');
           }
        }
    }

   global void finish(Database.BatchableContext BC){
        
       system.debug('Actual count in finish: '+count);
      // ReturnPaymentProcessedToFlow rpf=new ReturnPaymentProcessedToFlow();
       //List<String> result = ReturnPaymentProcessedToFlow.sendMsg(msg); // Correct
       //return result;
        CustomNotificationType statusChangeNotification = [SELECT Id, 
                                                        DeveloperName  
                                                        FROM CustomNotificationType  
                                                        WHERE DeveloperName='PaymentStatusChangeNotification' 
                                                        LIMIT 1]; 
       
                String body = 'Status of  ' +count +' payment records is changed from Variation to Scheduled.'; 
                Messaging.CustomNotification Notification = new Messaging.CustomNotification(); 
                Notification.setNotificationTypeId(statusChangeNotification.id); 
                Notification.setSenderId(Userinfo.getUserId()); 
                Notification.setBody(body); 
                Notification.setTitle('Payment status changed to scheduled'); 
                Notification.setTargetId('a0G6F00002ovTIJUA2'); 
                Notification.send(new Set<String> {Userinfo.getUserId()}); 
              
   }

}